### ISSUE TITLE
[v4] If i try play some spotify music, this happened

### ISSUE THREAD

**Issue by TristannSadge** [SudhanPlayz/Discord-MusicBot#1000]
![image](https://user-images.githubusercontent.com/108361190/179401817-d79e6e58-316c-4345-9c4c-9d404755dc9a.png)
![image](https://user-images.githubusercontent.com/108361190/179401825-48b901f1-a1e3-4335-99e4-bc837022655d.png)

**Comment by JotaroKujo0525** [comment]
are you on the current commit

**Comment by JotaroKujo0525** [comment]
There, before anything is done. Please let me know if you are on the current commit. Give me instructions on how you installed this

**Comment by TristannSadge** [comment]
> There, before anything is done. Please let me know if you are on the current commit. Give me instructions on how you installed this

I install this on replit.

Copy repo from git, and edit only config file.

The rest did not interest me.

**Comment by JotaroKujo0525** [comment]
hello, please try using the prefix commands and see

**Comment by DarrenOfficial** [comment]
did you put in the spotify clientId and secrets correctly?

**Comment by XstreamSpeed** [comment]
> did you put in the spotify clientId and secrets correctly?

I thought v5 came built in with that, also its not very common but 30% of my bots run time I get an error saying failed to renew Spotify token, I'm not sure from where the code is originating when I tried to search for it.

**Comment by LewdHuTao** [comment]
> I thought v5 came built in with that, also its not very common but 30% of my bot's run time I get an error saying failed to renew Spotify token, I'm not sure from where the code is originating when I tried to search for it.

this are not v4 so you have to spotify clientId and secret manually
