### ISSUE TITLE
Heroku 18.x Bug

### ISSUE THREAD

**Issue by vinceroti** [SudhanPlayz/Discord-MusicBot#1002]
**Please describe the problem you are having in as much detail as possible:**
v5 branch which is deployed to heroku has an issue when searching a song.

### Essentials:

- Bot Version: v5 Branch
- Commit Hash: 7d360bf093e886cc8a3a39144c179740c50e41ea
- Node.js version: Latest 18.x
- Operating system: Ubuntu using heroku

Heroku attempts to update to 18.x which is providing this error when searching for a song

```
An error occured
There was an error while searching: Unexpected token  in JSON at position 0
If you think this as a bug, please report it in the support server!
```

If you change this value in `package.json` it should fix this issue and keep heroku at node LTS

```
  "engines": {
    "node": "^16.x"
  },
  ```

**Comment by JotaroKujo0525** [comment]
what exactly did you do for this to occur?

**Comment by JotaroKujo0525** [comment]
you searched a song right?

**Comment by ChongZhiJie0216** [comment]
I also have the same problem

**Comment by vinceroti** [comment]
> you searched a song right?

Yes when I search for a song

@ChongZhiJie0216 if you update your package.json `engines` key to what I updated it should fix your problem

**Comment by JotaroKujo0525** [comment]
aight, i'll change the package.json

**Comment by JotaroKujo0525** [comment]
@vinceroti what did you search exactly? YouTube or Spotify?

**Comment by ChongZhiJie0216** [comment]
I tried it and it still doesn't work. I have the same problem with Master and v5. I'm not sure if it's caused by my own lavalink.

**Comment by JotaroKujo0525** [comment]
its from the package `better-erela.js-spotify` (idk if this package name is correct)

**Comment by JotaroKujo0525** [comment]
try switching lavalinks, i'm still finding the cause of this

**Comment by ChongZhiJie0216** [comment]
I just tested someone else's lavalink, not by myself, but by someone else on the Internet, the problem is the same

**Comment by JotaroKujo0525** [comment]
hello! as i said. **THIS IS NOT A PROBLEM WITH NODE**, it's a problem with the package `better-erela.js-spotify`

**Comment by JotaroKujo0525** [comment]
i already tried hosting v5 on heroku and it does work

**Comment by JotaroKujo0525** [comment]
you can look at this [issue](https://github.com/NezuChan/better-erela.js-spotify/issues/20)

**Comment by JotaroKujo0525** [comment]
I'll test the bot again and debug this issue, sorry for the slow response, I'm the only one managing the issues rn

**Comment by vinceroti** [comment]
That is okay, just providing some helpful feedback. Heroku is working fine on my end when I changed my key. 

I was getting this error regardless of v5 or if I was on main

**Comment by JotaroKujo0525** [comment]
fixed!

**Comment by JotaroKujo0525** [comment]
also,for those who are confused, this is only for `v5` branch, if you can't search Spotify on master, either change your Spotify key or change your lavalink
