### ISSUE TITLE
Leave when no people in current voice

### ISSUE THREAD

**Issue by amirulasri** [SudhanPlayz/Discord-MusicBot#1013]
I use V5 in my private server, when bot in loop mode, it not leaving even no one in the voice... I hope for the next update/commit have that feature! 😄

**Comment by JotaroKujo0525** [comment]
uh can you specify what is `this version`

**Comment by XstreamSpeed** [comment]
> uh can you specify what is `this version`

V5

**Comment by JotaroKujo0525** [comment]
ah so basically, in loop mode, make the bot leave when no one is in vc

**Comment by KiyoshiKunCool** [comment]
@amirulasri I have done your request by this pr #1023 :3
