### ISSUE TITLE
heroku not working

### ISSUE THREAD

**Issue by masterofninja** [SudhanPlayz/Discord-MusicBot#1014]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.
pls fix
![146274858-ebf0bfc1-ed95-41f9-9e44-f37013123b8e](https://user-images.githubusercontent.com/61804793/180686272-aa7a0cd4-36f3-41fa-b415-f1fd980e6f87.png)

**Comment by masterofninja** [comment]
the template shows that but if I do it an fork  of it then it would work

**Comment by JotaroKujo0525** [comment]
fork then remove readme.md

**Comment by JotaroKujo0525** [comment]
please dont put bug label if its not really a bug in the code

**Comment by masterofninja** [comment]
im new to the GitHub
