### ISSUE TITLE
Unexpected token in JSON at position 0

### ISSUE THREAD

**Issue by Flaam** [SudhanPlayz/Discord-MusicBot#1016]
**Please describe the problem you are having in as much detail as possible:**

![image](https://user-images.githubusercontent.com/48182219/181082108-08175aa6-f88f-4495-a35c-41974c7249d5.png) 
### Essentials:

Wanted to open the issue on Discord but I'm still not verified
- Bot Version: v5
- Commit Hash: 6cf4828
- Node.js version: 18.6.0
- Operating system: Ubuntu

#### Additional system info
- Is it virtualized? (Docker or ...) : AWS

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by JotaroKujo0525** [comment]
downgrade to node 16

**Comment by JotaroKujo0525** [comment]
also,please just wait on the discord server because the verification bot is down temporarily

**Comment by Flaam** [comment]
Downgrading resolved the issue, thank you, have a great day.
