### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by XstreamSpeed** [SudhanPlayz/Discord-MusicBot#1039]
**Please describe the problem you are having in as much detail as possible:**

https://youtu.be/pzL8uTIE9A8

### Essentials:

- Bot Version: v13.8.0
- Commit Hash: latest
- Node.js version: v18.7.0
- Operating system: linux-oracle

#### Additional system info
- Is it virtualized? (Docker or ...) : i dont know
- What CPU is it running on (X86 or ARM or...): Neoverse-N1
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by urbels** [comment]
I think its lavalink. Check your lavalink log. I have the same thing happening time to time but no idea how to fix it. This error was reported on lavalink github year ago ang got fixed but aparently still happening.

**Comment by JotaroKujo0525** [comment]
yes, it could be a lavalink error

**Comment by XstreamSpeed** [comment]
> yes, it could be a lavalink error

I thought of that too, but both of my lavalink nodes seems to be working, I even changed nodes yet it was still happening.

**Comment by XstreamSpeed** [comment]
> I think its lavalink. Check your lavalink log. I have the same thing happening time to time but no idea how to fix it. This error was reported on lavalink github year ago ang got fixed but aparently still happening.

Both my lavalink nodes were connected on startup and I didn't receive any other notifications regarding the lavalink after that

**Comment by urbels** [comment]
Did you check your lavalink log when its happening?

**Comment by XstreamSpeed** [comment]
> Did you check your lavalink log when its happening?

Yes, I did, nothing showed up

**Comment by XstreamSpeed** [comment]
I deleted that #test channel and now its spamming discord api errors saying missing access, even after restarting the bot!

**Comment by XstreamSpeed** [comment]
[!image](https://discord.com/channels/890079727090561104/900623405429190666/1007561984054669323)

**Comment by LewdHuTao** [comment]
> ![image](https://camo.githubusercontent.com/bffd97ce274253e26f53f04f173bb6894dd38b4b34784ba97c1e01352ff512a2/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3930303632333430353432393139303636362f313030373536313938333438383434323434382f756e6b6e6f776e2e6a706567)

check node.js version if its node 17 downgrade to node 16

**Comment by XstreamSpeed** [comment]
Given above is the error I get in my console when I try to search for a song, under the "LOAD_FAILED" case.

**Comment by XstreamSpeed** [comment]
> > ![image](https://camo.githubusercontent.com/bffd97ce274253e26f53f04f173bb6894dd38b4b34784ba97c1e01352ff512a2/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3930303632333430353432393139303636362f313030373536313938333438383434323434382f756e6b6e6f776e2e6a706567)
> 
> check node.js version if its node 17 downgrade to node 16

It's Node 18

**Comment by LewdHuTao** [comment]
> It's Node 18

ye downgrade it to 16

**Comment by XstreamSpeed** [comment]
Alr

**Comment by JotaroKujo0525** [comment]
if this is v5, node 18 breaks some of the modules included in the bot so don't run it in there

**Comment by XstreamSpeed** [comment]
Alright, thank you
