### ISSUE TITLE
My bot doesnt go online 

### ISSUE THREAD

**Issue by lucid-OmO** [SudhanPlayz/Discord-MusicBot#1045]
so after i follow the instruction in the youtube video somehow my bot doesnt go online, here is what i got in the console 
`npm run start

> discord-musicbot@4.1.4 start
> node index

Replit system detected, initiating special `unhandledRejection` event listener
15:7:2022 - 17:19 | Info: Web Server has been started
15:7:2022 - 17:19 | Info: Event Loaded: guildCreate
15:7:2022 - 17:19 | Info: Event Loaded: message
15:7:2022 - 17:19 | Info: Event Loaded: raw
15:7:2022 - 17:19 | Info: Event Loaded: ready
15:7:2022 - 17:19 | Info: Event Loaded: voiceStateUpdate
15:7:2022 - 17:19 | Info: Command Loaded: bassboost
15:7:2022 - 17:19 | Info: Command Loaded: bump
15:7:2022 - 17:19 | Info: Command Loaded: clear
15:7:2022 - 17:19 | Info: Command Loaded: config
15:7:2022 - 17:19 | Info: Command Loaded: disconnect
15:7:2022 - 17:19 | Info: Command Loaded: grab
15:7:2022 - 17:19 | Info: Command Loaded: help
15:7:2022 - 17:19 | Info: Command Loaded: invite
15:7:2022 - 17:19 | Info: Command Loaded: loop
15:7:2022 - 17:19 | Info: Command Loaded: loopqueue
15:7:2022 - 17:19 | Info: Command Loaded: lyrics
15:7:2022 - 17:19 | Info: Command Loaded: move
15:7:2022 - 17:19 | Info: Command Loaded: nowplaying
15:7:2022 - 17:19 | Info: Command Loaded: pause
15:7:2022 - 17:19 | Info: Command Loaded: play
15:7:2022 - 17:19 | Info: Command Loaded: queue
15:7:2022 - 17:19 | Info: Command Loaded: remove
15:7:2022 - 17:19 | Info: Command Loaded: resume
15:7:2022 - 17:19 | Info: Command Loaded: search
15:7:2022 - 17:19 | Info: Command Loaded: seek
15:7:2022 - 17:19 | Info: Command Loaded: shuffle
15:7:2022 - 17:19 | Info: Command Loaded: skip
15:7:2022 - 17:19 | Info: Command Loaded: skipto
15:7:2022 - 17:19 | Info: Command Loaded: stats
15:7:2022 - 17:19 | Info: Command Loaded: volume
15:7:2022 - 17:19 | Info: Command Loaded: youtube
`
*im still new in this kind of thing

**Comment by JotaroKujo0525** [comment]
`kill 1` or `kill 0` in shell, and just wait a few minutes
