### ISSUE TITLE
Parsing error in play.js

### ISSUE THREAD

**Issue by XstreamSpeed** [SudhanPlayz/Discord-MusicBot#1058]
**Please describe the problem you are having in as much detail as possible:**

![image](https://user-images.githubusercontent.com/79592017/187207315-660a2523-d30a-462d-b23f-fdaf69b7f62c.png)

### Essentials:

- Bot Version: v13.8.0
- Commit Hash: unknown
- Node.js version: 16.17.0
- Operating system: linux 5.15.0-1016-oracle

#### Additional system info
- Is it virtualized? (Docker or ...) : Is run on a container
- What CPU is it running on (X86 or ARM or...): Neoverse-N1
- Additional details that might help us figure out the problem: null

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by XstreamSpeed** [comment]
Basically, when I use /play I get a error from the bot saying "There was an error while searching" meaning the load failed, my lavalink nodes are perfectly intact and have no errors in them. I am currently using the Japan Node which was added by Islantay on lavalink-list. My crash handler then sends this message, some suggested its an API change and it is a parsing error.

**Comment by MiracleCherryPie** [comment]
Also try with another one if it doesn't work too

**Comment by cobianic** [comment]
for some reason bot doesn`t work with Node.js 16.17, use 16.16 or lower

**Comment by JotaroKujo0525** [comment]
nah the bot works on versions 16.6.0, and node 17

**Comment by JotaroKujo0525** [comment]
let me know if this fixes it

**Comment by XstreamSpeed** [comment]
NodeJS 17.9.1 seems to be compatible, this issue is solved.
