### ISSUE TITLE
play error

### ISSUE THREAD

**Issue by NettyByte** [SudhanPlayz/Discord-MusicBot#1063]
**Please describe the problem you are having in as much detail as possible:**

### Essentials:

- Bot Version : Newst
- Node.js version: v16.17.0
- Operating system: Debian 10

When I type /play song name the error There was an error while searching: Unexpected token in JSON at position 0 and when I type /play (spotify link) it works

![unknown](https://user-images.githubusercontent.com/85581909/188461179-c2e06e74-ddc4-4cf7-ac19-beee8848e4e1.png)

**Comment by JotaroKujo0525** [comment]
hello is this v5 or v4

**Comment by JotaroKujo0525** [comment]
also please downgrade to 16.6.0 or 17.x

**Comment by NettyByte** [comment]
Not working

**Comment by resvoke** [comment]
me too

**Comment by JotaroKujo0525** [comment]
please ask in the discord server

**Comment by Zyo20** [comment]
i also have the same problem.
![image](https://user-images.githubusercontent.com/24516479/190549381-b7892a3a-f0d3-4349-b0ad-f2af925fddfd.png)

**Comment by JotaroKujo0525** [comment]
Hello, please update your version into 17.x, I'll close this issue since its already been solved

**Comment by JotaroKujo0525** [comment]
please ask in the discord server rather than prolonging this issue
