### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by eccentricPACHARA** [SudhanPlayz/Discord-MusicBot#1064]
- Bot Version: 4.1.4
- Node.js version: 12.22.12
- Operating system:  Window

![image](https://user-images.githubusercontent.com/47096657/188559857-4f41c139-5447-4959-a512-f1583fcab68a.png)

**Comment by eccentricPACHARA** [comment]
![image](https://user-images.githubusercontent.com/47096657/188561687-043c9e3d-48db-4625-9a56-63a5dd3f069a.png)

**Comment by LewdHuTao** [comment]
> ![image](https://user-images.githubusercontent.com/47096657/188561687-043c9e3d-48db-4625-9a56-63a5dd3f069a.png)

this error occurred when interaction already been acknowledged but it didn’t reply, may i know which command you’re running to cause that error?

**Comment by LewdHuTao** [comment]
> All Bot Version v4 and v5 need NodeJs version 14+
> ~[prerequisites](https://github.com/SudhanPlayz/Discord-MusicBot#-prerequisites)

it has nothing to do with node version

**Comment by eccentricPACHARA** [comment]
> 

/play

**Comment by eccentricPACHARA** [comment]
after I do /play glimpe of us
this occur
![image](https://user-images.githubusercontent.com/47096657/188599702-a8f64778-4d8c-474d-9b78-8bf0d9891436.png)
but bot didnt join the voice chat

**Comment by LewdHuTao** [comment]
> after I do /play glimpe of us
> this occur
> ![image](https://user-images.githubusercontent.com/47096657/188599702-a8f64778-4d8c-474d-9b78-8bf0d9891436.png)
> but bot didnt join the voice chat

did you try changing the lavalink?

**Comment by eccentricPACHARA** [comment]
> > after I do /play glimpe of us
> > this occur
> > ![image](https://user-images.githubusercontent.com/47096657/188599702-a8f64778-4d8c-474d-9b78-8bf0d9891436.png)
> > but bot didnt join the voice chat
> 
> did you try changing the lavalink?

not yet

**Comment by eccentricPACHARA** [comment]
but I just changed node version to 16.x and the problem changed to this 
![image](https://user-images.githubusercontent.com/47096657/188604636-83eda567-f778-4536-80b8-ddc459c61846.png)

**Comment by LewdHuTao** [comment]
> but I just changed node version to 16.x and the problem changed to this
> ![image](https://user-images.githubusercontent.com/47096657/188604636-83eda567-f778-4536-80b8-ddc459c61846.png)

change to node 16.6.0 or 16.5.0 or 17.x

**Comment by eccentricPACHARA** [comment]
ok now 
![image](https://user-images.githubusercontent.com/47096657/188606185-7e623e95-aa3b-4841-8129-867add8406f7.png)
the bot didnt join the voice chat

**Comment by eccentricPACHARA** [comment]
ok now it is working

**Comment by eccentricPACHARA** [comment]
appreciate your help bro thank

**Comment by LewdHuTao** [comment]
ig i can close this issue for now, if you have any problems/error you can reopen or make a new issue

**Comment by JotaroKujo0525** [comment]
next time, you can ask in the discord server
