### ISSUE TITLE
V5  [MessageEmbed#addField]

### ISSUE THREAD

**Issue by wibe01204** [SudhanPlayz/Discord-MusicBot#1078]
**Please describe the problem you are having in as much detail as possible:**

`(node:25676) DeprecationWarning: MessageEmbed#addField is deprecated and will be removed in the next major update. Use MessageEmbed#addFields instead.`
(Use `node --trace-deprecation ...` to show where the warning was created)

### Essentials:

- Bot Version: v5.0.0-beta; Build: c187efc
- Commit Hash: c187efc
- Node.js version: 16.17.0
- Operating system: Microsoft Windows 11

#### Additional system info
- Is it virtualized? (Docker or ...) : not virtualized
- What CPU is it running on (X86 or ARM or...): X86
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

![image](https://user-images.githubusercontent.com/90883053/190912125-93537482-d278-450a-a829-cb04ed8a4557.png)

**Comment by kiyoshikuncool** [comment]
Which command are you get trouble in, my friend? :3

**Comment by wibe01204** [comment]
@kiyoshikuncool `play` command
it just show "Searching..." and nothing happend
![image](https://user-images.githubusercontent.com/90883053/190952304-5a16b335-7967-4721-afcf-c838de88ae9b.png)

**Comment by kiyoshikuncool** [comment]
Oh boiiii, this is insane. I'll check it for you

**Comment by Buronn** [comment]
Update to Node v17 (I personally recommend 17.0.1, if you are using docker, use this image `node:17.0.1-alpine`)

**Comment by MiracleCherryPie** [comment]
I tell to y'all to ask general questions in support server

**Comment by MiracleCherryPie** [comment]
Also this isn't the error bruh
