### ISSUE TITLE
ChangeAble Prefix

### ISSUE THREAD

**Issue by DarkTheif** [SudhanPlayz/Discord-MusicBot#108]
**Is your feature request related to a problem? Please describe.**
Most servers want a different prefix because other bots have the same one

**Describe the solution you'd like**
It would be nice if you guys could use mongoosedb to have a changeable prefix like a new branch called prefix or something and have it where people can use their own database or something to let people change the prefix of the bot per server

**Describe alternatives you've considered**
I have looked into changing it myself and I can get it to work but none of the music commands like !play or anything else like that work so while I am getting somewhere I still haven't gotten it to fully work

**Comment by SudhanPlayz** [comment]
has been added to #72
