### ISSUE TITLE
failed to obtain access token

### ISSUE THREAD

**Issue by priyam1234-spec** [SudhanPlayz/Discord-MusicBot#1084]
**Please describe the problem you are having in as much detail as possible:**
InternalOAuthError: Failed to obtain access token
it shows this error when i authorize the bot after i click on dashboard
everything in config is filled

### Essentials:

- Bot Version: 4.1.2
- Commit Hash:
- Node.js version: idk cant see
- Operating system: replit 

#### Additional system info
- Is it virtualized? (Docker or ...) :
- What CPU is it running on (X86 or ARM or...):
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by damiennnnn** [comment]
Having the same issue with OAuth when trying to use the dashboard

**Comment by JotaroKujo0525** [comment]
Reasons:
-Not filled botconfig.js
-Slow host

First, check your botconfig.js if it's all fine, and the next problem is your host which is replit, it's slow

**Comment by damiennnnn** [comment]
Botconfig.js is filled correctly

I am hosting on an Oracle Cloud instance which has ample performance available

**Comment by JotaroKujo0525** [comment]
please ask in the discord server for more in-depth support
