### ISSUE TITLE
I cant use play

### ISSUE THREAD

**Issue by lopackhak333** [SudhanPlayz/Discord-MusicBot#1089]
An error occured
There was an error while searching: Unexpected token  in JSON at position 0[
![Screenshot_60](https://user-images.githubusercontent.com/90701868/192157466-199019ae-d092-4b46-a359-9792907448f1.png)
](url)

**Comment by kismomesz** [comment]
I have this problem too.

**Comment by JotaroKujo0525** [comment]
Downgrade/Upgrade to Nodejs 17.x

**Comment by CheeFaitLer** [comment]
> Downgrade/Upgrade to Nodejs 17.x

![image](https://user-images.githubusercontent.com/71252760/192538371-f8f1dc5a-8a6a-4d05-b5bf-6d14a35d8b49.png)

![image](https://user-images.githubusercontent.com/71252760/192538488-7db33798-ba9c-4d52-b0fb-2b4c52c1cc8c.png)
