### ISSUE TITLE
`generate-musicbot-id` error

### ISSUE THREAD

**Issue by banool** [SudhanPlayz/Discord-MusicBot#1093]
### Essentials:

- Bot Version: v5
- Commit Hash: f9bdf467950f0bce0f2fb2f34ead4ef8afc58db7
- Node.js version: 16.16
- Operating system: Arch

### Additional system info
- Is it virtualized? (Docker or ...) : Raw metal
- What CPU is it running on (X86 or ARM or...): x86
- Additional details that might help us figure out the problem:

### Report
When I clone the v5 repo, delete it, then clone it again and run `yarn install` and `yarn start`, I get this error:
```
chmod: cannot access 'generate-musicbot-id*': No such file or directory
```

The first time I ran it it worked, but I can't seem to make this error go away.

**Comment by Neko-Life** [comment]
Try updating to the latest commit of the v5 branch. The error should be gone already.
