### ISSUE TITLE
Spotify links don't work when they contain url paramter

### ISSUE THREAD

**Issue by 0yz** [SudhanPlayz/Discord-MusicBot#1098]
When you go to the Spotify desktop app on Windows, right click a song, share and click copy url it will add a "?si=xxxxx123456" reference parameter at the end of the url for Spotifys tracking. 
The bot doesn't seem to understand those URLs.
It will return
`No matches found for - https://open.spotify.com/track/528z84miB4evk5i33FMLKK?si=9fbaa0cd9b32477a`
so you have to manually remove the parameter every time you copy a url out of Spotify.

awesome bot btw, thank you!

**Comment by GazorHuman** [comment]
Are you sure? I've tried to play a song with Spotify url + the parameter, it works normally, and not showing "no matches found for".

**Comment by GazorHuman** [comment]
Btw are you using V4 or V5?

**Comment by 0yz** [comment]
Sorry for the late reply. I don't know why but after restarting the bot it just started working. Thank you though!
