### ISSUE TITLE
i keep getting a error

### ISSUE THREAD

**Issue by matthew42904** [SudhanPlayz/Discord-MusicBot#1102]
when i run the npm run deploy it gives me this error:
![image](https://user-images.githubusercontent.com/43304608/196002678-c0e85c28-2c38-4a88-b1c1-15fe37e59baf.png)

**Comment by kotik1998** [comment]
same

**Comment by GazorHuman** [comment]
> when i run the npm run deploy it gives me this error:
> 
> ![image](https://user-images.githubusercontent.com/43304608/196002678-c0e85c28-2c38-4a88-b1c1-15fe37e59baf.png)
> 
> 

Is that V4?

**Comment by matthew42904** [comment]
Happens on v5 and master

**Comment by matthew42904** [comment]
> Update your nodejs

It happens on 14, 16, and 18

**Comment by matthew42904** [comment]
> > when i run the npm run deploy it gives me this error:
> > ![image](https://user-images.githubusercontent.com/43304608/196002678-c0e85c28-2c38-4a88-b1c1-15fe37e59baf.png)
> 
> Is that V4?

I had it happen on v5 and master

**Comment by matthew42904** [comment]
> try refilling your `config.js` and `botconfig.js` files.

I don’t have a config.js file. From what I can see everything is on botconfig.js

**Comment by C-EO** [comment]
then try refilling the botconfig.js
