### ISSUE TITLE
i cant use play

### ISSUE THREAD

**Issue by Hak333** [SudhanPlayz/Discord-MusicBot#1103]
![image](https://user-images.githubusercontent.com/115870989/196020280-af8881e5-c467-4112-9b41-a6f81933b31d.png)
but i have node version 18

**Comment by GazorHuman** [comment]
V4?

**Comment by C-EO** [comment]
v4 uses node v12 to v14
it can't use any version of node higher than v14

**Comment by LewdHuTao** [comment]
downgrade your node.js version to v16.x
