### ISSUE TITLE
Error play spotify

### ISSUE THREAD

**Issue by khiempham06** [SudhanPlayz/Discord-MusicBot#1110]
![Screenshot from 2022-10-27 22-28-22](https://user-images.githubusercontent.com/68492139/198333171-b3bcf666-6700-40f3-bb28-7f31b0265ac1.png)
When I run spotify link I meet the error!

**Comment by DevAmiyo** [comment]
Same as #1118

**Comment by LewdHuTao** [comment]
switch to v5 as it use better-erela.js-spotify (better than v4 almost every link can be play) and v4 use erela.js-spotify (almost every link cannot be play)
