### ISSUE TITLE
skip bug?

### ISSUE THREAD

**Issue by Toodo** [SudhanPlayz/Discord-MusicBot#1113]
hello!
after i updated to #1105 i cannot use the skip button or /skip when i have auto queue i get a massage saying "There is nothing after  songname in the queue."

**Comment by kiyoshikuncool** [comment]
It's not a bug, my friend. You can undo the update or follow this update files #1023

**Comment by kiyoshikuncool** [comment]
It's not a bug, my friend. You can undo these #1105 update files:
+ commands/slash/skip.js
+ lib/DiscordMusicBot.js
+ util/Controller.js
And in events/voiceStateUpdate.js (#1105), you need to add `|| (player.trackRepeat || player.queueRepeat)` behind at line 102
That's all, my friend :3

**Comment by Toodo** [comment]
nice that worksed gazorhuman thanks :)
