### ISSUE TITLE
discord.js@13.8.0 is deprecated

### ISSUE THREAD

**Issue by XstreamSpeed** [SudhanPlayz/Discord-MusicBot#1114]
**Please describe the problem you are having in as much detail as possible:**
discord.js v13.8.0 has been deprecated, the latest version is 14.6.0, please update the bot 

### Essentials:

- Bot Version: 13.8.0
- Commit Hash: idk
- Node.js version: 17.9.0
- Operating system: linux-oracle

#### Additional system info
- Is it virtualized? (Docker or ...) : Yes VM
- What CPU is it running on (X86 or ARM or...): Neoverse-N1
- Additional details that might help us figure out the problem: nil

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by kiyoshikuncool** [comment]
You can update discord.js to 13.12.0 (lts-v13) :3

**Comment by LewdHuTao** [comment]
In (v6 maybe?) also erela.js not maintained anymore probably need to use another lavalink client

**Comment by DarrenOfficial** [comment]
There probably will be another massive rewrite.
