### ISSUE TITLE
Can't find song lyric 

### ISSUE THREAD

**Issue by PandaKeny** [SudhanPlayz/Discord-MusicBot#1119]
Can't find lyrics in Vietnamese
example:
- Hãy trao cho anh | Hay trao cho anh
( This is a song by SonTungMTP )

**Comment by XstreamSpeed** [comment]
Well, the bot would prefer English songs to be found rather that any other language, but try putting the actually vietnamese language text to search

**Comment by PandaKeny** [comment]
I tried to find many different Vietnamese lyric but couldn't

**Comment by GazorHuman** [comment]
Are you sure you are already using the latest lyrics command from [this commit](https://github.com/SudhanPlayz/Discord-MusicBot/commit/b7a52541118f3d301328255a4a33021b4093c1eat)? 
I searched for `Hãy trao cho anh` and I got the exact lyrics that you were looking for.

**Comment by PandaKeny** [comment]
> 

![image](https://user-images.githubusercontent.com/87780831/202864897-3d78263a-ccaf-4fe5-893e-ab43e208a404.png)
LINK

**Comment by GazorHuman** [comment]
> > 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/87780831/202864897-3d78263a-ccaf-4fe5-893e-ab43e208a404.png)
> 
> LINK
> 
> 


Just use the latest lyrcis command from V5 branch
