### ISSUE TITLE
Everything is running but music is not playing

### ISSUE THREAD

**Issue by Happylife016** [SudhanPlayz/Discord-MusicBot#1120]
**Please describe the problem you are having in as much detail as possible:**

### Essentials:

- Bot Version:
- Commit Hash:
- Node.js version:
- Operating system:

#### Additional system info
- Is it virtualized? (Docker or ...) :
- What CPU is it running on (X86 or ARM or...):
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by GazorHuman** [comment]
Please go to the discord support channel for this type of issue.
