### ISSUE TITLE
Auto Resume Issue

### ISSUE THREAD

**Issue by adityaghub** [SudhanPlayz/Discord-MusicBot#1122]
**Please describe the problem you are having in as much detail as possible:**
if bot is paused nd if i drag it to another vc it resume the track

### Essentials:

- Bot Version: v5
- Commit Hash: latest
- Node.js version: 17.x
- Operating system: 

#### Additional system info
- Is it virtualized? (Docker or ...) :
- What CPU is it running on (X86 or ARM or...):
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by GazorHuman** [comment]
Hey, I fixed this issue in my pull request #1105. You can fix this issue by changing a file called voiceStateUpdate.js, which is located in the events folder, change the whole code into this link https://codepaste.xyz/posts/WfwR40N2oC82xMuamqtT.

**Comment by adityaghub** [comment]
> Hey, I fixed this issue in my pull request #1105. You can fix this issue by changing a file called voiceStateUpdate.js, which is located in the events folder, change the whole code into this link https://codepaste.xyz/posts/WfwR40N2oC82xMuamqtT.

tysm its working fine for now

**Comment by GazorHuman** [comment]
> > Hey, I fixed this issue in my pull request #1105. You can fix this issue by changing a file called voiceStateUpdate.js, which is located in the events folder, change the whole code into this link https://codepaste.xyz/posts/WfwR40N2oC82xMuamqtT.
> 
> tysm its working fine for now

You may close this Issue now, my pull request has been merged with V5.

**Comment by adityaghub** [comment]
> > > Hey, I fixed this issue in my pull request #1105. You can fix this issue by changing a file called voiceStateUpdate.js, which is located in the events folder, change the whole code into this link https://codepaste.xyz/posts/WfwR40N2oC82xMuamqtT.
> > 
> > 
> > tysm its working fine for now
> 
> You may close this Issue now, my pull request has been merged with V5.

that dragging issue isnt fixed yet?

**Comment by GazorHuman** [comment]
> > > > Hey, I fixed this issue in my pull request #1105. You can fix this issue by changing a file called voiceStateUpdate.js, which is located in the events folder, change the whole code into this link https://codepaste.xyz/posts/WfwR40N2oC82xMuamqtT.
> 
> > > 
> 
> > > 
> 
> > > tysm its working fine for now
> 
> > 
> 
> > You may close this Issue now, my pull request has been merged with V5.
> 
> 
> 
> that dragging issue isnt fixed yet?

The issue has been fixed.
