### ISSUE TITLE
client.build is not a function

### ISSUE THREAD

**Issue by twist3dimages** [SudhanPlayz/Discord-MusicBot#1134]
**Please describe the problem you are having in as much detail as possible:**

### Essentials:

- Bot Version: latest
- Commit Hash: d7acf7c5f84237c63fd0f0b42a6279d507e05c6b1f4c61f9adf8606e14591131
- Node.js version: 17.9.1
- Operating system: Unraid
#### Additional system info
- Is it virtualized? (Docker or ...) : Docker
- What CPU is it running on (X86 or ARM or...): x64 (amd ryzen 3600)
- Additional details that might help us figure out the problem:
I have recreated the docker application, tried using my own lavalink server, tried using several hosted ones, turned on debugging, etc. it looks like it's not reading the config file. All I get is the client.build is not a function. I am 100% sure every field is filled out. Turning on debugging doesn't do anything either

 Settings https://imgur.com/XzX72Pt (config)
Volumes, etc https://imgur.com/NuXJWUG
### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by MiracleCherryPie** [comment]
Isn't lavalink.oops.wtf changed to *.freelavalink.ga?

**Comment by DarrenOfficial** [comment]
I see you're using unraid, downgrade the node version to 16.15.1

**Comment by DarrenOfficial** [comment]
Re-open this issue if it still happening, I am able to recreate this bug and downgrading to 16.15.1 solved the issue.
