### ISSUE TITLE
Spotify playing

### ISSUE THREAD

**Issue by SametKecici** [SudhanPlayz/Discord-MusicBot#114]
Hey dude you adding a spotify music playing

**Comment by kaaax0815** [comment]
There is such feature in the Groovy bot, which makes most sense. Its uses a Spotify playlist url, strips out the id, then uses the spotify api to get the songs in this playlist in json and then searches the titles on youtube, and if it cant find it, it skips the song and send a error message
+1

**Comment by SudhanPlayz** [comment]
Thanks for your suggestion, it has been added in TO-DO list of Discord Music Bot v4, which will be launched in a short period of time!
