### ISSUE TITLE
SyntaxError: Unexpected token '', ""... is not valid JSON 

### ISSUE THREAD

**Issue by MR-UNKNOWN2000** [SudhanPlayz/Discord-MusicBot#1142]
**Please describe the problem you are having in as much detail as possible:**

![image](https://user-images.githubusercontent.com/59323333/208810478-f778a150-ef44-419b-b216-5f97e76a27f7.png)
i have tried reinstalling npm

### Essentials:

- Bot Version:4.1.4
- Commit Hash:
- Node.js version:19.3.0
- Operating system: Windows Server 2022

#### Additional system info
- Is it virtualized? (Docker or ...) : NO
- What CPU is it running on (X86 or ARM or...): Intel X86
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by ItzMiracleOwO** [comment]
Seems its a library issue, see https://github.com/helperdiscord/petitio/issues/41
For a quick solution, try downgrading to Node.js v16.16.0

**Comment by MR-UNKNOWN2000** [comment]
Thanks downgrading to Node.js v16.16.0 worked
