### ISSUE TITLE
Track had an error: undefined.

### ISSUE THREAD

**Issue by DumbBoy10** [SudhanPlayz/Discord-MusicBot#1149]
**Please describe the problem you are having in as much detail as possible:**

Playback error!
Failed to load track: Bang Bang Bang Bang
Oops! something went wrong but it's not your fault!

[4:0:2023 - 23:24] | Player: 954394438648602674 | Track had an error: undefined.

Thats all info i have

- Bot Version: @5.0.0-beta
- Node.js version: npm@8.19.2
- Operating system: Windows 10

#### Additional system info
- What CPU is it running on (X86 or ARM or...): i5-10400F

**Comment by Assassin654** [comment]
That's not an issue

**Comment by DumbBoy10** [comment]
Oh sorry then is there something I can do to make it funcional agin?

**Comment by Assassin654** [comment]
It's a lavalink issue. So you need to change your lavalink
