### ISSUE TITLE
[ Suggestion ]

### ISSUE THREAD

**Issue by johntaxmi** [SudhanPlayz/Discord-MusicBot#115]
Be able to set the volume before the bot starts playing music
coz for some reason every time a song stops playing and I have set the volume down to 40 when the song ends, and I add a new song the volume resets back to 100.

That only happens when you start a new song, not already in the queue.

**Comment by SudhanPlayz** [comment]
Thanks for your suggestion, it has been added in TO-DO list of Discord Music Bot v4, which will be launched in a short period of time!
