### ISSUE TITLE
npm run deploy command

### ISSUE THREAD

**Issue by pierluigizagaria** [SudhanPlayz/Discord-MusicBot#1155]
- Bot Version: v5
- Commit Hash: 3d155101e99ed42a08d371f4fd9c74f0e4863ae6
- Node.js version: 16.16
- Operating system: Raspbian

I was trying to configure the bot by looking at the Dockerfile. Everything was fine, from the build to the startup, but the problem was that the commands were not registed to the bot. Then, after 30 minutes I figured out that the `npm run deploy` was running at **BUILD** time. I set all the tokens and secrets by using a .env file in the root of the project and defining `--env-file=.env` in the `docker run` command. The command registration was failing because you cannot sent env variables from file during the `docker build` command.

In order to make this project usable with docker I think is necessary to move the `npm run deploy` command at the **START** of the docker image. We cannot define 2 commands to run in the Dockerfile properly, so we can easily add a new command into the package.json like `deploy-start` that runs `npm run deploy && npm run start` and change the CMD into Dockerfile to `npm run deploy-start`

**Comment by pheeef** [comment]
Hey look at Pull Request #1141 , because I had the same Issue - I use pm2 to run the bot and so I set the ENV Variables in my ecosystems file but the Deploy didn't work, because there is a require('dotenv') missing in the config util, so it wouldn't load the env variables. 

I hope that helps.

**Comment by DarrenOfficial** [comment]
Could you try @pheeef fix, let me know if that solves the issue for you. If not, re-open this issue.
