### ISSUE TITLE
What is the purpose of this binaries in v5?

### ISSUE THREAD

**Issue by pierluigizagaria** [SudhanPlayz/Discord-MusicBot#1156]
Hi, I would like to understand what is the purpose of [this exe](https://github.com/SudhanPlayz/Discord-MusicBot/blob/v5/util/generate-musicbot-id.exe)? Shall I be concerned about the security of this project?

**Comment by Aryan1718** [comment]
The name of the file suggests that it may have something to do with generating an ID for a music bot

**Comment by pierluigizagaria** [comment]
Well, it's something that plain js could do easily, thats why seems shady that we need a compiled code to do that

**Comment by Aryan1718** [comment]
Yes, you are right. By using UUID in JavaScript, you can easily do that.

**Comment by timotiose** [comment]
Run it on linux easy fix

**Comment by sprucecellodev125** [comment]
> Run it on linux easy fix

Not really though. There's Linux binary version of generate-musicbot-id

**Comment by sprucecellodev125** [comment]
However we can just safely remove those files

**Comment by Neko-Life** [comment]
> I would like to understand what is the purpose of this exe?

It does what its name describe, creates an identifier for the bot. It was made so we can identify skids who violates this project's license. It's still a prototype and it's not of any use currently since no other maintainer cares about skids and most of the time we can just find them asking for support in our discord server, which we inherently deny.

> Shall I be concerned about the security of this project?

It does nothing malicious. You can prove it yourself.

**Comment by brandonsturgeon** [comment]
This is so silly. Plenty of open source projects can run without bizarre black-box code running on startup.

**Comment by sprucecellodev125** [comment]
> This is so silly. Plenty of open source projects can run without bizarre black-box code running on startup.

Ok I'll remove it

**Comment by sprucecellodev125** [comment]
Even though I didn't create it

**Comment by Neko-Life** [comment]
> This is so silly. Plenty of open source projects can run without bizarre black-box code running on startup.

You have no idea how many "developer" violating the very simple license, it basically says "Don't remove credits and keep your bot private" yet the amount of kid claiming credits and making their bot public is staggering. Some even dare to show their nose and ask for support on our discord server, now that's what you wanna call "silly".

You're calling it "bizarre black-box code", may I ask you to elaborate more on that? Is it bizarre that we want to prevent you from violating our license? Do you not have any respect for our work? It doesn't even do anything to your computer, it only creates an Id and that's it. Not even mentioning that it's just a prototype and I have lost spirit to chase after dumb skid anymore. If you're just one of that skid then fuck off, don't use our code.

**Comment by pierluigizagaria** [comment]
I got your point and understand your anger. This ID can be generated by clear JS instructions. Not everyone has the skill to reverse a binary and truly check what it does. I think is normal for everyone to doubt about a compiled binary. Binaries are black boxes that CAN be silly, clear JS instructions CAN'T because can easily be understood

**Comment by Neko-Life** [comment]
You're right @daichuanwu21, I have cleaned my binaries. I don't care much whether we need to change the license or not as I am no longer active in this project. Probably @SudhanPlayz or @DarrenOfficial as code owners might wanna consider that.

**Comment by Assassin654** [comment]
> I got your point and understand your anger. This ID can be generated by clear JS instructions. Not everyone has the skill to reverse a binary and truly check what it does. I think is normal for everyone to doubt about a compiled binary. Binaries are black boxes that CAN be silly, clear JS instructions CAN'T because can easily be understood. With this issue my point is not to remove your defensive mechanism over skids, but to make it clear to everyone!

I agree about the black box code. It's something that can be easily read and done in plain JS, but I believe that's the point of it. So it's not editable and easily removed. On a open project like this it should at least be more clear about what it does.

**Comment by sprucecellodev125** [comment]
Well, we're no longer cares about skids. However if I have a time I'll clone a previous commit to my remote dev machine, zipping this code and upload it to triage and run the program with invalidated token to see any network request that this script done (to see what the previously deleted black box does)

**Comment by sprucecellodev125** [comment]
@pierluigizagaria so I tried 2 of those binaries in triage, it really does nothing
https://tria.ge/230219-nn5j8seh4z/behavioral1 (macOS Catalina 10.15)
https://tria.ge/230219-nshk9sfd82/behavioral1 (Debian Linux 9 armhf)

**Comment by brandonsturgeon** [comment]
> @pierluigizagaria so I tried 2 of those binaries in triage, it really does nothing https://tria.ge/230219-nn5j8seh4z/behavioral1 (macOS Catalina 10.15) https://tria.ge/230219-nshk9sfd82/behavioral1 (Debian Linux 9 armhf)

Maybe I don't understand this website, but judging by the Replay Monitor, did it ever even run the binary?

**Comment by sprucecellodev125** [comment]
Triage should be run the binary automatically. You can see the running process

**Comment by DarrenOfficial** [comment]
What have I missed? God, this is a mess. Please do not commit any binaries file.

I am so sorry to everyone that has this arbitrary “binary” on their computer.

Thank-you again @pierluigizagaria for bringing this issue to my attention.

> @Neko-Life 
> It does nothing malicious. You can prove it yourself.

Again, do not commit this. As this binary is unrelated to the project, itself. I understand that some people can't understand what FOSS is.


> @daichuanwu21 
> I would suggest removing the black-box binary and switching to the [AGPL license](https://www.gnu.org/licenses/agpl-3.0.en.html).

I will consider that for the future, will discuss with @SudhanPlayz.


Will close this issue as this problem is resolved. If there's any security concerns/important information, please bring them to me directly. My email is me@darrennathanael.com & my discord is [DarrenOfficial#3451](https://discord.gg/JqPbxCcDRb)
