### ISSUE TITLE
Issues logging in to dashboard

### ISSUE THREAD

**Issue by timotiose** [SudhanPlayz/Discord-MusicBot#1169]
**Please describe the problem you are having in as much detail as possible:**

When logging in to the dashboard after i log in with discord it shows me this 
![image](https://user-images.githubusercontent.com/57829932/216797111-ad0320d5-e404-4da2-8fe2-515ea308ba30.png)

### Essentials:

- Bot Version: 5.0.0-beta
- Commit Hash: ffaf4b8
- Node.js version: v18.2.0
- Operating system: Linux

#### Additional system info
- Is it virtualized? (Docker or ...) :
- What CPU is it running on (X86 or ARM or...):
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by DarrenOfficial** [comment]
Please provide step-by-step process, so we can replicate the issue, otherwise we can't help you/
