### ISSUE TITLE
Command /queue crashing the bot

### ISSUE THREAD

**Issue by Falow1** [SudhanPlayz/Discord-MusicBot#1172]
The bot crashes when the queue has many songs, I put a playlist of mine with 110 songs (exaggerated) and when I use the /queue it dies
![Screenshot_7](https://user-images.githubusercontent.com/92454215/218189273-e41047dd-76e5-4cd7-b1a3-904254c3aadb.png)

**Comment by LewdHuTao** [comment]
Migrate to v5 as bugs in v4 will not be fix anymore due to djs 12 is outdated
