### ISSUE TITLE
An unexpected error has occurred. Possible type Error: Status code: 429

### ISSUE THREAD

**Issue by pratyushsnake** [SudhanPlayz/Discord-MusicBot#119]
I am hosting my bot on BlueFoxHosting this error pops up when i try to use the play command. if this is a hosting side issue please tell me more about this issue so i can take it to the hosting's support.

**Comment by GhostyScripts** [comment]
I'm having the same issue and I'm hosting mine on Repl.it

**Comment by pratyushsnake** [comment]
devs please look into this

**Comment by SudhanPlayz** [comment]
Sorry it will be fixed as soon as possible, it has been added in TO-DO list of Discord Music Bot v4, which will be launched in a short period of time!
