### ISSUE TITLE
Does v5 support Apple Music?

### ISSUE THREAD

**Issue by CalendulaED** [SudhanPlayz/Discord-MusicBot#1194]
From the help section, it said support Apple Music, but when I passed in the apple music playlist, it showed searching but never end. Are there a specific format I need to follow in order to play apple music?

- Bot Version:5.0.0
- Commit Hash:
- Node.js version:18.14.2
- Operating system: 

#### Additional system info
- Is it virtualized? (Docker or ...) : No
- What CPU is it running on (X86 or ARM or...): X86

**Comment by CalendulaED** [comment]
This is the sample I tried: "https://music.apple.com/us/playlist/pl.u-WabZv4jUeqYke77"

**Comment by Assassin654** [comment]
Yes

**Comment by CalendulaED** [comment]
> Yes

I try to use the apple music shared link, but it doesn't work. Does it works for you?

**Comment by LewdHuTao** [comment]
tested multiple apple music playlist links(including your playlist) and can confirm they didn't work. maybe you can create a spotify playlist instead?

**Comment by CalendulaED** [comment]
> tested multiple apple music playlist links(including your playlist) and can confirm they didn't work. maybe you can create a spotify playlist instead?

But I did saw the apple music match code for apple music, I thought it was been supported

**Comment by LewdHuTao** [comment]
you can play use apple music if its a single track also certain playlist link. we can't do anything as we're not using our own plugins

**Comment by Assassin654** [comment]
Apple links have worked for me before, it may be a very specific link, like directly to the song. The lava link also has to support the link.

**Comment by DarrenOfficial** [comment]
Natively, maybe. The code is unmaintained. Erela.js is unmaintained. Not guaranteed it will work every time.
