### ISSUE TITLE
Autoplay related music 

### ISSUE THREAD

**Issue by oye-zzzzuuuu** [SudhanPlayz/Discord-MusicBot#1195]
Add autoplay music related feature with toggle button ✅

**Comment by oye-zzzzuuuu** [comment]
In v5 bot

**Comment by oye-zzzzuuuu** [comment]
Also YouTube music playlist not supported

**Comment by LewdHuTao** [comment]
> Also YouTube music playlist not supported 

change your lavalink

**Comment by oye-zzzzuuuu** [comment]
> > Also YouTube music playlist not supported
> 
> change your lavalink

Nah i am talking about YouTube music not YouTube

**Comment by LewdHuTao** [comment]
give the playlist link you want to try i want to test in my bot

**Comment by oye-zzzzuuuu** [comment]
> > Also YouTube music playlist not supported
> 
> change your lavalink

Lavalink working without any issue:/

**Comment by LewdHuTao** [comment]
> Nah i am talking about YouTube music not YouTube 

we don't remember we add youtube music support? we only have spotify, apple music, deezer, youtube (not youtube music) and lavalink plugins in application.yml 

anyway you can send the playlist link i will test in my bot

**Comment by oye-zzzzuuuu** [comment]
Here you go

> > Nah i am talking about YouTube music not YouTube
> 
> we don't remember we add youtube music support? we only have spotify, apple music, deezer, youtube (not youtube music) and lavalink plugins in application.yml
> 
> anyway you can send the playlist link i will test in my bot

Here you go

**Comment by LewdHuTao** [comment]
![image](https://user-images.githubusercontent.com/90232327/224970240-df5ce778-7f33-4cce-95fd-258823299067.jpeg)

what error you get anyway? also there is any error in lavalink console?

**Comment by oye-zzzzuuuu** [comment]
> ![image](https://user-images.githubusercontent.com/90232327/224970240-df5ce778-7f33-4cce-95fd-258823299067.jpeg)
> 
> what error you get anyway? also there is any error in lavalink console?

Bot is thinking, no error in console

**Comment by oye-zzzzuuuu** [comment]
> you host own lavalink or use public lavalink?

Local host Lavalink win.

**Comment by LewdHuTao** [comment]
custom jar or original jar?

if custom jar try switch to original lavalink.jar version 3.7.5 also use latest application.yml file and see if there is any changes

also update your bot to latest v5 commits to get autoplay feature

**Comment by DarrenOfficial** [comment]
Autoplay is only available on v5, It is called autoqueue.
![Autoqueue](https://user-images.githubusercontent.com/55406094/226881705-475a4569-615e-49a2-9b41-75d6e022867c.png)


YouTube Music is the same as YouTube Source, and it is supported.


![YT](https://user-images.githubusercontent.com/55406094/226881437-54b89c27-b810-4359-80d5-8458c7a56f8a.png)

Feel free to test this out yourself
```
host : narco.buses.rocks
port : 2269
password : "glasshost1984"
```
