### ISSUE TITLE
skip command doesnt put songs i skipped back in the queue, even when i have loopqueue enabled

### ISSUE THREAD

**Issue by Yootz** [SudhanPlayz/Discord-MusicBot#1201]
**Please describe the problem you are having in as much detail as possible:**

Problem: i want to listen to my song 24/7, and sometimes i wanna skip some songs in the queue, but i still want to listen to it later on, but this makes it so that I have to put the song back in because it's throwed out of the queue if i use the skip command, it doesnt throw it out of the queue if i dont skip it.

Steps to reproduce: 

1. Play a song 
2. Put another song in the queue
3. enable >loopqueue
4. use >skip command
5. skipped song is not in the queue.

### Essentials:

- Bot Version: v4.1.2
- Commit Hash:
- Node.js version: v19.8.1
- Operating system: Linux

#### Additional system info
- Is it virtualized? (Docker or ...) : no
- What CPU is it running on (X86 or ARM or...): x86
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by LewdHuTao** [comment]
thats not how skip command work in music bot lol

**Comment by Yootz** [comment]
then how do you pick the next song while not removing it from the queue without some sort of roundabout way?

**Comment by Yootz** [comment]
nah forget it, ill just use >seek 1000m and its gucci

**Comment by LewdHuTao** [comment]
you can use previous command actually but its only available in v5

**Comment by Yootz** [comment]
Damn, i realized this is not being updated, guess I'll switch to v5

**Comment by LewdHuTao** [comment]
good decision then
