### ISSUE TITLE
Search suggestions error

### ISSUE THREAD

**Issue by heyjumanji** [SudhanPlayz/Discord-MusicBot#1205]
As you can see after the v5 update the bot stop working the play command as its not working with the song suggestions anyone can please tell me whats the way to fix it anyway and explain why its happening and im looking into the codes but dont understand how to fix it.
![IMG_20230408_141247_310](https://user-images.githubusercontent.com/90971841/230712495-f1017599-fe84-4fb1-aa57-8ef30d2e4e67.jpg)

**Comment by LewdHuTao** [comment]
![image](https://user-images.githubusercontent.com/90232327/231925833-9895e83e-f491-4ae2-8dc3-c21c53e5b8c6.png)

works fine for me

**Comment by LewdHuTao** [comment]
close this as duplicate of #1202 , as there are more than one people who get same issue like you ill be looking if the recent update have to do anything with play command autocomplete
