### ISSUE TITLE
[AutoComplete] /Play command still doesn't autocomplete

### ISSUE THREAD

**Issue by ItJustFox** [SudhanPlayz/Discord-MusicBot#1207]
**Please describe the problem you are having in as much detail as possible:**
![image](https://user-images.githubusercontent.com/42358087/232043471-225ec533-c06b-492d-ad43-51a45a669197.png)

### Essentials:

- Bot Version: V5
- Commit Hash: 5f2efac
- Node.js version: node: 'v16.20.0', npm: '9.6.4'
- Operating system: unRAID'os | Behind Pterodactyl server

#### Additional system info
- Is it virtualized? (Docker or ...) : Pterodactyl server -> Docker
- What CPU is it running on (X86 or ARM or...): X86
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: all needed 
- other: none

**Comment by LewdHuTao** [comment]
refer to #1202

**Comment by LewdHuTao** [comment]
i just realized you already have the same issue before and im pretty sure you have do a clean install but still get same error

**Comment by LewdHuTao** [comment]
so try edit the autocomplete code by doing `try and catch` and see if there is any error in console. oh make sure debug is set to true in config

**Comment by Assassin654** [comment]
Try changing the request limit to 5 instead of 25 and see if that works. It could be that it takes too long to search.

**Comment by ItJustFox** [comment]
> Try changing the request limit to 5 instead of 25 and see if that works. It could be that it takes too long to search.

Actually I managed to fix it has told on discord, reinstalling wasn't doing that much, I had to re send the slash command to discord with `npm run deploy` to debug it, with updating youtube-sr and manually all nodejs addon but re run deploy fixed it first time

**Comment by LewdHuTao** [comment]
great to hear this issue is fixed
