### ISSUE TITLE
Discord.js v14 support (v5 related)

### ISSUE THREAD

**Issue by ddodogames** [SudhanPlayz/Discord-MusicBot#1208]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the ideal solution**
Is it possible to add support for Discord.js v14? The reason I'm asking for this is that, naturally every year discord deprecates an API Version over the newer one, and so it is possible that discord could deprecate discord api v9 (which what v5 uses considering that it's on discord.js v13). Are there any plans on this or Something? I'm not sure if discord.js will discontinue v13 sometime later since they recommend users to update to v14 for some Reason.

Note: I personally Apologize if this wasn't the right place to ask for this.

**Comment by C-EO** [comment]
@SudhanPlayz and @DarrenOfficial I believe he has a valid point

**Comment by LewdHuTao** [comment]
v14 will break the bot, ofc you can still update the bot to v14 as long you know what you’re doing and don’t worry djs will not discontinue v13 yet and the API wont be deprecated soon

**Comment by ddodogames** [comment]
> v14 will break the bot, ofc you can still update the bot to v14 as long you know what you’re doing and don’t worry djs will not discontinue v13 yet and the API wont be deprecated soon


Hmm Yeah, that makes sense. I was just worried as if all the work done on v5 would be wasted eventually. Thanks for the information.
