### ISSUE TITLE
Spotify URLs not handled correctly

### ISSUE THREAD

**Issue by rartigues** [SudhanPlayz/Discord-MusicBot#1215]
**Please describe the problem you are having in as much detail as possible:**

Sorry for maybe not understanding the code correctly. 

After installing the LavaScr plugin to Lavalink (enabling listening from Spotify) all the Lavalink node recieves from the music bot is ytsearch requests. By looking at the code where the play interaction is processed, I found that even when a Spotify link is provided it is searched for in Youtube.
> See [interactionCreate.js](https://github.com/SudhanPlayz/Discord-MusicBot/blob/5f2efacba85cae8c4233b4d6af52763f78be22c5/events/interactionCreate.js#L44-L77)

TLDR: Even when providing valid Spotify links, all that Lavalink recieves is a `ytsearch:` request 
![image](https://user-images.githubusercontent.com/87259530/234757814-1a6795ae-a34b-48e0-a38b-9335a52ed735.png)

### Essentials:

- Bot Version: v5.0.0.0-beta
- Commit Hash: 5f2efac
- Node.js version: 16.16.0
- Operating system: Manjaro Linux

#### Additional system info
- Is it virtualized? (Docker or ...) : Running with PM2
- What CPU is it running on (X86 or ARM or...): x86_64
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by rartigues** [comment]
I'm aware of issue #1200, this is not a duplicate due to the fault being blamed on Lavalink needing to handle the spotify requests, but the problem I'm having is that Lavalink doesn't recieve a Spotify request

**Comment by LewdHuTao** [comment]
did you disable spotify plugins in erela manager?

**Comment by LewdHuTao** [comment]
i bet you did not disable it yet and to save your time all you need to do is go to DiscordMusicBot.js file in lib folder and find this code:

```
this.manager = new Manager({
      plugins: [
        new deezer(),
        new AppleMusic(),
        new spotify(),
        new facebook(),
        new filters(),
      ],
```

you need to remove `new spotify()` to disable spotify plugins and let lavaSrc handle spotify plugins.

Note: if you also use apple and deezer plugins in lavaSrc you also need to disable deezer and apple plugins in erela manager

**Comment by rartigues** [comment]
Thank you so much! It works perfectly now. I got mixed up from [this response](https://github.com/SudhanPlayz/Discord-MusicBot/issues/1200#issuecomment-1511923492), maybe that's the supposed behaviour in v5?

**Comment by LewdHuTao** [comment]
> Thank you so much! It works perfectly now. I got mixed up from [this response](https://github.com/SudhanPlayz/Discord-MusicBot/issues/1200#issuecomment-1511923492), maybe that's the supposed behaviour in v5?

he must get it wrong, spotify plugins don’t need any configuration in v5 unless you were using custom lavalink plugins like lavaSrc

anyway i guess this issue has been solved so imma close it, feel free to reopen if you have any issue regarding lavaSrc

**Comment by LewdHuTao** [comment]
> > Thank you so much! It works perfectly now. I got mixed up from [this response](https://github.com/SudhanPlayz/Discord-MusicBot/issues/1200#issuecomment-1511923492), maybe that's the supposed behaviour in v5?
> 
> spotify plugins don’t need any configuration in v5 as we moved to other wrapper that doesn’t require the client id anymore, unless you were using custom lavalink plugins like lavaSrc
> 
> anyway i guess this issue has been solved so imma close it, feel free to reopen if you have any issue regarding lavaSrc
