### ISSUE TITLE
 Track had an error: undefined.

### ISSUE THREAD

**Issue by icymyers** [SudhanPlayz/Discord-MusicBot#1219]
**no songs will play, it just says failed to load track and spits it out over and over**

![image](https://user-images.githubusercontent.com/16390816/235792852-842385c9-e733-4349-9647-a70578def71b.png)

### Essentials:

- Bot Version: v5 updated 5/2/23
- Commit Hash:
- Node.js version: 18.15
- Operating system: windows server 2019 and windows 10 tried both

#### Additional system info
- Is it virtualized? (Docker or ...) :
- What CPU is it running on (X86 or ARM or...):
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by Assassin654** [comment]
Fix/use a different lavalink. Not a bot issue.

**Comment by sprucecellodev125** [comment]
^
Without an error log, we still can't figure out your problem
