### ISSUE TITLE
I Want TO Know One Thing.

### ISSUE THREAD

**Issue by drasmodeus666** [SudhanPlayz/Discord-MusicBot#1220]
Can't I Remove This?  I need to remove this line, i'll give credit on the other text. how can  i remove this?
<img width="331" alt="Screenshot 2023-05-04 014251" src="https://user-images.githubusercontent.com/82769834/236028966-d9531672-140d-4e6f-bc51-2ab8dae13254.png">

**Comment by C-EO** [comment]
@Pronoy2007 email me using this email. dennis.sebalemba@gmail.com

**Comment by C-EO** [comment]
I'll show you how

**Comment by sprucecellodev125** [comment]
@C-EO Please don't tell random person to mail them.
@Pronoy2007 as you wanted to change the credit and put it somewhere else, please confirm where you'll put original developer credit on
