### ISSUE TITLE
User cannot move bot between channels or disconnect bot using discord actions

### ISSUE THREAD

**Issue by Jacob439** [SudhanPlayz/Discord-MusicBot#1226]
**Please describe the problem you are having in as much detail as possible:**

- If you move the bot to a different channel and join that other channel, the bot still thinks it is in the original channel.
- If you disconnect the bot by right-clicking in discord, the bot still thinks it is connected and playing in the original channel (image below)
![image](https://github.com/SudhanPlayz/Discord-MusicBot/assets/63742413/9bb1ad41-ac5e-4f5a-8069-c610aea5c90a)

### Essentials:

- Bot Version: v4.1.4
- Commit Hash: 63efbd4
- Node.js version: 16.11.1
- Operating system: Fedora 34 (Server Edition)

#### Additional system info
- Is it virtualized? (Docker or ...) : 
- What CPU is it running on (X86 or ARM or...): 
- Additional details that might help us figure out the problem: 

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by Jacob439** [comment]
This looks relevant: https://discordjs.guide/voice/voice-connections.html#handling-disconnects
I'll create a PR once I get something working

**Comment by Assassin654** [comment]
Switch to v5

**Comment by Jacob439** [comment]
Ahhh, I was unaware of the existence of v5. Thank you!
