### ISSUE TITLE
Requested by undefined 

### ISSUE THREAD

**Issue by oye-zzzzuuuu** [SudhanPlayz/Discord-MusicBot#1232]
when autoQueue: true , in config and you skip song 
snap shot  https://cdn.discordapp.com/attachments/1000106840446734418/1112699813138550895/image.png

**Comment by brianferri** [comment]
it ain't wrong...
This should be fixed in v5.1 natively. Alternatively someone could push a fix on v5.0 with something like
```js
{
  name: "Requested by",
  value: `${track.requester || client.manager.autoPlay ? "Autoplay" : "noone"}`,
  inline: true,
},
```

**Comment by LewdHuTao** [comment]
not sure why it show undefined instead it should show bot name when autoqueue is enabled.

![Screenshot_20230531_211805.jpg](https://github.com/SudhanPlayz/Discord-MusicBot/assets/90232327/a1ebce6b-c253-4324-8b2a-3a2b03acf3de)

**Comment by oye-zzzzuuuu** [comment]
> not sure why it show undefined instead it should show bot name when autoqueue is enabled.
> 
> ![Screenshot_20230531_211805.jpg](https://user-images.githubusercontent.com/90232327/242289637-a1ebce6b-c253-4324-8b2a-3a2b03acf3de.jpg)

It shows undefined when autoqueue is true in config, but if you enable autoqueue with command it show bot name

**Comment by LewdHuTao** [comment]
> It shows undefined when autoqueue is true in config, but if you enable autoqueue with command it show bot name

you aint wrong tho. I'll try push a fix when im free

**Comment by LewdHuTao** [comment]
fixed.
