### ISSUE TITLE
Crash bot when use Spotify link 

### ISSUE THREAD

**Issue by mrrSwift** [SudhanPlayz/Discord-MusicBot#1235]
- Bot Version: 4.1.4
- Node.js version: 18.15
- Operating system: Windows 10 64bit

I'm use self vps for run bot 

vps is located in Iran and when I try to play a song with a Spotify link, the program crashes
When I first checked it, I found that it crashes when the program can't communicate with Spotify. If you can do something so that it only shows the error and the program doesn't crash.

**Comment by Assassin654** [comment]
Use v5
