### ISSUE TITLE
Prefix not working

### ISSUE THREAD

**Issue by Naiml007** [SudhanPlayz/Discord-MusicBot#1237]
![Screenshot_2023-06-11-15-12-33-278_com discord](https://github.com/SudhanPlayz/Discord-MusicBot/assets/90306726/e332573d-ea23-405a-81e3-f3d290712e13)

**Comment by brianferri** [comment]
If you are using v4 please consider switching to v5 instead. Prefix commands have long since been marked deprecated and don't have any official discord support anymore

**Comment by DarkDaVinci** [comment]
Hello,
So I have similar issue with perfix. In config I set it on "-" and it doesnt work... I tried on v5, same issue. I tried to change it but I get "The application did not respond" error on discord. I tried then to leave it on deafult but even ">" didn't work.

**Comment by brianferri** [comment]
> Hello,
> So I have similar issue with perfix. In config I set it on "-" and it doesnt work... I tried on v5, same issue. I tried to change it but I get "The application did not respond" error on discord. I tried then to leave it on deafult but even ">" didn't work.

@DarkDaVinci 
V5 doesn't have prefix commands

**Comment by iseeface** [comment]
> Hello, So I have similar issue with perfix. In config I set it on "-" and it doesnt work... I tried on v5, same issue. I tried to change it but I get "The application did not respond" error on discord. I tried then to leave it on deafult but even ">" didn't work.

V5 only have slash command
