### ISSUE TITLE
Resuming a song makes the bot freeze.

### ISSUE THREAD

**Issue by joeyk710** [SudhanPlayz/Discord-MusicBot#125]
**Describe the bug**
> When pausing a song, after you try to resume the song, the bot says the music is resumed, but nothing happens. I have to pause the song then resume again to then have the song skip and glitch.

**To Reproduce**

> Please go to the `resume.js` file and change something in that file to fix the resume command.

**Expected behavior**

> I expected the song to be resumed. Instead the bot just froze.

**Screenshots**

**Desktop (please complete the following information):**

>-OS : Windows 10
-Browser : Chrome
-Version : 3.0.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Colonel-Ltd** [comment]
> Could you give me something to try to fix this instead of just telling me it works for you?

Tell me what errors appear in the log

**Comment by joeyk710** [comment]
Nothing goes wrong in the console so I'm not sure. Also now searching a song the bot joins then leaves right before a song is played.
