### ISSUE TITLE
Add prefix to commands

### ISSUE THREAD

**Issue by Jim-m-y** [SudhanPlayz/Discord-MusicBot#1255]
Add prefix to commands or only essential commands in V5

```
/play [Name_song]
>play [Name_song]
or directly
>[Name_song]
```

**Comment by sprucecellodev125** [comment]
this is useless, jk prefix commands is deprecated right? then why would you need it? slash commands menu is too slow?

**Comment by Jim-m-y** [comment]
using the slash command bar is very time consuming and complicated to use if you have many bots on a discord server and also for users not very familiar with discord, it is better to use a prefix, you just put the prefix and the name of the music search and that's it, so it wouldn't be more if you planned to re-integrate prefixes for some commands, of course this is just a suggestion
