### ISSUE TITLE
Crossfade and/or Gapless Playback.

### ISSUE THREAD

**Issue by theLucasAntunes** [SudhanPlayz/Discord-MusicBot#1257]
**Is your feature request related to a problem? Please describe.**
No. I just found it would be nice.

**Describe the ideal solution**
Perhaps a command to turn it on/off, and identify when an Album is played, prompting if that is desired. Useful for albums where there are intros to next songs, etc.

**Describe alternatives you've considered**
Pretty straightforward, I guess.

**Additional context**
Not sure if this is easy or even possible to be made, but I think it would be an AWESOME feature. If it's possible, I'd love to contribute whenever I have some time.

**Comment by Neko-Life** [comment]
this isn't possible with lavalink

**Comment by C-EO** [comment]
@Neko-Life isn't it possible to manipulate the lavalink API to our liking just for the bot?
Either that or just create a crossfade/gapless playback plugin for lavalink
