### ISSUE TITLE
Queue reactions

### ISSUE THREAD

**Issue by joeyk710** [SudhanPlayz/Discord-MusicBot#126]
Hi. Is there a way in the code to make it so it reacts to the message only when there are 10 songs or more in the queue? It doesn't really make sense to have it react to go to different pages if there is less than 10 songs. I forked the project and I'm wondering if there's something I can change to make that happen. 

I was also wondering what the proper line would be to add the queue position when users add songs. This is a lot so any suggestions or help would be really great! Thanks!

**Comment by SudhanPlayz** [comment]
Thanks for your suggestion, it has been added in TO-DO list of Discord Music Bot v4, which will be launched in a short period of time!
