### ISSUE TITLE
Bot quits after music starts

### ISSUE THREAD

**Issue by nanoeray** [SudhanPlayz/Discord-MusicBot#1261]
I successsfully installed lavalink and bot. Applied all config parameters. but when i try to listen a music bot enters room and quits immediately. 

When check the bot it says: 9:8:2023 - 16:42 | Info: Lavalink: Node Main connected
9:8:2023 - 16:42 | Info: Lavalink: Node Main had an error: Unexpected op "ready" with data: [object Object]****

Lavalink works without problem. All tokens are correct.

**Comment by LewdHuTao** [comment]
lavalink issue. are you using your own lavalink or public lavalink?

**Comment by nanoeray** [comment]
Hi,
Im using my own lavalink, latest version. Music plays right now but when i stop it or skip bot got a .map error on /node_modules/erela.js/dist/structures/Manager.js:161 i think this is a lavalink problem too. but i cant get it why lavalink works with problems? im using latest version not edited version.

**Comment by t15575975** [comment]
Hello! 
I have the same problem.
try the new version of [Lavalink](https://github.com/lavalink-devs/Lavalink/releases/download/3.7.8/Lavalink.jar)
It solved my problem!

**Comment by pheeef** [comment]
@nanoeray Which *numeric* version of Lavalink are you using?

**Comment by subhiahsan** [comment]
Same here, restarting bot and lavalink even the vps doesnt work
Lavalink stable 3.7.8
