### ISSUE TITLE
there is no music coming out of the bot and all the lavalink server dont connect unless it your own

### ISSUE THREAD

**Issue by discnono** [SudhanPlayz/Discord-MusicBot#1262]
**Please describe the problem you are having in as much detail as possible:**

### Essentials:

- Bot Version:
- Commit Hash:
- Node.js version:
- Operating system:

#### Additional system info
- Is it virtualized? (Docker or ...) :
- What CPU is it running on (X86 or ARM or...):
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by sourabhbeni** [comment]
same it work for me for 2-3 days but now not working even with my own lavalink
