### ISSUE TITLE
#BugInProgramming

### ISSUE THREAD

**Issue by Siddhartha41210** [SudhanPlayz/Discord-MusicBot#1263]
When I play a music it runs but for 3 - 4 secs only and stucks.

**Comment by C-EO** [comment]
I recommend using the new version. Find it [here](github.com/wtfnotavailable/Discord-MusicBot).

**Comment by Siddhartha41210** [comment]
But I cannot find the new version it a blog news

**Comment by Siddhartha41210** [comment]
But I cannot find the new version it a blog news

**Comment by Siddhartha41210** [comment]
> I recommend using the new version. Find it [here](github.com/wtfnotavailable/Discord-MusicBot).

I cannot find the new version

**Comment by C-EO** [comment]
Sorry. [HERE](https://github.com/wtfnotavailable/Discord-MusicBot)
