### ISSUE TITLE
you can't play the music

### ISSUE THREAD

**Issue by Rafci** [SudhanPlayz/Discord-MusicBot#1272]
## Please describe the problem you are having in as much detail as possible:
when I type /play to play music, it keeps searching and on VPS there is an error fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem |
boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

## Include a reproducible code sample here, if possible:

```js
// Place your code here
```
fatal: not a git repository (or any parent up to mount point /home) Stopping at filesystem 
boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
........................................................

**Comment by pheeef** [comment]
Hey @Rafci

I'm wiling to help you here, but you need to provide a bit more information about your set-up. 

* General information (that is provided in the template you initially were supposed to fill out) like software version of the entire stack, operating system etc.. 
* From what specific log file / process is that log entry "fatal" you've posted? Lavalink, Node or something else?

Just throwing a log entry into a Github Issue is generally not very beneficial to getting your problem solved.

**Comment by Rafci** [comment]
Where should the entire stack software, system, etc. be placed?

**Comment by Rafci** [comment]
because I transferred it to pterodactyl
