### ISSUE TITLE
Lavalink v4 Support

### ISSUE THREAD

**Issue by rhonivanpareja** [SudhanPlayz/Discord-MusicBot#1274]
## Please describe the problem you are having in as much detail as possible:
It seems that the lavalink v4 breaks the v5 version of the bot. It would be great to support the latest version as well

**Comment by rinzler100** [comment]
Also experiencing this. Glad it's not just me.

**Comment by JasonWu55** [comment]
same here

**Comment by pheeef** [comment]
I'd recommend you go open a FR in the other Repo, this one is not actively being developed anymore. See https://github.com/wtfnotavailable/Discord-MusicBot

**Comment by fragtion** [comment]
Same issue here. Looks like the lavalink client library being used ("erela.js") halted development. So the bot needs a new lavalink client library.

Any other discord music bots you guys can recommend?

**Comment by ItJustFox** [comment]
The bot should add a support for LavalinkV4 it would fix everything.

**Comment by LewdHuTao** [comment]
Soon™
