### ISSUE TITLE
lavalink version in docker-compose.yml doesn't support current youtube api

### ISSUE THREAD

**Issue by chit-uob** [SudhanPlayz/Discord-MusicBot#1292]
## Please describe the problem you are having in as much detail as possible:
I've used the docker setup for the discord bot, and was unable to play YouTube videos, saying API was outdated, this was fixed by changing the fredboat lavalink image version from 439f122 to v3-update-lp

## Include a reproducible code sample here, if possible:

```js
// Place your code here
```

## Further details:

I am using the docker-compose.yml suggested
- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

## Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by chit-uob** [comment]
a pull request has been created to fix this issue

**Comment by LewdHuTao** [comment]
merged 👍
