### ISSUE TITLE
everything works fine but when /play + https://www.youtube.com/watch?v=HX9IJJkQ1b0 the bot keeps Searching... no response

### ISSUE THREAD

**Issue by vovanhau123** [SudhanPlayz/Discord-MusicBot#1294]
![Ảnh chụp màn hình 2024-04-21 163854](https://github.com/SudhanPlayz/Discord-MusicBot/assets/102389652/2a47c253-52e0-4c86-b002-694c53a036d5)

**Comment by LewdHuTao** [comment]
fix your lavalink, if you use public lavalink switch until they work or if you host a lavalink update your lavalink jar https://repo.lavalink.dev/artifacts/lavalink/8d40740b/Lavalink.jar
