### ISSUE TITLE
Stolen

### ISSUE THREAD

**Issue by lAzrythl** [SudhanPlayz/Discord-MusicBot#13]
CorbinDioxide#2965 has downloaded the code, claimed the bot is his and used it in his discord server, he has edited the code so there are credits to him in some of the footers. To confirm you are him please dm me on discord the following:
NIV5NE46UBU532VN83y48NWN87

**Comment by lAzrythl** [comment]
Almost forgot, Lapiduck#8308

**Comment by lAzrythl** [comment]
It says made by corbin on the help screen, and he claims to have made the help screen

**Comment by SudhanPlayz** [comment]
Its not me i think they were just changed the help command

**Comment by SudhanPlayz** [comment]
This person? I don't even know him and if he used his credits instead of mine I really don't know what to do in this situation.
![](https://pika-pika.is-inside.me/JznmopCC.png)

**Comment by MHTal** [comment]
They're all good as I see it, the license you put on this allows for modification and redistribution.

**Comment by lAzrythl** [comment]
No I'm Lapiduck, it was CorbinDioxide
