### ISSUE TITLE
Site Down @ https://musicbot.darrenofficial.com/

### ISSUE THREAD

**Issue by x6410v** [SudhanPlayz/Discord-MusicBot#1310]
I believe the site is experiencing downtime. 

Trying to connect via the following browsers:
- Firefox
- Chrome
- DuckDuckGo

Tested with and without vpn.

The error could be due to a network issue on my side though i thought i should make an issue.

**Comment by LewdHuTao** [comment]
hope this help. if you have trouble to setup the bot you can join the support server and ask there

![image](https://github.com/SudhanPlayz/Discord-MusicBot/assets/90232327/1ad1f24e-615d-48f0-a672-d9e286a7c46a)
