### ISSUE TITLE
Increase lyrics to more than 1 embed message

### ISSUE THREAD

**Issue by joeyk710** [SudhanPlayz/Discord-MusicBot#133]
**Is your feature request related to a problem? Please describe.**

> Maybe for lyrics instead of having the cut off be set to 2048 for embeds, extend the lyrics to another embed so it can show all of the lyrics to a song. An idea.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Colonel-Ltd** [comment]
updated and added pagination

**Comment by joeyk710** [comment]
Thank you so much! The changes made have been amazing!
