### ISSUE TITLE
New lyrics embed

### ISSUE THREAD

**Issue by joeyk710** [SudhanPlayz/Discord-MusicBot#140]
When lyrics are shown, the words at the bottom get cut off into the next page of lyrics. Any way to make it so it just pushes that line to the next page?

Also is it possible to maybe add a feature to search lyrics to any song without being in a voice channel at any time?

![Screenshot (91)](https://user-images.githubusercontent.com/71621973/112100222-2b61cc80-8b7b-11eb-8daf-01cffa06c91f.png)

**Comment by hadiabbasjafry** [comment]
I dont think thats possible , even if it is that will be hard. the command will be similer to of yagpdb's dictionary ones you can search it.

**Comment by joeyk710** [comment]
I almost feel like that would be a really good feature to have instead of the bot only finding lyrics to the song playing.

**Comment by SudhanPlayz** [comment]
Will do on v4
