### ISSUE TITLE
Slash commands?

### ISSUE THREAD

**Issue by joeyk710** [SudhanPlayz/Discord-MusicBot#146]
Would it be possible in the future to make these commands into slash commands as well? Or maybe how to do them for my code? That would be amazing!

**Comment by SudhanPlayz** [comment]
Ahh yes that's a very good idea, I'm do with it v4

**Comment by joeyk710** [comment]
That is amazing! I noticed the Rythm bot and other bots as well use slash commands on top of the regular prefix. It's really amazing. Thank you so much!
