### ISSUE TITLE
play command doesn't work

### ISSUE THREAD

**Issue by alex12266** [SudhanPlayz/Discord-MusicBot#151]
a few days ago I started having the following problem, I would appreciate if you help me solve it
![image](https://user-images.githubusercontent.com/74673312/114249761-1baafc00-9961-11eb-9edd-6459848b8ad5.png)

**Comment by joeyk710** [comment]
Did you change anything in your code?

**Comment by joeyk710** [comment]
Join the support discord server so we can help you more!

**Comment by joeyk710** [comment]
> a few days ago I started having the following problem, I would appreciate if you help me solve it
> ![image](https://user-images.githubusercontent.com/74673312/114249761-1baafc00-9961-11eb-9edd-6459848b8ad5.png)

Are you still having issues?

**Comment by alex12266** [comment]
yes

**Comment by joeyk710** [comment]
> yes

Can you join the support discord server so we can help you quicker? If not, have you made any edits to the code?

**Comment by alex12266** [comment]
but I'm going to download the new code because the one I had was old, even so, thanks for the help : D

**Comment by joeyk710** [comment]
I was going to suggest that. No problem!

**Comment by alex12266** [comment]
if something happens he informed you by discord
