### ISSUE TITLE
How to make bot NOT to leave voice channel(aka stay 24/7)

### ISSUE THREAD

**Issue by superhe11** [SudhanPlayz/Discord-MusicBot#155]
Hi, i want to have 24/7 ds bot, while deploying to heroku i can choose how much time before quitting bot will have. Is it any solution to have it 24/7?

**Comment by SudhanPlayz** [comment]
You wanted to host your bot 24/7? Well then buy a VPS. We don't provide you free hosting services like some websites etc. We suggest you using https://digitalocean.com/ for shipping(production of the product) your apps/bots. Still wanted to host your bots fore free? We don't help you.
