### ISSUE TITLE
Spotify Playlist vs Song info in Dashboard

### ISSUE THREAD

**Issue by Sattishh** [SudhanPlayz/Discord-MusicBot#163]
I played a playlist in Spotify and the song info shows ```[object Object]```

Should be a quick fix!
Thank you :)
![image](https://user-images.githubusercontent.com/51452387/116819350-f7c28b00-ab99-11eb-9c60-c03ba6b052b0.png)

**Comment by SudhanPlayz** [comment]
i think i fixed it ;-;

**Comment by Colonel-Ltd** [comment]
Fixed.

**Comment by Sattishh** [comment]
All good now. Thank you all :)
