### ISSUE TITLE
Slash commands not registered for all guilds

### ISSUE THREAD

**Issue by Sattishh** [SudhanPlayz/Discord-MusicBot#164]
As mentioned by Sudhan, slash commands are currently not registered for all guilds. That's the only reason why slash commands don't work at the moment. 

Just wanted to update everyone & raise the issue!

**Comment by SudhanPlayz** [comment]
Fixed in [ce9cb3f](https://github.com/SudhanPlayz/Discord-MusicBot/commit/ce9cb3f0673776822f872380abf9b3f743083177)
