### ISSUE TITLE
[IMPORTANT] Music Bot v4 - Bugs

### ISSUE THREAD

**Issue by SudhanPlayz** [SudhanPlayz/Discord-MusicBot#166]
You may see many bugs, you are allowed to pull request and i accept every contributers, make sure your contribution is good to get accepted, Comment your bugs and errors here, We will try to fix it as soon as possible!

Also make sure to check out [development branch](https://github.com/SudhanPlayz/Discord-MusicBot/tree/development)

**Comment by SudhanPlayz** [comment]
Some bugs has been fixed merged development branch to main branch ;)

**Comment by Lukas349** [comment]
play command doesn't change from "🔍 Searching..."

**Comment by SudhanPlayz** [comment]
> play command doesn't change from "🔍 Searching..."

Can you post your error logs?

**Comment by Itzzz-Malik** [comment]
play command doesn't change from "🔍 Searching..."

![image](https://user-images.githubusercontent.com/76797986/116953499-1312c080-ac96-11eb-8e82-0540e603ed72.png)

**Comment by SudhanPlayz** [comment]
> play command doesn't change from "🔍 Searching..."
> 
> ![image](https://user-images.githubusercontent.com/76797986/116953499-1312c080-ac96-11eb-8e82-0540e603ed72.png)

It means no Lavalink node connected, Try restarting the bot or connect to correct lavalink

**Comment by SudhanPlayz** [comment]
Make sure to update your codes to v4.1.0
