### ISSUE TITLE
Slash Command: loop command not working

### ISSUE THREAD

**Issue by mixmediayt** [SudhanPlayz/Discord-MusicBot#192]
Whenever I try to use /loop it gives me the following error 
![bandicam 2021-05-07 15-13-18-504](https://user-images.githubusercontent.com/76951294/117436229-319fe280-af48-11eb-9dc8-bbde8f630edf.jpg)

**Comment by joeyk710** [comment]
> Whenever I try to use /loop it gives me the following error
> ![bandicam 2021-05-07 15-13-18-504](https://user-images.githubusercontent.com/76951294/117436229-319fe280-af48-11eb-9dc8-bbde8f630edf.jpg)

This slash command is still being fixed. We are in the process of fixing it and should be updated as soon as possible.

**Comment by joeyk710** [comment]
> > Whenever I try to use /loop it gives me the following error
> > ![bandicam 2021-05-07 15-13-18-504](https://user-images.githubusercontent.com/76951294/117436229-319fe280-af48-11eb-9dc8-bbde8f630edf.jpg)
> 
> This slash command is still being fixed. We are in the process of fixing it and should be updated as soon as possible.

do you still need help? this issue will be closed in a few hours if there is no response
