### ISSUE TITLE
/stop and /leave

### ISSUE THREAD

**Issue by joeyk710** [SudhanPlayz/Discord-MusicBot#204]
Please refer to #213 for more information about the bot.

**Comment by aitronssesin** [comment]
I use /leave but it say me the same that interaction has failed

**Comment by Daniel23XD** [comment]
I use the command to put music and I get that the music is put on and at the moment it comes out that all the queue is eliminated

**Comment by joeyk710** [comment]
I appreciate you submitting issues, but we can't fix literally every little bug that you find. We can't fix them when you want so you need to have patience. We will fix the bugs and such when we get the chance to.

**Comment by sovanmondal182** [comment]
![image](https://user-images.githubusercontent.com/56794254/118029095-6e713c80-b381-11eb-9021-c1112df70bad.png)
Song is not playing

**Comment by joeyk710** [comment]
> ![image](https://user-images.githubusercontent.com/56794254/118029095-6e713c80-b381-11eb-9021-c1112df70bad.png)
> Song is not playing

this doesnt have to do with the slash commands. change your lavalink server in the config.js to one of the alternate servers here - https://lavalink.org
