### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by Akshit1025** [SudhanPlayz/Discord-MusicBot#210]
When I go to the website and click dashboard it says that `Invalid OAuth2 Redirect_uri`

**Please help**

**Comment by RayenMichael** [comment]
it's very easy to solve

**Comment by RayenMichael** [comment]
just give me your discord to add you and then i will help you

**Comment by Akshit1025** [comment]
I am already in the code with sudhan discord server

I am Akshit Gupta on the server


@Akshit Gupta
