### ISSUE TITLE
Not Working Properly 

### ISSUE THREAD

**Issue by Dr-Appukuttan** [SudhanPlayz/Discord-MusicBot#217]
Showing Client.build is not a function
![Screenshot_20210516-091001](https://user-images.githubusercontent.com/73917119/118385357-bca96880-b62b-11eb-882c-5de104bc15d0.png)

**Comment by joeyk710** [comment]
Are you in the discord server? We can help you more. Otherwise, I would create a new bot.

**Comment by Dr-Appukuttan** [comment]
> Are you in the discord server? We can help you more. Otherwise, I would create a new bot.

Yes am in
