### ISSUE TITLE
dj role for every command

### ISSUE THREAD

**Issue by RayenMichael** [SudhanPlayz/Discord-MusicBot#225]
dj role for every command thats a stupid thing if it not exist then this is a bug

**Comment by joeyk710** [comment]
We will look into it. Also, please watch the way you speak to us. We're trying our best here to make everything work as best as we can. Take a look here - #213 for more information. It's a great idea. If you would like to help fix the bugs on top of adding the dj role for every command, please do so. We are very limited on how many people we have to fix things all the time.

**Comment by joeyk710** [comment]
Not a bug btw if its not on every command. Don't tell us how to do things.
