### ISSUE TITLE
question

### ISSUE THREAD

**Issue by JacProsser** [SudhanPlayz/Discord-MusicBot#228]
Would you be able to tell me how you've got the code to keep the bot in the vc 24/7? i've looked at your code and can't find anything to do with staying in the channel

**Comment by joeyk710** [comment]
You can find the 24/7 setting in the config.js file. Same file as your bot token. Just change it to true and your bot should stay in vc 24/7. If it does not, drop by our [discord](https://discord.gg/a9SHDpD) and we should be able to help you more.

**Comment by JacProsser** [comment]
well this was not the goal. i was wondering about the code that keeps the bot on the vc as i would like to implement it into my own bot however i cannot find this anywhere
