### ISSUE TITLE
Youtube links

### ISSUE THREAD

**Issue by OblivionGhoul** [SudhanPlayz/Discord-MusicBot#24]
Just a suggestion so that you can play music using YouTube links. Also there is no limit on how much you can change volume. Hope you reach 500 subs :).

**Comment by SudhanPlayz** [comment]
Yeah will do :)

**Comment by cjxe** [comment]
> Yeah will do :)

I managed to do it with a few lines of code (added added more commands). Can contribute to the repo if you add.
