### ISSUE TITLE
Feature Request - Discord Buttons

### ISSUE THREAD

**Issue by ChillNotTaken** [SudhanPlayz/Discord-MusicBot#252]
**Add Disocrd-Buttons To the music commands**
As you know discord-buttons is here so now literally every music bot uses buttons you should add that too you could just use discord-buttons npm which would be great!

**Comment by joeyk710** [comment]
Can you please follow the correct template for creating a feature request? Thanks.

**Comment by ChillNotTaken** [comment]
Isn't it understandable tho?

**Comment by joeyk710** [comment]
We are waiting for discord.js v13 to be released so we can add more features to the bot. Please check the discussion posted on v5

**Comment by ChillNotTaken** [comment]
> Can you please follow the correct template for creating a feature request? Thanks.



> We are waiting for discord.js v13 to be released so we can add more features to the bot. Please check the discussion posted on v5

Okay I posted stuff there thanks for th quick reply and bot

**Comment by joeyk710** [comment]
Nono thank you! Lol

**Comment by ChillNotTaken** [comment]
> Nono thank you! Lol

Thank me for what?

**Comment by joeyk710** [comment]
For the suggestion!

**Comment by ChillNotTaken** [comment]
Oh okay lol
