### ISSUE TITLE
Can't play YouTube Topic channel music

### ISSUE THREAD

**Issue by prodlowd** [SudhanPlayz/Discord-MusicBot#253]
Dear Sudhan,
I am using your bot as a template for a friend's discord server, and I have noticed that whenever using the `/play` command, if the video is from a YouTube Topic Channel, (I tried my music 'lowd. Take the shot') then the bot will start playing, the instantly stop playing. This only occurs when it is a YT Topic Channel. Is there a fix for this issue?

https://prnt.sc/14yrobz

Many thanks,
lowd.

**Comment by prodlowd** [comment]
Sometimes it works and sometimes it doesn't work for the YouTube Topic channel issue. I am going to see if I can try and find a pattern where it works and doesn't work

https://prnt.sc/14yvo3s
(Example of it working)

lowd.

**Comment by joeyk710** [comment]
We know that there are a lot of bugs with the bot right now and we can't fix all of them. Check this list which shows updates and improvements being made to the bot for the future - #236

**Comment by joeyk710** [comment]
The picture links shown are not viewing for me btw. If you could send another type of format, that would be great to get a visual of what we need to work on for the next update. Thanks!

**Comment by prodlowd** [comment]
Thanks! I appreciate what you do! ♥️
