### ISSUE TITLE
Please use the issue templates.

### ISSUE THREAD

**Issue by joeyk710** [SudhanPlayz/Discord-MusicBot#254]
### PLEASE USE THIS TEMPLATE WHEN CREATING A NEW ISSUE. This allows us to help you better. 

**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by SudhanPlayz** [comment]
Can't we close this?
