### ISSUE TITLE
No Songs Found

### ISSUE THREAD

**Issue by Hiajen** [SudhanPlayz/Discord-MusicBot#255]
**Please describe the problem you are having in as much detail as possible:**
Freshly setup Bot with default config using the provided LavaLink Server but disabled WebServer.
Bot starts up fine and commands are working great, but the bot does not find ANY Music from ANY Platform (tried YouTube, SoundCloud, Spotify)

Console is throwing following:
```
Z [HeadersTimeoutError]: Headers Timeout Error
    at Timeout.lt [as _onTimeout] (/home/bots/NodeDiscordMusicBot/node_modules/petitio/dist/index.js:4:5697)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}
```

- discord.js version: using v4.1.1 dont know what discord JS version you are using.
- Node.js version: v14.16.1
- Operating system: Debian 10
- Priority this issue should have – please be realistic and elaborate if possible: BLOCKER, CRITICAL Bot Purpose not functional

**Comment by Akshit1025** [comment]
update the version of discord.js to v12

**Comment by Hiajen** [comment]
Sorry for the missunderstanding, i am using the bot release v4.1.1 , it uses discordjs v12.5.3

**Comment by SudhanPlayz** [comment]
Its your lavalink server problem change your lavalink server and try again.

**Comment by Hiajen** [comment]
Got it ...

You need to setup your own LavaLink Server ( https://github.com/freyacodes/Lavalink )
