### ISSUE TITLE
Error code 404

### ISSUE THREAD

**Issue by ohidur4** [SudhanPlayz/Discord-MusicBot#263]
![20210623_124236](https://user-images.githubusercontent.com/66195433/123048739-8cba6580-d420-11eb-930d-c91c0b19b8c8.jpg)

**Comment by joeyk710** [comment]
Can you at least use the issue template? All u did was post an image without explaining the issue

**Comment by ohidur4** [comment]
discord.js version:12.5.3
Node.js version:6.14.13
Operating system: heroku cli
Every time when using play command it's giving error code 404

**Comment by joeyk710** [comment]
U need at least node 12 using the bot. Heroku isn't the best. Try creating a new project using another hosting platform

**Comment by ohidur4** [comment]
Can you suggest?

**Comment by joeyk710** [comment]
Replit, visual studio code, a VPS

**Comment by ohidur4** [comment]
Okay
