### ISSUE TITLE
why no volume in my bot 

### ISSUE THREAD

**Issue by Ade-Hermansyah** [SudhanPlayz/Discord-MusicBot#264]
plz help me my bot is no volume even
![Screen Shot 2021-06-24 at 13 36 57](https://user-images.githubusercontent.com/83535353/123214338-497bf780-d4f1-11eb-9b58-8f1ab40971b1.png)

**Comment by joeyk710** [comment]
Bruh use the damn volume command. U should know how to use the music bot even after u were banned.

**Comment by Ade-Hermansyah** [comment]
fp im alr 100 volume but stll no sound

**Comment by joeyk710** [comment]
Change the bots volume on discord bro and what the hell is fp
