### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by D4rkk1** [SudhanPlayz/Discord-MusicBot#275]
https://prnt.sc/1730sa1

**Comment by Akshit1025** [comment]
what is the meaning of your issue please explain in detail

**Comment by D4rkk1** [comment]
o bot não inicia

**Comment by D4rkk1** [comment]
the bot does not start

**Comment by bettydreemurr** [comment]
we have too little detail to know why it does not start, if you could explain a certain thing, for example: how did you do your configuration? where did you put the token and the others options etc ...

**Comment by D4rkk1** [comment]
I put it like it is on the youtube video, and where are you from?

**Comment by joeyk710** [comment]
Your image doesn't load and you did not follow the issue layout so we will not help you since you did not give us more information about your issue.
