### ISSUE TITLE
Lavalink node not connected

### ISSUE THREAD

**Issue by Akshatyt** [SudhanPlayz/Discord-MusicBot#285]
**The bot is saying :x: | Lavalink node not connected**
![image](https://user-images.githubusercontent.com/82574385/125155468-bf34c400-e17d-11eb-8b26-16c166d1f483.png)

```js
![Screenshot 2021-07-10 125120](https://user-images.githubusercontent.com/82574385/125155441-8d236200-e17d-11eb-9339-619712a15ab8.png)
```

**Comment by SudhanPlayz** [comment]
Connect to a lavalink server, Or make a lavalink server
