### ISSUE TITLE
website dashboard and invite bug

### ISSUE THREAD

**Issue by civilizedcadet** [SudhanPlayz/Discord-MusicBot#288]
the invite ad dashboard is not working
i did everything as shown in the video but i am facing problems please help 
![Screenshot 2021-07-14 031034](https://user-images.githubusercontent.com/83629423/125605113-28952a9f-05d8-4882-b6a4-632f23775f5b.png)
![Screenshot 2021-07-14 031326](https://user-images.githubusercontent.com/83629423/125605229-f60e3472-3377-48d1-8f6f-992754e16fb2.png)

**Comment by SudhanPlayz** [comment]
You need a `http` callback URL

**Comment by Astrowes** [comment]
still same error for me
