### ISSUE TITLE
bug: RangeError: Provided argument must be present.

### ISSUE THREAD

**Issue by BrentFidder** [SudhanPlayz/Discord-MusicBot#295]
![image](https://user-images.githubusercontent.com/78434993/126079554-06cd0f4b-9cc5-4a48-bc8a-002b36f4e187.png)

Ok, so the problem is all the bots, it doesn't matter what music bot every bot made throw ur bot code has the same problem.

It will give an error that it couldn't find any music witch is really annoying, if you enter a link or anything it gives you the same error code so please take a look at that.

Sincerely,
Brent

Discord: Brent#5083

**Comment by maximumdarkness1** [comment]
Hey Brent, It may seem like the lavalink is not hosted proper or a error with your Script, Sudhan may look over this to see what's wrong and try to find out (Not Officially with Support Team) Please List the errors given in the console on here Thanks :)

**Comment by BrentFidder** [comment]
Hi,

There isn't any error showed up on the console.

Op zo 18 jul. 2021 21:25 schreef maximumdarkness1 ***@***.***

**Comment by ChandanGaming** [comment]
I have coming this issue too

**Comment by aimxnn** [comment]
me too

**Comment by lider369** [comment]
me too

**Comment by lider369** [comment]
When I type play it gives the following line in the console
![error](https://user-images.githubusercontent.com/87528209/126113677-2876d495-a979-4b24-bb84-689380828c4b.PNG)

**Comment by jiading4540** [comment]
me too

**Comment by SadieDev** [comment]
Same issue

**Comment by SadieDev** [comment]
`RangeError: Provided argument must be present.
at Function.validate (/app/node_modules/erela.js/dist/structures/Utils.js:46:19)
at Queue.add (/app/node_modules/erela.js/dist/structures/Queue.js:38:33)
at Object.run (/app/commands/play.js:86:34)
at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by SudhanPlayz** [comment]
> > Same issue
> 
> `RangeError: Provided argument must be present. at Function.validate (/app/node_modules/erela.js/dist/structures/Utils.js:46:19) at Queue.add (/app/node_modules/erela.js/dist/structures/Queue.js:38:33) at Object.run (/app/commands/play.js:86:34) at processTicksAndRejections (internal/process/task_queues.js:95:5)`

Can you tell anyway to reproduce this error?

**Comment by lider369** [comment]
will this problem be solved

**Comment by SudhanPlayz** [comment]
> will this problem be solved

RangeError: Provided argument must be present. - I need to figure out how this actually happens and i can try to fix it
and For no songs found you should change your lavalink server

**Comment by lider369** [comment]
> lavalink

how to change server

**Comment by lider369** [comment]
how to change server?

**Comment by lider369** [comment]
how will I do

**Comment by D4rkk1** [comment]
how i change my lavalink server?

**Comment by OceanusFaction** [comment]
Yeah this error happends for everyone, @SudhanPlayz it happends when we just try and click run the bot on repilt. The music says that it cant find anything! The only way you can do it rn is by creating teh activity

**Comment by SudhanPlayz** [comment]
> Yeah this error happends for everyone, @SudhanPlayz it happends when we just try and click run the bot on repilt. The music says that it cant find anything! The only way you can do it rn is by creating teh activity

It's because of your lavalink server rate limit not this code and I have changed this issue into RangeError which some people are getting and posted in this issue

**Comment by OceanusFaction** [comment]
> > Yeah this error happends for everyone, @SudhanPlayz it happends when we just try and click run the bot on repilt. The music says that it cant find anything! The only way you can do it rn is by creating teh activity
> 
> It's because of your lavalink server rate limit not this code and I have changed this issue into RangeError which some people are getting and posted in this issue

So how can I fix the lavalink thing?

**Comment by SudhanPlayz** [comment]
> > > Yeah this error happends for everyone, @SudhanPlayz it happends when we just try and click run the bot on repilt. The music says that it cant find anything! The only way you can do it rn is by creating teh activity
> > 
> > It's because of your lavalink server rate limit not this code and I have changed this issue into RangeError which some people are getting and posted in this issue
> 
> So how can I fix the lavalink thing?

Create your own lavalink server and connect to it

**Comment by D4rkk1** [comment]
and where does it create a lavalink server

**Comment by ChandanGaming** [comment]
@SudhanPlayz can you make a tutorial how to make lavalink server or just tell us the steps

**Comment by SudhanPlayz** [comment]
> and how create a lavalink server?

It just connect to a lavalink server, not create

**Comment by SudhanPlayz** [comment]
> @SudhanPlayz can you make a tutorial how to make lavalink server or just tell us the steps

Not yet, But our support server can help you creating them

**Comment by ChandanGaming** [comment]
So can you provide a support server link?

**Comment by OceanusFaction** [comment]
> So can you provide a support server link?

discord.gg/cwkhan

**Comment by SudhanPlayz** [comment]
This is lavalink server problem, Please fix your lavalink server
