### ISSUE TITLE
[Feature Request] Pitch command

### ISSUE THREAD

**Issue by ChiboYen** [SudhanPlayz/Discord-MusicBot#301]
**Is your feature request related to a problem? Please describe.**
No, it is a pure feature request.

**Describe the ideal solution**
I am suggesting a command addition to change the pitch of the music being played without changing the speed of the music. An example of this would be a command such as `?pitch 1.1` to increase the pitch of the music being played by 10%.

**Describe alternatives you've considered**
No alternatives were considered.

**Additional context**
No additional context.

**Comment by LilMayo69** [comment]
Pure feature request
Add the option to implement a voice channel id so that that bot can join the channel on join. Would really appreciate if you could do this for the bot

**Comment by SudhanPlayz** [comment]
maybe will do in v5
