### ISSUE TITLE
[NEW] PLEASE ADD Discord Bot read messages and respond back feature

### ISSUE THREAD

**Issue by DorisJohnson03** [SudhanPlayz/Discord-MusicBot#310]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]
NO

**Describe the ideal solution**
Discord Bot read messages and respond back 
Like this: https://youtu.be/XiluM3zjNuw

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by SudhanPlayz** [comment]
Well it can able to read commands and respond back. It has a good handler to handle the commands
