### ISSUE TITLE
Soptify and SoundCloud not playing

### ISSUE THREAD

**Issue by VerstreuteSeele** [SudhanPlayz/Discord-MusicBot#316]
Adding a spotify or soundcloud link fails. It says "added to queue" then "playing" and seconds later "queue has ended" without every playing the song

- discord.js version: 12.5.3
- Node.js version: 14.16
- Operating system: Windows 10 & Raspbian
- Priority this issue should have – please be realistic and elaborate if possible: idk.. mid to high I guess..

**Comment by VerstreuteSeele** [comment]
Fixed spotify with local lavalink server. 

sc returns an 401 but from what I can tell thats not something you can fix?

**Comment by joeyk710** [comment]
SoundCloud with lavalink does not work right now. Ask for when it's gonna be fixed in https://discord.gg/jda

**Comment by VerstreuteSeele** [comment]
lil info for you. the dev branch of lavalink fixed the issue

https://ci.fredboat.com/viewType.html?buildTypeId=Lavalink_Build&branch_Lavalink=refs%2Fheads%2Fdev&tab=buildTypeStatusDiv&guest=!
