### ISSUE TITLE
ERROR Command

### ISSUE THREAD

**Issue by badriyatus123** [SudhanPlayz/Discord-MusicBot#349]
hello I have an error like this is it normal?

![gambar](https://user-images.githubusercontent.com/87899416/131222226-5cf0b774-264a-4a53-b797-5b406f6df4df.png)

**Comment by DyBlok27** [comment]
it means that some guils have not enabled the slash command on their server

**Comment by badriyatus123** [comment]
> it means that some guils have not enabled the slash command on their server

so to fix this what should i do?

**Comment by DyBlok27** [comment]
You need to have the bot defer to the guilds

**Comment by joeyk710** [comment]
> > it means that some guils have not enabled the slash command on their server
> 
> so to fix this what should i do?

you need to re-invite the bot with the `applications.commands` scope from the discord dev portal. its an easy discord error to fix. if your bot is in a lot of servers that you can't get access to, then you will have to deal with that error in your console.
