### ISSUE TITLE
Bug disconnect

### ISSUE THREAD

**Issue by DyBlok27** [SudhanPlayz/Discord-MusicBot#358]
When you disconnect the bot from a vowel manually, while a song is playing, if you look at the queue you find that the song is still playing.

**Comment by joeyk710** [comment]
I'm not really sure what you mean by 'vowel', but the bot is to not be forcefully disconnected. The disconnect command was created for a reason.

**Comment by DyBlok27** [comment]
sorry for "vowel" I meant vocal, but what if a person would like to do first to disconnect the bot?

**Comment by joeyk710** [comment]
Use the disconnect command.

**Comment by DyBlok27** [comment]
If in doubt, can you do it?  and if so could you tell me how?  thanks

**Comment by joeyk710** [comment]
I keep telling you to use the disconnect command to make the bot leave vc.  (prefix)dc

**Comment by joeyk710** [comment]
If you have more issues, please feel free to join our discord server
