### ISSUE TITLE
Error client.build is not a function

### ISSUE THREAD

**Issue by PhantomNimbi** [SudhanPlayz/Discord-MusicBot#363]
I'm attempting to run the bot on my Ubuntu 20.04 VPS. I followed the instrucions and created my `.env` file as stated but every time I attempt to run the bot I the error below.

```js
discord-bots@nimbivps:~/Discord-MusicBot$ node .
/home/discord-bots/Discord-MusicBot/index.js:4
client.build();
       ^

TypeError: client.build is not a function
    at Object.<anonymous> (/home/discord-bots/Discord-MusicBot/index.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

- discord.js version: 12.x
- Node.js version: 16.x
- Operating system: Ubuntu 20.04
- Priority: Moderate

- partials: not sure
- gateway intents: both
- other: none

**Comment by joeyk710** [comment]
Make sure your config is completely filled out. Nothing can be blank

**Comment by PhantomNimbi** [comment]
> Make sure your config is completely filled out. Nothing can be blank

Mine is albeit i used my own lavalink server so not sure if that could be causing the issue

**Comment by joeyk710** [comment]
The bot needs to be using the botconfig.js

**Comment by PhantomNimbi** [comment]
> The bot needs to be using the botconfig.js

nvm i found my issue i forgot to include the spotify apis

**Comment by joeyk710** [comment]
sounds good

**Comment by PhantomNimbi** [comment]
> sounds good

ok maybe I'm still missing something. Here is my `botconfig.js`

```js
module.exports = {
  Admins: ["465228604721201158"], //Admins of the bot
  ExpressServer: true,//If you wanted to make the website run or not
  DefaultPrefix: process.env.Prefix || ">", //Default prefix, Server Admins can change the prefix
  Port: 3000, //Which port website gonna be hosted
  SupportServer: "https://discord.gg/sbySMS7m3v", //Support Server Link
  Token: process.env.Token || "", //Discord Bot Token
  ClientID: process.env.Discord_ClientID || "", //Discord Client ID
  ClientSecret: process.env.Discord_ClientSecret || "", //Discord Client Secret
  Scopes: ["identify", "guilds", "applications.commands"], //Discord OAuth2 Scopes
  CallbackURL: "/api/callback", //Discord OAuth2 Callback URL
  "24/7": false, //If you want the bot to be stay in the vc 24/7
  CookieSecret: "Pikachu is cute", //A Secret like a password
  IconURL:
    "https://raw.githubusercontent.com/SudhanPlayz/Discord-MusicBot/master/assets/logo.gif", //URL of all embed author icons | Dont edit unless you dont need that Music CD Spining
  Permissions: 2205280576, //Bot Inviting Permissions
  Website: process.env.Website || "http://localhost", //Website where it was hosted at includes http or https || Use "0.0.0.0" if you using Heroku

//Lavalink
  /*
   Lavalink: {
    id: "Main",
    host: "lava.link",
    port: 80,
    pass: "youshallnotpass", 
    secure: false, // Set this to true if you're self-hosting lavalink on replit.
  },
  */

  Lavalink: {
    id: "Main",
    host: "https://ip13.ip-167-114-94.net",
    port: 3032,
    pass: "youshallnotpass",
    secure: false,
  },

  //Alternate Lavalink
  /*
  Lavalink: {
    id: "Main",
    host: "lava.sudhan.tech",
    port: 1234,
    pass: "CodingWithSudhan",
    secure: false // Set this to true if you're self-hosting lavalink on replit.
  },
  */


  //Please go to https://developer.spotify.com/dashboard/
  Spotify: {
    ClientID: process.env.Spotify_ClientID || "", //Spotify Client ID
    ClientSecret: process.env.Spotify_ClientSecret || "", //Spotify Client Secret
  },
};
```

**Comment by joeyk710** [comment]
your lavalink server hostname cannot have https. also i wouldn't know if your config is empty because you removed the token info and other stuff

**Comment by PhantomNimbi** [comment]
> your lavalink server hostname cannot have https. also i wouldn't know if your config is empty because you removed the token info and other stuff

I used the `.env` file for those so it wouldn't display them

**Comment by joeyk710** [comment]
above i said to not make a .env file. you need to use the botconfig.js

**Comment by PhantomNimbi** [comment]
> above i said to not make a .env file. you need to use the botconfig.js

oof yeah im seeing that now. soz the `process.env` thing got me cuz its normally used for `.env` files xD

Editing it now. will see if this works

**Comment by joeyk710** [comment]
i dont mind helping here, but please join our discord where we can help you faster = https://discord.gg/x6x7MHZ488

**Comment by PhantomNimbi** [comment]
> i dont mind helping here, but please join our discord where we can help you faster = https://discord.gg/x6x7MHZ488

looks like im already in there. I'm Nimbi on there

**Comment by joeyk710** [comment]
got it!

**Comment by PhantomNimbi** [comment]
> got it!

Moving on to the Discord. I got it running but now I have new errors xD
