### ISSUE TITLE
Invalid OAuth2 redirect_uri

### ISSUE THREAD

**Issue by Trebll** [SudhanPlayz/Discord-MusicBot#369]
I have the correct http and https redirects on my dev portal but I am still receiving this for some reason

redirects:
![Screenshot 2021-09-02 022045](https://user-images.githubusercontent.com/76267123/131762314-1661e4bd-e655-4888-8fd2-344ff40e31ef.png)

error:
![Screenshot 2021-09-02 022107](https://user-images.githubusercontent.com/76267123/131762340-8ffae241-98fa-4d59-ba07-08ec9d48a3e4.png)

tried doing it with a generated link within the dev portal as well
![Screenshot 2021-09-02 022310](https://user-images.githubusercontent.com/76267123/131762443-647db58c-5860-47d3-8a6f-d48d4d7fb00e.png)

**Comment by joeyk710** [comment]
You need to add the website link to your config which is why it doesn't work. Line 17 in the botconfig needs to be https://(website name).

**Comment by joeyk710** [comment]
This isn't a bug btw. You just need to edit the config. It's a discord error. Not a bot error.
