### ISSUE TITLE
the help command wont show

### ISSUE THREAD

**Issue by masterofninja** [SudhanPlayz/Discord-MusicBot#370]
when I do a help command it shows this in the logs

(node:22) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'IconURL' of undefined
    at Object.run (/app/commands/help.js:30:32)
    at module.exports (/app/events/message.js:67:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js

**Comment by DarrenOfficial** [comment]
Hey, what version of the bot are you currently using?

**Comment by DarrenOfficial** [comment]
also, do you see `botconfig.js` in your root folder?
![BotConfigShow](https://darrennathanael.com/cdn/github/botconfig.png)
If you don't see it, just copy and paste [this](https://github.com/SudhanPlayz/Discord-MusicBot/blob/master/botconfig.js) then put it on your root folder

**Comment by joeyk710** [comment]
This issue has been untouched for 2 days, so it will be closed
