### ISSUE TITLE
i think there's some wrong typing (redirect_uri) in views/index.html some some other parts with that uri

### ISSUE THREAD

**Issue by Sothirich** [SudhanPlayz/Discord-MusicBot#374]
![image](https://user-images.githubusercontent.com/83401742/132318655-20490915-594e-4da7-b155-de2302ee5e8c.png)

**Comment by Kakarot-0690** [comment]
I dont think so, its uri only

**Comment by SudhanPlayz** [comment]
Its `redirect_uri`
