### ISSUE TITLE
Intents Problem

### ISSUE THREAD

**Issue by Rescued0** [SudhanPlayz/Discord-MusicBot#384]
A intents Problem When I switch to discord.js 13 , i don't know where i should add the intents.
**Further details:**

- discord.js version: 13
- Node.js version: 16
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: yes
- other: none

**Comment by Kakarot-0690** [comment]
;--; Please refer to the djs docs

**Comment by joeyk710** [comment]
> 
> 
> 
> 
> 
> 
> A intents Problem When I switch to discord.js 13 , i don't know where i should add the intents.
> 
> **Further details:**
> 
> 
> 
> - discord.js version: 13
> 
> - Node.js version: 16
> 
> - Operating system: Windows
> 
> - Priority this issue should have – please be realistic and elaborate if possible:
> 
> 
> 
> **Relevant client options:**
> 
> 
> 
> - partials: none
> 
> - gateway intents: yes
> 
> - other: none
> 
> 

The bot currently isn't compatible with djs v13. The bot will be updated to support it in the next update so check the djs docs and guide on how to fix ur issue.
