### ISSUE TITLE
[Feature request] playlists/collections

### ISSUE THREAD

**Issue by emhl** [SudhanPlayz/Discord-MusicBot#386]
**Is your feature request related to a problem? Please describe.**
- i don't listen to that many different playlists and i don't want to always lookup the link to my playlists a easy command to load a playlist would save much time

**Describe the ideal solution**
- Users can create and edit playlists through a command that are only axessible to themselves if not shared through a uique playlistID
- the current queue should be able to be added to a playlist with a simple command

**Describe alternatives you've considered**
- playlist are global and exist as a textfile containg a list of youtube links and can be loaded by everyone through a single command

**Additional context**
the collections feature of Jockiemusic is a quite good integration of that feature

**Comment by joeyk710** [comment]
This isn't really needed, but we will consider it
