### ISSUE TITLE
Playback issues when using "Automatic" region

### ISSUE THREAD

**Issue by notchris** [SudhanPlayz/Discord-MusicBot#392]
**Please describe the problem you are having in as much detail as possible:**

When using the "Automatic" setting for region selection in a voice channel, I experienced stuttering & playback issues. Changing the region to anything except "Automatic" resolved the issue (even setting it to a region that is not location near the server hosting the bot & lavalink server).

I also experimented with the Bitrate settings, but that had no noticeable improvement in playback (only quality).

**Include a reproducible code sample here, if possible:**

<img width="619" alt="Screen Shot 2021-09-15 at 9 50 39 PM" src="https://user-images.githubusercontent.com/1944433/133536314-0d2020d1-2d70-4d1f-a6e7-2ae908cf0273.png">

**Further details:**

- discord.js version: 
- Node.js version: v14.17.4
- Operating system: Ubuntu 20.0.4
- Priority this issue should have – please be realistic and elaborate if possible:

Moderate if complaints about stuttering increase

**Comment by joeyk710** [comment]
this has to do with your lavalink server
