### ISSUE TITLE
I ran into a problem when I pressed Disconnecting of the bot

### ISSUE THREAD

**Issue by kornxz** [SudhanPlayz/Discord-MusicBot#395]
I ran into a problem when I pressed Disconnecting of the bot, the queue is still pending and when adding a new song it will not play but will be in the 1st queue instead.

**Comment by joeyk710** [comment]
dont force disconnect the bot. it has a disconnect command for a reason

**Comment by kornxz** [comment]
Usually, when a bot gets disconnected, it has to clear its queue and restart, right?

**Comment by joeyk710** [comment]
it doesnt restart the bot. force disconnecting the bot is literally the same thing
