### ISSUE TITLE
Move queue item

### ISSUE THREAD

**Issue by LeviSnoot** [SudhanPlayz/Discord-MusicBot#400]
**Is your feature request related to a problem? Please describe.**
-
We can use `/skipto` in order to skip the queue to a specific item. The problem with that is that sometimes you just want to move an item up the queue instead of just skipping every item inbetween.

**Describe the ideal solution**
-
A `/moveto` command. For example `/moveto 16 2` moves the item in position 16 in the queue to position 2 in the queue without removing other items.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Kakarot-0690** [comment]
;-;

**Comment by DarrenOfficial** [comment]
added.
