### ISSUE TITLE
Bot keep sending message

### ISSUE THREAD

**Issue by buiquochuy2k1** [SudhanPlayz/Discord-MusicBot#433]
**Please describe the problem you are having in as much detail as possible:**

When we use loop commands and left the voice channel => Bot will pause ( no error here ) and resume when we connect again ( no error here ) but if we leave for too long, bot will disconnect and leave voice channel ( no error here ) and bot continue send now playing message due to a song we hear.

**Comment by Kakarot-0690** [comment]
just remove the voicestate.js from events if it is bugging out for u
