### ISSUE TITLE
The Features which can solve many problems

### ISSUE THREAD

**Issue by ghost** [SudhanPlayz/Discord-MusicBot#434]
_1._ **Stage Channel Support**.
_2._ **Setup Command** which will block the bot from sending now playing messages in every channel the person do commands on.
_3._ **Autoplay** toggle on and off which will improve the bot a whole lot.

**Comment by DarrenOfficial** [comment]
1. Stage channel support will come in v5, reason djs 13 support native stage channel support while djs 12(current) dont.

2. No comment.

3. Autoplay will most likely not be added, it puts alot of loads on the lavalink server.

**Comment by Kakarot-0690** [comment]
> 1. Stage channel support will come in v5, reason djs 13 support native stage channel support while djs 12(current) dont.
> 2. No comment.
> 3. Autoplay will most likely not be added, it puts alot of loads on the lavalink server.

agreed
