### ISSUE TITLE
Everytime i try to debug i get rate limited

### ISSUE THREAD

**Issue by xenos1337** [SudhanPlayz/Discord-MusicBot#436]
**Please describe the problem you are having in as much detail as possible:**
When I try to debug the bot and I run it a few times I get literally rate limited from Discord.

**Include a reproducible code sample here, if possible:**
Run the bot about 2 - 3 times

**Further details:**

- discord.js version: 12.5.3
- Node.js version: v16.5.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: High

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by Kakarot-0690** [comment]
try using a different web browser of try accessing replit from another ip, u might have got rate limited

**Comment by xenos1337** [comment]
its IP limited and its 1h

**Comment by Kakarot-0690** [comment]
that might be some repl issue then, it has nothing to do with the bot
