### ISSUE TITLE
[Slash Command]: [POST-FAILED]

### ISSUE THREAD

**Issue by NONPLAYT** [SudhanPlayz/Discord-MusicBot#437]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

**Further details: when im add bot to server I get this error**
`1:9:2021 - 19:9 | Info: [Slash Command]: [POST-FAILED] Guild 852579380417003540, Command: youtube
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot-1/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot-1/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot-1/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/851042005198307328/guilds/852579380417003540/commands',
  code: 50001,
  httpStatus: 403`
and this error goes with other slash commands
how fix this?

- discord.js version: 12.5.3
- Node.js version: v12.22.6
- Operating system: 
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by joeyk710** [comment]
Use this link below to re-invite it with the proper perms -
https://discord.com/oauth2/authorize?client_id=CLIENT_ID&scope=bot%20applications.commands&permissions=2205280576

• `CLIENT_ID` needs to be replaced with your bot Id

**If you re-invited the bot and your console still shows `DiscordAPIError: Missing Access`, then your bot is in a server you don't have access to so you can't fix it.**

Make sure you restart your bot so it knows it has the correct permissions.
