### ISSUE TITLE
ytdl-core issue

### ISSUE THREAD

**Issue by Hypnamed** [SudhanPlayz/Discord-MusicBot#44]
I do everything i saw in video but when i try to play a music it's not playing and bot stops working.
![bothata](https://user-images.githubusercontent.com/56888921/98490239-f2673200-2241-11eb-9e98-7ef13924fe6c.png)

**Comment by SudhanPlayz** [comment]
Please upgrade your `ytdl-core` package

**Comment by Hypnamed** [comment]
How can i do that?

**Comment by SudhanPlayz** [comment]
`npm i ytdl-code` should be update

**Comment by Hypnamed** [comment]
i did it but it's not working
