### ISSUE TITLE
No way to change the prefix or set the dj role

### ISSUE THREAD

**Issue by Giuseh** [SudhanPlayz/Discord-MusicBot#445]
Hi, i installed yesterday following the bot guide and all seems going fine except for one thing, i tried to change the prefix of the bot from the botconfig.js but it doesn't work, i also tried to change it from the /config command and still doesn't work, i asked help on discord and no one helped me.
When i try to change the prefix or set a dj role i receive this error:

```
(node:10399) UnhandledPromiseRejectionWarning: Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at /home/giuseh/Discord-MusicBot/node_modules/discord.js/src/managers/GuildMemberManager.js:317:16
    at Timeout._onTimeout (/home/giuseh/Discord-MusicBot/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10399) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10399) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Further details:**

- discord.js version:
v12.5.3
- Node.js version:
v14.18.0
- Operating system:
Debian 10
All the stats:
https://i.imgur.com/G76gd2G.jpg

-->

**Comment by Kakarot-0690** [comment]
The DJ role is bugged out, do not use it and for the prefix, u need to delete guild.json before changing prefix in botconfig.js and the config command works for me, so i see no problem
