### ISSUE TITLE
bot permsissions are incorrect

### ISSUE THREAD

**Issue by topjor** [SudhanPlayz/Discord-MusicBot#446]
the bot permissions configured in the botconfig are not setup correctly and using these permissions result in a half broken bot.

https://github.com/SudhanPlayz/Discord-MusicBot/blob/master/botconfig.js#L18
the bot permission code lacks permission for reading channel messages, resulting in the prefix commands to be ignored by the bot as it does not receive channel messages
adding channel message read permission results in the following permission code `2205281600`

**Comment by Kakarot-0690** [comment]
done, thanks for informing ^^
