### ISSUE TITLE
Add Audio File Support

### ISSUE THREAD

**Issue by FreshImmuc** [SudhanPlayz/Discord-MusicBot#447]
**File Upload option or Local file support**

Add a command like ">upload" to then upload a file that gets added to the queue. 
Another option would be to add a folder with songs to just do ">play Example_song.mp3"
and it automatically plays this song file, if exists. I think many people would use this.

**Additional context**
![image](https://user-images.githubusercontent.com/65733898/135761589-55b84eaf-5ee0-4591-b6e6-2954e82c2ef2.png)

**Comment by TechGenius7777** [comment]
Actually this shouldn't be here, This area is for issues and this doesn't seems to be an issue

**Comment by DarrenOfficial** [comment]
> Add a command like ">upload" to then upload a file that gets added to the queue.
No comment.

> Another option would be to add a folder with songs to just do ">play Example_song.mp3" 
This is already a feature on lavalink, just enable local playback, reference: https://github.com/freyacodes/Lavalink/blob/master/LavalinkServer/application.yml.example#14 line 14.
