### ISSUE TITLE
Add player control in web panel

### ISSUE THREAD

**Issue by YueMiyuki** [SudhanPlayz/Discord-MusicBot#457]
**Is your feature request related to a problem? Please describe.**
No

**Describe the ideal solution**
Add music control in the web panel. For example, volume control,skip song, pause, stop

**Comment by TechGenius7777** [comment]
> **Is your feature request related to a problem? Please describe.** No
> 
> **Describe the ideal solution** Add music control in the web panel. For example, volume control,skip song, pause, stop

It's most probably not coming in v5 but it will be released in a sub major update, because we are already running late on v5 development. We are only focusing on discord.js v13 support and discord.js button support for now.

Regards,
Tech Genius
