### ISSUE TITLE
Information about lavalink in ping

### ISSUE THREAD

**Issue by kotru21** [SudhanPlayz/Discord-MusicBot#460]
**Is your feature request related to a problem? Please describe.**
I think that this request is not related to a problem.

**Describe the ideal solution**
I think it would be great if there will be an information about lavalink when you type !ping 
(Some information that lavalink is connected/disconnected,maybe its response time)

**Describe alternatives you've considered**
No

**Additional context**
Maybe it can look something like that:

> Lavalink
- Connected
- 64ms

**Comment by SudhanPlayz** [comment]
Will be doing this in v5
