### ISSUE TITLE
MIssing Perm

### ISSUE THREAD

**Issue by SpaceLeft** [SudhanPlayz/Discord-MusicBot#492]
Add Missing Perm For commands embed

**Comment by TechGenius7777** [comment]
> what do you mean?

I was also going to say that

**Comment by Kakarot-0690** [comment]
> what do you mean?

I think he means to say to add a permission handler where you check the bot's permissions in every guild for each command, like if one guild removes SEND_MESSAGES perm, the bot should send `Missing Permission - SEND_MESSAGES`
