### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by HazzasGaming** [SudhanPlayz/Discord-MusicBot#5]
Came across this error while using the bot, we where using the bot really fast to see how much it could take tho.

(node:14980) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.exports.run (C:\Users\harry_36gamls\OneDrive\Desktop\Studio\commands\play.js:26:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SudhanPlayz** [comment]
It means the bot unable to find a video with the command you sent also you use [v.1.0.0](https://github.com/SudhanPlayz/Discord-MusicBot/tree/v1.0.0) for no issues
