### ISSUE TITLE
Context Menus

### ISSUE THREAD

**Issue by Crni39** [SudhanPlayz/Discord-MusicBot#504]
**Is your feature request related to a problem? Please describe.**
No

**Describe the ideal solution**
Context Menus for music commands

**Comment by SudhanPlayz** [comment]
Can you explain briefly

**Comment by Crni39** [comment]
> Can you explain briefly like where we wanted to use, why we wanted to use

Like, this https://ban.rip/OGR8RQp2, if link, song name isn't valid send error message, commands would be: play, search, help

**Comment by SudhanPlayz** [comment]
Already planned on v5
