### ISSUE TITLE
Discord Music Bot v5 - Commands

### ISSUE THREAD

**Issue by SudhanPlayz** [SudhanPlayz/Discord-MusicBot#508]
# Commands list of v5 which will be added

- [x] ~~bassboost - Enables bass boosting audio effect~~
- [x] filters - add / remove filters. bassboost included 
- [x] clear - Clears the server queue
- [x] ~~config - Edit the server settings~~
- [x] disconnect - Stop the music and leave the voice channel
- [x] grab - Saves the current song to your Direct Messages
- [x] help - Information about the bot
- [x] invite - To invite me to your server
- [x] loop - Loop the current song
- [x] loopqueue - Loop the whole queue
- [x] lyrics - Shows the lyrics of the song searched
- [x] move - Moves a track to a specified position.
- [x] nowplaying - See what song is currently playing
- [x] pause - Pauses the music
- [x] play - Play your favorite songs
- [x] queue - Shows all currently enqueued songs
- [x] remove - Remove a song from the queue
- [x] resume - Resumes the music
- [x] search - Shows a result of songs based on the search query
- [x] seek - Seek to a position in the song
- [x] shuffle - Shuffles the queue
- [x] skip - Skip the current song
- [x] skipto - Skip to a song in the queue
- [x] stats - Get information about the bot
- [x] volume - Check or change the current volume
- [x] youtube - Starts a YouTube Together session
- [x] join - Joins the voice channel
- [x] 24/7 - Toggle 24/7 mode per server

## Looking something is missing here?
Comment below it will be here soon

## Looking to contribute?
Check out [v5 branch](https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5) there you can create a file or edit the file according to the command handler and the commands list given above

**Comment by Kakarot-0690** [comment]
gud ;-;

**Comment by SudhanPlayz** [comment]
> Best music bot I've used. I only wish there was a summon command.

Added it ![](https://cdn.discordapp.com/emojis/795762963679674369.png?size=40)

**Comment by Kakarot-0690** [comment]
> Can u add a setup command that will be lovely and add autoplay also dont worry about the load on lavalink server people host there lavalink so u dont have to worry about it and if someone has problem with it he can remove autoplay command and ik these are very big features we are asking from open source devs but u can improve urself plus u can take as much time as u want.
> 
> Quick edit on bugs: check that if someone disconnect the bot from vc without commands it dont work until u do the disconnect command of the bot and play the song again

Thank you for ur suggestion, i do agree, we could add an autoplay maybe, we dont manage lavalink servers so it wont be an issue for us but ya sounds good and yes the bot breaks when it is moved in vc or forcefully disconnected, we will work on that.

**Comment by 7qm** [comment]
> > Playnext command to play a song next in queue like -playnext "song" that's adds a song to the queue and makes it the top song in the queue, and -playnow "song" skips the current song and plays the one requested
> 
> You can just use move command. I don't think it's necessary. Adding more stuffs will slow down the bot

I believe coding it isn't so hard but it will make the bot way better

**Comment by KMPR** [comment]
> Playnext command to play a song next in queue like -playnext "song" that's adds a song to the queue and makes it the top song in the queue, and -playnow "song" skips the current song and plays the one requested

I would definitely love to see these commands added as well. Groovybot (RIP) had them as well and the people on my discord used them heavily. Also while trying out the move command to help @Nooby69 out with his issue I noticed that it is not possible to move a track to position 1. I've no idea about Javascript so I can't really check the move.js for errors but I think there may be a logic issue here:

    let dest = parseInt(args[1] - 1);
    if (dest < 1 || dest > player.queue.length - 1) {
      return client.sendTime(
        message.channel,
        "❌ | **Invalid track destination.**"
      );
    } 

If I understand the code correctly, trying to move a song to position 1 will cause `dest=0` and therefore cause the invalid track destination error message. Again, I'm not that great a coding so please bear with me.

**Comment by DarrenOfficial** [comment]
> Is there a option for music bot that it only plays song from **Spotify** and **SoundCloud** and not the **YouTube**?

There's definitely a way to only play from SoundCloud, but playing from Spotify only would be impossible cause all the bot is doing is pulling the song from Spotify then search for the equivalent on YouTube

**Comment by Nooby69** [comment]
Also, while trying out the move command to help @Nooby69 out with his issue I noticed that it is not possible to move a track to position 1. I've no idea about Javascript so I can't really check the move.js for errors but I think there may be a logic issue here:
> 
> ```
> let dest = parseInt(args[1] - 1);
> if (dest < 1 || dest > player.queue.length - 1) {
>   return client.sendTime(
>     message.channel,
>     "❌ | **Invalid track destination.**"
>   );
> } 
> ```
> 
> If I understand the code correctly, trying to move a song to position 1 will cause `dest=0` and therefore the invalid track destination error message. Again, I'm not that great at coding so please bear with me.

Ya it don't move track to position 1 that's why I was confused I hope they make it like track can go to position 1 also

**Comment by Nooby69** [comment]
> > Is there a option for music bot that it only plays song from **Spotify** and **SoundCloud** and not the **YouTube**?
> 
> There's definitely a way to only play from SoundCloud, but playing from Spotify only would be impossible cause all the bot is doing is pulling the song from Spotify then search for the equivalent on YouTube

Ok

**Comment by Teja-12** [comment]
24/7 cmd with db?

**Comment by Kakarot-0690** [comment]
> > 24/7 cmd with db?
> 
> wut, why would it need db lol just a simple toggle command would work
😏

**Comment by possyeater** [comment]
> > > Best music bot I've used. I only wish there was a summon command.
> > 
> > 
> > Added it ![](https://camo.githubusercontent.com/e347e19958308f267482af8f7704a76f17dce81d9a89d2c96123882522d93d1d/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3739353736323936333637393637343336392e706e673f73697a653d3430)
> 
> Very cool, I assume it will come with v5?

finding lavalink hosting is hard you should make a tutorial on that

**Comment by FreshImmuc** [comment]
> > > > Best music bot I've used. I only wish there was a summon command.
> > > 
> > > 
> > > Added it ![](https://camo.githubusercontent.com/e347e19958308f267482af8f7704a76f17dce81d9a89d2c96123882522d93d1d/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3739353736323936333637393637343336392e706e673f73697a653d3430)
> > 
> > 
> > Very cool, I assume it will come with v5?
> 
> finding lavalink hosting is hard you should make a tutorial on that

just host it by yourself?

or use
lava.link:80
password: any

**Comment by JotaroKujo0525** [comment]
> > > > Best music bot I've used. I only wish there was a summon command.
> > > 
> > > 
> > > Added it ![](https://camo.githubusercontent.com/e347e19958308f267482af8f7704a76f17dce81d9a89d2c96123882522d93d1d/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3739353736323936333637393637343336392e706e673f73697a653d3430)
> > 
> > 
> > Very cool, I assume it will come with v5?
> 
> finding lavalink hosting is hard you should make a tutorial on that

I did just make 3 tutorials in the discord server ;-;, ask in the discord server not here lol

**Comment by DarrenOfficial** [comment]
> > > > Best music bot I've used. I only wish there was a summon command.
> > > 
> > > 
> > > Added it ![](https://camo.githubusercontent.com/e347e19958308f267482af8f7704a76f17dce81d9a89d2c96123882522d93d1d/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3739353736323936333637393637343336392e706e673f73697a653d3430)
> > 
> > 
> > Very cool, I assume it will come with v5?
> 
> finding lavalink hosting is hard you should make a tutorial on that

Yes I agree, it’s very hard to google “free lavalink server hosting” and it’s very hard to find this https://lavalink-list.darrennathanael.com/

**Comment by kotru21** [comment]
> > > > Best music bot I've used. I only wish there was a summon command.
> > > 
> > > 
> > > Added it ![](https://camo.githubusercontent.com/e347e19958308f267482af8f7704a76f17dce81d9a89d2c96123882522d93d1d/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3739353736323936333637393637343336392e706e673f73697a653d3430)
> > 
> > Very cool, I assume it will come with v5?
> 
> finding lavalink hosting is hard you should make a tutorial on that

If you want to host lavalink on replit you can use this:
Just check the readme before using
https://github.com/kagchi/lavalink-repl

**Comment by t3rry327** [comment]
Command to change status of the bot
like: !setstatus ONLINE/IDLE/DND PLAYING/LISTENING/STREAMING/WATCHING [name of the stream - app - or music]

Command to change bot's avatar
like: !setavatar [LINK]

maybe save te queue after reboot [rarely necessary (but necessary)]

**Comment by FreshImmuc** [comment]
> Command to change status of the bot like: !setstatus ONLINE/IDLE/DND PLAYING/LISTENING/STREAMING/WATCHING [name of the stream - app - or music]
> 
> Command to change bot's avatar like: !setavatar [LINK]
> 
> maybe save te queue after reboot [rarely necessary (but necessary)]

Avatar can't be changed by the bot itself and the Status is literally in the config

**Comment by DarrenOfficial** [comment]
> Command to change status of the bot like: !setstatus ONLINE/IDLE/DND PLAYING/LISTENING/STREAMING/WATCHING [name of the stream - app - or music]
> Command to change bot's avatar like: !setavatar [LINK]


This is unnecessary

**Comment by Crni39** [comment]
> > Command to change status of the bot like: !setstatus ONLINE/IDLE/DND PLAYING/LISTENING/STREAMING/WATCHING [name of the stream - app - or music]
> > 
> > Command to change bot's avatar like: !setavatar [LINK]
> > 
> > maybe save te queue after reboot [rarely necessary (but necessary)]
> 
> Avatar can't be changed by the bot itself and the Status is literally in the config

It can be lol, [docs](https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setAvatar).

```js
ClientUser.setAvatar()
```

**Comment by FreshImmuc** [comment]
> > > Command to change status of the bot like: !setstatus ONLINE/IDLE/DND PLAYING/LISTENING/STREAMING/WATCHING [name of the stream - app - or music]
> > > Command to change bot's avatar like: !setavatar [LINK]
> > > maybe save te queue after reboot [rarely necessary (but necessary)]
> > 
> > 
> > Avatar can't be changed by the bot itself and the Status is literally in the config
> 
> It can be lol, [docs](https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setAvatar).
> 
> ```js
> ClientUser.setAvatar()
> ```

Oh lol didn't know that but I mean you can do this easiöy in the dev dashboard so there is no point of adding that.

**Comment by carlos-lr** [comment]
8d command please, it is the best filter for a music bot, please add it

**Comment by JotaroKujo0525** [comment]
> 8d command please, it is the best filter for a music bot, please add it

<img src="https://user-images.githubusercontent.com/55418697/137898896-2119fb65-7fc3-44ce-a76a-c3319ac4e16a.png">

**Comment by cowhead2000** [comment]
Will the bot support spotify? :o

**Comment by JotaroKujo0525** [comment]
> Will the bot support spotify? :o

Always has been

**Comment by cowhead2000** [comment]
> > Will the bot support spotify? :o
> 
> Always has been

Ty for replaying so fast. If you query a song from spotify with the /play command, the bot will crash, hence the asking ^^

**Comment by JotaroKujo0525** [comment]
> > > Will the bot support spotify? :o
> > 
> > 
> > Always has been
> 
> Ty for replaying so fast. If you query a song from spotify with the /play command, the bot will crash, hence the asking ^^

Ask in the discord server, the link is in the README.md

**Comment by Nooby69** [comment]
> > Is there a option for music bot that it only plays song from **Spotify** and **SoundCloud** and not the **YouTube**?
> 
> There's definitely a way to only play from SoundCloud, but playing from Spotify only would be impossible cause all the bot is doing is pulling the song from Spotify then search for the equivalent on YouTube

Can u tell me how to make the bot don't play songs from **YouTube** and only from **Spotify** & **SoundCloud**

**Comment by DarrenOfficial** [comment]
> Can u tell me how to make the bot don't play songs from **YouTube** and only from **Spotify** & **SoundCloud**

Just do `scsearch:` instead of `ytsearch:` when you do play, and also you can’t play from spotify because it has a strict drm

**Comment by DarrenOfficial** [comment]
also disable youtube search and play on your lavalink config

**Comment by priyam1234-spec** [comment]
new filters?

**Comment by SudhanPlayz** [comment]
> new filters?

go code and make pr

**Comment by patipakdeeying** [comment]
can you please add autoplay command that autoplay related music from youtube when no one add song to queue ?

**Comment by DarrenOfficial** [comment]
added filters instead of bassboost cause y not

**Comment by SoulHunter287** [comment]
> added filters instead of bassboost cause y not

Yea 😅

**Comment by FlyingndCoding** [comment]
Nice

**Comment by testbot-github** [comment]
Almost done 😮

**Comment by DarrenOfficial** [comment]
ask @SudhanPlayz to finish, me touching grass rn

**Comment by DarrenOfficial** [comment]
Handcam one of touching grass
![handone](https://cdn.darrennathanael.com/assets/grass/IMG_0571.jpeg)
me with briefcase touching grass
![full body](https://cdn.darrennathanael.com/assets/grass/IMG_0572.jpeg)

**Comment by JotaroKujo0525** [comment]
Wow, Darren touching grass

**Comment by DarrenOfficial** [comment]
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by SudhanPlayz** [comment]
> reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

E

**Comment by urbels** [comment]
touching fireworks

**Comment by JH21-22** [comment]
touching kids

**Comment by Klish132** [comment]
> touching kids

🤨

**Comment by testbot-github** [comment]
@DarrenOfficial https://github.com/SudhanPlayz/Discord-MusicBot/issues/508#issuecomment-972840354

Can u add that to readme.md?

**Comment by Nishikyso** [comment]
Hey! Hi, I have a problem, idk if this is the best site for comment this (sorry).
I did the bot like a video explain how to do it and it work good just one time haha I put a song, the first one, and the bot just connected into channel and it play the song. The second song I put was a yt link, the bot play it but nothing was sounding... after 10s writed the msg "The queue has ended" :( I tried with another songs (titles and links) but the problem happens again
Sorry if my English is not good, and sorry again if this site is not the best for comment a problem!! Have a good week! :)

**Comment by JotaroKujo0525** [comment]
> Hey! Hi, I have a problem, idk if this is the best site for comment this (sorry). I did the bot like a video explain how to do it and it work good just one time haha I put a song, the first one, and the bot just connected into channel and it play the song. The second song I put was a yt link, the bot play it but nothing was sounding... after 10s writed the msg "The queue has ended" :( I tried with another songs (titles and links) but the problem happens again Sorry if my English is not good, and sorry again if this site is not the best for comment a problem!! Have a good week! :)

Ask in the support serve or create an issue

**Comment by testbot-github** [comment]
Lets goo, all are done :)

**Comment by XstreamSpeed** [comment]
> > it will be nice if you can add autoplay command
> > Since many bots lock this feature behind paywalls :D
> 
> they say that it will be too much of load on lavalink server to keep accessing the api and give us the most appropriate song on the basis of the song which was being played. They said they will look into this in the future but not in v5

I mean if you have a good lavalink server you could do it, there could be another scope in config.js where it can be toggled on or off.

**Comment by Nooby69** [comment]
> > > it will be nice if you can add autoplay command
> > > Since many bots lock this feature behind paywalls :D
> > 
> > 
> > they say that it will be too much of load on lavalink server to keep accessing the api and give us the most appropriate song on the basis of the song which was being played. They said they will look into this in the future but not in v5
> 
> I mean if you have a good lavalink server you could do it, there could be another scope in config.js where it can be toggled on or off.

Finally....
Well ur late
