### ISSUE TITLE
Play command not working

### ISSUE THREAD

**Issue by AyeeItzLuke** [SudhanPlayz/Discord-MusicBot#52]
**Describe the bug**
Whenever you try to play anything with the bot it joins then leaves and displays **An unexpected error has occurred.**

**To Reproduce**
1. Clone the repository
2. Edit the config and rename to .env
3. use the install script
4. run the bot
5. try the play command

**Expected behavior**
I expected the bot to play the music as usual.

**Screenshots**
https://cdn.discordapp.com/attachments/765199759228928010/781473494096674826/unknown.png
https://cdn.discordapp.com/attachments/765199759228928010/781473559905566721/unknown.png
https://cdn.discordapp.com/attachments/765199759228928010/781473691690336276/unknown.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 87.0.4280.66

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS14.0
 - Browser Safari

**Additional context**
I moved over from the old version of the bot since I was having the same issues with the play command.

**Comment by Colonel-Ltd** [comment]
Is it with all songs? Or with a specific song, the message appears to prevent your bot from failing.

**Comment by AyeeItzLuke** [comment]
> Is it with all songs? Or with a specific song, the message appears to prevent your bot from failing.

Yeah it's with all songs

**Comment by Colonel-Ltd** [comment]
> > Is it with all songs? Or with a specific song, the message appears to prevent your bot from failing.
> 
> Yeah it's with all songs
The command updated to show the cause of the error, Please Update it and try again. Send a screenshot to output

**Comment by AyeeItzLuke** [comment]
I just updated it and it's showing an error about video metadata
https://cdn.discordapp.com/attachments/765199759228928010/781495450716340254/unknown.png

**Comment by Colonel-Ltd** [comment]
Update packages:

 "ytdl-core": "^4.0.0",
"@discordjs/opus": "^0.3.3"

 Tell me if it doesn't work

**Comment by Colonel-Ltd** [comment]
Also i need the url/name  you trying to play.

**Comment by AyeeItzLuke** [comment]
Unfortunately, it didn't work and I've been using Valerie as the general test song.
https://cdn.discordapp.com/attachments/765199759228928010/781505558125477898/unknown.png

**Comment by Colonel-Ltd** [comment]
Come to our server discord .. i waiting you

**Comment by Colonel-Ltd** [comment]
https://discord.com/invite/a9SHDpD
