### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by JanjyTapYT** [SudhanPlayz/Discord-MusicBot#535]
Branch: Default 

I tryed all but its still not working when i go on the website and click on dashboard then it Gives me this error: 
![Screenshot_20211031-172604_Chrome](https://user-images.githubusercontent.com/81481526/139593332-d56b38be-fdb2-4916-b6d6-a3057a63fbf8.jpg)
I dont know how I can fix this can someone please help me 

Note: I have as redirect on discord developer [my domain]/api/callback and in the botconfig.js file too

**Comment by Crni39** [comment]
> Branch: Default
> 
> I tryed all but its still not working when i go on the website and click on dashboard then it Gives me this error: ![Screenshot_20211031-172604_Chrome](https://user-images.githubusercontent.com/81481526/139593332-d56b38be-fdb2-4916-b6d6-a3057a63fbf8.jpg) I dont know how I can fix this can someone please help me
> 
> Note: I have as redirect on discord developer [my domain]/api/callback and in the botconfig.js file too

can you send screenshots of both? blur url if you want

**Comment by JotaroKujo0525** [comment]
> Branch: Default
> 
> I tryed all but its still not working when i go on the website and click on dashboard then it Gives me this error: ![Screenshot_20211031-172604_Chrome](https://user-images.githubusercontent.com/81481526/139593332-d56b38be-fdb2-4916-b6d6-a3057a63fbf8.jpg) I dont know how I can fix this can someone please help me
> 
> Note: I have as redirect on discord developer [my domain]/api/callback and in the botconfig.js file too

Hi, see if you did all of this
1. You didn't put the redirect uris in https://discord.com/developers/applications.
2. You didn't put the right website in line 20 of botconfig.js
3. You didn't put `/api/callback` in the `CallbackUrl` part in botconfig.js.

See if you did all of this but I suspect you changed the callback url in botconfig.js. Please be advised you only put the website name in botconfig.js (line 20)

**Comment by JotaroKujo0525** [comment]
And also please be informed that this is **NOT** a bug, you just configured it not correctly.

**Comment by JanjyTapYT** [comment]
I'll checked I filled out all correctly but its still not working

**Comment by JotaroKujo0525** [comment]
> I'll checked I filled out all correctly but its still not working

Please screen host the CallbackUrl in botconfig.js

**Comment by JotaroKujo0525** [comment]
![Screenshot_20211102_055636](https://user-images.githubusercontent.com/77835007/139747423-9b56d16f-7835-4ce8-b932-88e9783d7836.jpg)
This shouldnt be touched
