### ISSUE TITLE
Moving bot to another channel breaks functionality.

### ISSUE THREAD

**Issue by Xiragi** [SudhanPlayz/Discord-MusicBot#536]
**Please describe the problem you are having in as much detail as possible:**

Moving the bot to a new channel then joining that channel will not resume/play/continue music. Attempting to type !resume will say that you need to be in the same voice channel.

:x: | You must be in the same voice channel as me to use this command!

**Further details:**

- discord.js version:12.5.3
- Node.js version: v14.18.1
- Operating system: Ubuntu 20.04
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Comment by DarrenOfficial** [comment]
It will be fixed in v5, it's known as a bug, moving, disconnecting, deafening the bot will break it, so yeah don't do it until it's fixed
