### ISSUE TITLE
Crashing on invalid message request.

### ISSUE THREAD

**Issue by Aspect0002** [SudhanPlayz/Discord-MusicBot#543]
**If i play music and i delete the messages of the bot it says unkown message then the bot crashes, so it tried to get unkown message and its exiting then**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version: 13.5.1
- Node.js version: 17.0.1
- Operating system: Windows,Linux

**Comment by JotaroKujo0525** [comment]
Wait a minute, are you using v5 code?

**Comment by DarrenOfficial** [comment]
Which branch are you using?

**Comment by Aspect0002** [comment]
> Wait a minute, are you using v5 code?

oh, i don’t use newest I try later if I am on pc with newest one ._.

**Comment by SudhanPlayz** [comment]
> > Wait a minute, are you using v5 code?
> 
> oh, i don’t use newest I try later if I am on pc with newest one ._.

Reopen this issue once you try
