### ISSUE TITLE
[Feature Request] Support for YouTube Chapter as playlist

### ISSUE THREAD

**Issue by c3n21** [SudhanPlayz/Discord-MusicBot#550]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Describe the ideal solution**
Right now when you play a YouTube video with chapter it will played as a single video and you can't skip to a video's chapter (as far as I can see from the command menu of the bot and tested so far).

**Describe alternatives you've considered**
It would be nice to support YouTube chapters as lots of music videos on YouTube are single video playlists but support chapters for easy navigation like in a real playlist, i.e. [this](https://www.youtube.com/watch?v=IEQDvaXBxp8). It could be also handy to have the possibility to add YouTube chapters manually using a similar format **hh::mm:ss <name>** since some videos don't provide chapters but are still available in the comments section.

**Additional context**

**Comment by JotaroKujo0525** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]
> 
> **Describe the ideal solution** Right now when you play a YouTube video with chapter it will played as a single video and you can't skip to a video's chapter (as far as I can see from the command menu of the bot and tested so far).
> 
> **Describe alternatives you've considered** It would be nice to support YouTube chapters as lots of music videos on YouTube are single video playlists but support chapters for easy navigation like in a real playlist, i.e. [this](https://www.youtube.com/watch?v=IEQDvaXBxp8). It could be also handy to have the possibility to add YouTube chapters manually using a similar format **hh::mm:ss ** since some videos don't provide chapters but are still available in the comments section.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

I don't think that's a thing with erela.js lol

**Comment by JotaroKujo0525** [comment]
If there is, let us know
