### ISSUE TITLE
Show artist name in now playing when song is requested with Spotify link

### ISSUE THREAD

**Issue by jvgoch** [SudhanPlayz/Discord-MusicBot#554]
**Is your feature request related to a problem? Please describe.**
The now playing message only shows the song name and not the artist. Not a problem per say but more of an inconvenience.

**Describe the ideal solution**
Now playing:
Artist name - Song name

**Describe alternatives you've considered**
When you request trough YouTube sometimes the artist is in the title, then it does show in the now playing message.

**Additional context**

**Comment by DarrenOfficial** [comment]
will be added in v5.
