### ISSUE TITLE
Lavalink.

### ISSUE THREAD

**Issue by Aspect0002** [SudhanPlayz/Discord-MusicBot#556]
**Please describe the problem you are having in as much detail as possible:**
After some time like 2days or sometimes one day it says lavalink not connected same on repl.it.

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 17.0.1
- Operating system: Linux

**Comment by JotaroKujo0525** [comment]
Just get a stable lavalink bruh ;-;

**Comment by JotaroKujo0525** [comment]
And why did you put bug on this?
