### ISSUE TITLE
Lavalink node

### ISSUE THREAD

**Issue by NONPLAYT** [SudhanPlayz/Discord-MusicBot#557]
**Please describe the problem you are having in as much detail as possible:**
The bot just works, but after a while the lavalink node turns itself off, although everything works stably
Help please

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 14.18.1
- Operating system: Heroku
- Priority this issue should have – please be realistic and elaborate if possible: minimum

**Relevant client options:**

- partials: none
- gateway intents: all turned on
- other: none

**Comment by captainion2119** [comment]
damn, bruv imma be honest, dev to dev, u prolly might wanna check on the lavalink node, or see if ur heroku is on 24/7

it aint a problem on the bot's end, so they closed the ticket. but yeh

felt bad xd
