### ISSUE TITLE
Repl.it

### ISSUE THREAD

**Issue by MEZBATHEKING** [SudhanPlayz/Discord-MusicBot#567]
client.build is not a function showing in repl.it console

**Comment by JotaroKujo0525** [comment]
Means you didn't fill out all of botconfig.js. Ask in the discord server first. And mostly, this is not a bug, it's just you did something wrong

**Comment by JotaroKujo0525** [comment]
> Means you didn't fill out all of botconfig.js. Ask in the discord server first. And mostly, this is not a bug, it's just you did something wrong

Double check the contents if it's all filled out.

**Comment by DarrenOfficial** [comment]
@MEZBATHEKING reopen if the issue still happens.
