### ISSUE TITLE
Callback dont work

### ISSUE THREAD

**Issue by JanjyTapYT** [SudhanPlayz/Discord-MusicBot#568]
Hello, I configured all in botconfig.js but when I go on the website and I click on dashboard then the site tells me that: 
![Screenshot_20211119-103444_Chrome](https://user-images.githubusercontent.com/81481526/142600412-c4d78934-13cc-42a9-a694-64db4551abef.jpg)

Information: 
• Im using replit
• i filled out all in the botconfig.js file and on the discord developer forum
• Branche: Default

**Comment by JotaroKujo0525** [comment]
Ask in the discord server for more elaboration

**Comment by DarrenOfficial** [comment]
send a screenshot of your botconfig

**Comment by DarrenOfficial** [comment]
;-;
