### ISSUE TITLE
Bot not rejoining vc after manual disconnect

### ISSUE THREAD

**Issue by lolpoe** [SudhanPlayz/Discord-MusicBot#577]
https://user-images.githubusercontent.com/93990656/142730529-26fc1502-32d1-4942-a3c9-6ae11fa8e7dc.mp4

Looks like voiceStateUpdate.js event is the culprit. 
It acts as if the bot is still in vc and works fine if you type [p]disconnect then [p]play again.

**Comment by JotaroKujo0525** [comment]
> ww4gXY1vos.mp4 
> Looks like voiceStateUpdate.js event is the culprit. It acts as if the bot is still in vc and works fine if you type [p]disconnect then [p]play again.

It's a known issue, refer to this [issue](https://github.com/SudhanPlayz/Discord-MusicBot/issues/536) before
