### ISSUE TITLE
bump command with text instead of number crashes bot

### ISSUE THREAD

**Issue by urbels** [SudhanPlayz/Discord-MusicBot#578]
Any text in command "!bump some random text" crashes the bot.

Also one other issue suggestest to remove it because !move exists. If you remove it maybe you cant add !playtop (!pt) or something like it to add song at the top. Would save time.

**Comment by JotaroKujo0525** [comment]
You know that `bump` requires number right?

**Comment by urbels** [comment]
> You know that `bump` requires number right? not text

I know but people who dont crashed bot 2 times. :D One was accident using !bump and spotify link.

Also why close actual issue?

**Comment by DarrenOfficial** [comment]
> > You know that `bump` requires number right? not text
> 
> I know but people who dont crashed bot 2 times. :D One was accident using !bump and spotify link.
> 
> Also why close actual issue?

Because we already know about this issue, thats why on v4.1.2 (latest release) we disabled it.

We’re gonna fix this issue on v5 release.

**Comment by urbels** [comment]
Ok thank you for clarification!
