### ISSUE TITLE
TypeError: client.build is not a function

### ISSUE THREAD

**Issue by AceKiller250** [SudhanPlayz/Discord-MusicBot#580]
**Please describe the problem you are having in as much detail as possible:**
21.11 02:23:42 [Bot] /index.js:5
21.11 02:23:42 [Bot] client.build();
21.11 02:23:42 [Bot] ^
21.11 02:23:42 [Bot] TypeError: client.build is not a function
21.11 02:23:42 [Bot] at Object.<anonymous> (/index.js:5:8)
21.11 02:23:42 [Bot] at Module._compile (node:internal/modules/cjs/loader:1095:14)
21.11 02:23:42 [Bot] at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
21.11 02:23:42 [Bot] at Module.load (node:internal/modules/cjs/loader:975:32)
21.11 02:23:42 [Bot] at Function.Module._load (node:internal/modules/cjs/loader:816:12)
21.11 02:23:42 [Bot] at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
21.11 02:23:42 [Bot] at node:internal/main/run_main_module:17:47
**Include a reproducible code sample here, if possible:**

```js
// Place your code here
const DiscordMusicBot = require("./structures/DiscordMusicBot");

const client = new DiscordMusicBot();

client.build();

module.exports = client; //;-;

```

**Further details:**

- discord.js version:
- Node.js version: 16.6.9
- Operating system: Hosting service so I don't know
- Priority this issue should have – please be realistic and elaborate if possible: 2/5 May happen to other people

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by SudhanPlayz** [comment]
Fill up your `botconfig.js`. Make sure you filled up every details. If this not helped join our support server and ask for help instead of creating or re-opening the issue
