### ISSUE TITLE
wrong url

### ISSUE THREAD

**Issue by Tuurkevg** [SudhanPlayz/Discord-MusicBot#582]
![afbeelding](https://user-images.githubusercontent.com/77327545/143280271-10d78d64-8bfa-44af-9049-6090c14239ca.png)
error when starting the bot could you help me?

**Comment by Vretu-Dev** [comment]
You must install discord.js
Command
`npm install discord.js`

**Comment by DarrenOfficial** [comment]
> You must install discord.js
> Command
> `npm install discord.js`

False

**Comment by DarrenOfficial** [comment]
> ![afbeelding](https://user-images.githubusercontent.com/77327545/143280271-10d78d64-8bfa-44af-9049-6090c14239ca.png)
> error when starting the bot could you help me?

You need to enter lavalink details in botconfig.js

**Comment by DarrenOfficial** [comment]
you can check this for public lavalink https://lavalink-list.darrennathanael.com/
or you can self host lavalink yourself https://github.com/freyacodes/Lavalink

**Comment by Tuurkevg** [comment]
> 
![afbeelding](https://user-images.githubusercontent.com/77327545/143299989-99e6da2d-71c3-4e22-903e-82320d3e294c.png)
![afbeelding](https://user-images.githubusercontent.com/77327545/143300018-a2d4a723-6bfa-4b27-bbd3-3180d1bea216.png)

i followed what you day and I get the same error
i take a server without ssl and with ssl they are both broken

**Comment by DarrenOfficial** [comment]
> ![afbeelding](https://user-images.githubusercontent.com/77327545/143299989-99e6da2d-71c3-4e22-903e-82320d3e294c.png)

This is a permissions issue
If you got an error in your console that says `DiscordAPIError: Missing Access`, this means the bot does not have the proper permissions.  
  Use this link below to re-invite it with the proper perms -
**https://discord.com/oauth2/authorize?client_id=CLIENT_ID&permissions=2205281600&scope=bot%20applications.commands**
• CLIENT_ID needs to be replaced with your bot Id
• Permission calculator: [learn more](https://finitereality.github.io/permissions-calculator)
• You can use #generateInvite instead: [learn more](https://discord.js.org/#/docs/main/main/class/Client?scrollTo=generateInvite)
**If you re-invited the bot and your console still shows `DiscordAPIError: Missing Access`, then your bot is in a server you don't have access to so you can't fix it.**
Make sure you **restart** your bot so it knows it has the correct permissions.

**Comment by DarrenOfficial** [comment]
next time read the error first.

**Comment by DarrenOfficial** [comment]
Re open if there’s another issues.
