### ISSUE TITLE
Info: [Slash Command]: [POST-FAILED]

### ISSUE THREAD

**Issue by Vretu-Dev** [SudhanPlayz/Discord-MusicBot#583]
Hey, I have problem. Bot is working but in console dispaly this.
```
24:10:2021 - 18:49 | Info: [Slash Command]: [POST-FAILED] Guild 519482843810758677, Command:
 bassboost                                                                                  
DiscordAPIError: Missing Access                                                             
    at RequestHandler.execute (/home/Discord-MusicBot/node_modules/discord.js/src/rest/Reque
stHandler.js:154:13)                                                                        
    at processTicksAndRejections (node:internal/process/task_queues:96:5)                   
    at async RequestHandler.push (/home/Discord-MusicBot/node_modules/discord.js/src/rest/Re
questHandler.js:39:14)                                                                      
    at async /home/Discord-MusicBot/util/Register
![Zrzut ekranu 2021-11-24 184932]
SlashCommands.js:36:9 {                    
  method: 'post',                                                                           
  path: '/applications/887753067020288050/guilds/519482843810758677/commands',              
  code: 50001,                                                                              
  httpStatus: 403                                                                           
}      
```
This is slash command discord, could i disable this?
![Zrzut ekranu 2021-11-24 184932](https://user-images.githubusercontent.com/82831707/143291540-69448cb8-de5e-46c7-aa04-6ed16b93d2aa.png)

**Comment by DarrenOfficial** [comment]
Not a bug.

**Comment by DarrenOfficial** [comment]
If you got an error in your console that says `DiscordAPIError: Missing Access`, this means the bot does not have the proper permissions.  
  Use this link below to re-invite it with the proper perms -
**https://discord.com/oauth2/authorize?client_id=CLIENT_ID&permissions=2205281600&scope=bot%20applications.commands**
• CLIENT_ID needs to be replaced with your bot Id
• Permission calculator: [learn more](https://finitereality.github.io/permissions-calculator)
• You can use #generateInvite instead: [learn more](https://discord.js.org/#/docs/main/main/class/Client?scrollTo=generateInvite)
**If you re-invited the bot and your console still shows `DiscordAPIError: Missing Access`, then your bot is in a server you don't have access to so you can't fix it.**
Make sure you **restart** your bot so it knows it has the correct permissions.
