### ISSUE TITLE
Crash/Shutting down after taking all permissions bot

### ISSUE THREAD

**Issue by Vretu-Dev** [SudhanPlayz/Discord-MusicBot#584]
Hello. I found a rather serious error. When we, as the owner of the server, take away all permissions from the bot and disable the text channel permissions to send messages and enter a command the bot crashes
![Zrzut ekranu 2021-11-25 092154](https://user-images.githubusercontent.com/82831707/143405282-adda4834-b43c-4ecb-a7b8-d8f88bfa0364.png)

**Comment by Vretu-Dev** [comment]
![image](https://user-images.githubusercontent.com/82831707/143406625-7ba2c6de-f882-4e27-ab43-1531f6fffeb5.png)

**Comment by axmyo** [comment]
The bot does not have permissions to send messages as you've taken the permission from everyone.. Even the bot.

**Comment by Vretu-Dev** [comment]
Yeah, I know about that. But it drives the bot to crash. So someone can crash my bot

**Comment by Nyxou-Kurpo** [comment]
I also have a problem with the permissions with the slash commands

**Comment by Nyxou-Kurpo** [comment]
![Uploading Screenshot_2021_1125_120511.jpg…]()

**Comment by JotaroKujo0525** [comment]
> This is permission for @everyone in this text channel. The bot has no permissions in this case so it takes over from @everyone ![image](https://user-images.githubusercontent.com/82831707/143406625-7ba2c6de-f882-4e27-ab43-1531f6fffeb5.png)

Give it a role that has send messages perms. The problem is the bot can detect that channel but can't send messages returning to a crash.

**Comment by Vretu-Dev** [comment]
> > This is permission for @everyone in this text channel. The bot has no permissions in this case so it takes over from @everyone ![image](https://user-images.githubusercontent.com/82831707/143406625-7ba2c6de-f882-4e27-ab43-1531f6fffeb5.png)
> 
> Give it a role that has send messages perms. The problem is the bot can detect that channel but can't send messages returning to a crash.

Yes but this Shutting down bot! It's dangerous

**Comment by Vretu-Dev** [comment]
I know that in order for it to work you need to give the bot permissions to work. Ake the point here is that potential users can shut it down like this
