### ISSUE TITLE
Add Discord Music Bot v5 on Docker Hub

### ISSUE THREAD

**Issue by Vretu-Dev** [SudhanPlayz/Discord-MusicBot#586]
Maybe in Discord Music Bot v5  add container image on docker hub.
This will make it easier to set up and run the bot

**Comment by DarrenOfficial** [comment]
This will be unnecessary, docker compose works fine.

**Comment by jvgoch** [comment]
This would actually quite useful for people running unRAID, since unRAID doesn't have an easy to run docker compose.
