### ISSUE TITLE
Playlist cmd dosen't works 

### ISSUE THREAD

**Issue by AkshatNoobProMax** [SudhanPlayz/Discord-MusicBot#59]
**Playlist not found.**

Whenever a playlist name or link is used with playlist cmd , it dosen't works and bot shows the message" Playlist not found ".

**Comment by Colonel-Ltd** [comment]
Please provide more information, which id of playlist are you trying to get?

**Comment by Colonel-Ltd** [comment]
Updated, feel free to re open if u have any issues
