### ISSUE TITLE
Lavalink node not connected 

### ISSUE THREAD

**Issue by AceKiller250** [SudhanPlayz/Discord-MusicBot#590]
Lavalink keeps disconnecting and the bot ends up saying "Lavalink node not connected". It fixes when I restart the bot but I don't want to keep restarting it as this happens every few hours.

```js
30:10:2021 - 13:47 | Info: Lavalink: Node Main connected
30:10:2021 - 13:50 | Info: Lavalink: Node Main had an error: Client network socket disconnected before secure TLS connection was established
30:10:2021 - 13:50 | Info: Lavalink: Node Main had an error: Client network socket disconnected before secure TLS connection was established
30:10:2021 - 13:51 | Info: Lavalink: Node Main had an error: Client network socket disconnected before secure TLS connection was established
30:10:2021 - 13:51 | Info: Lavalink: Node Main had an error: Unable to connect after 5 attempts.
```

**Further details:**

- discord.js version:
- latest
- Node.js version:
- 16
- Operating system:
- Linux hosting service
- Priority this issue should have – please be realistic and elaborate if possible:
Medium as this prevents the whole bot from working.
**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by JotaroKujo0525** [comment]
> Lavalink keeps disconnecting and the bot ends up saying "Lavalink node not connected". It fixes when I restart the bot but I don't want to keep restarting it as this happens every few hours.
> 
> ```js
> 30:10:2021 - 13:47 | Info: Lavalink: Node Main connected
> 30:10:2021 - 13:50 | Info: Lavalink: Node Main had an error: Client network socket disconnected before secure TLS connection was established
> 30:10:2021 - 13:50 | Info: Lavalink: Node Main had an error: Client network socket disconnected before secure TLS connection was established
> 30:10:2021 - 13:51 | Info: Lavalink: Node Main had an error: Client network socket disconnected before secure TLS connection was established
> 30:10:2021 - 13:51 | Info: Lavalink: Node Main had an error: Unable to connect after 5 attempts.
> ```
> 
> **Further details:**
> 
> * discord.js version:
> * latest
> * Node.js version:
> * 16
> * Operating system:
> * Linux hosting service
> * Priority this issue should have – please be realistic and elaborate if possible:
>   Medium as this prevents the whole bot from working.
>   **Relevant client options:**
> * partials: none
> * gateway intents: none
> * other: none

Find lavalinks [here](https://lavalink-list.darrennathanael.com)

**Comment by JotaroKujo0525** [comment]
Can somebody uh, close this issue

**Comment by DarrenOfficial** [comment]
done :)
