### ISSUE TITLE
Discord-MusicBot - LavaLink Issue

### ISSUE THREAD

**Issue by LightyCat** [SudhanPlayz/Discord-MusicBot#602]
When i run the bot
1st. The Slash Commands doesn't works and gives SO MANY ERRORS 
2th. Sometimes The lavalink Disconnects and i have to RESTART it
3th. Sometimes the bot becomes SO SLOW and Please try to make it faster somehow with the code

**Comment by QuintenQVD0** [comment]
you have any screens to prove that or a error log it all works fine for me

**Comment by kotru21** [comment]
Lavalink can be disconnected because of heavy load on lavalink server.
You can find other public lavalinks here: https://lavalink-list.darrennathanael.com
Or host your own(you can use this if you like to host your lavalink on replit: https://github.com/kagchi/lavalink-repl )

**Comment by JotaroKujo0525** [comment]
> When i run the bot 1st. The Slash Commands doesn't works and gives SO MANY ERRORS 2th. Sometimes The lavalink Disconnects and i have to RESTART it 3th. Sometimes the bot becomes SO SLOW and Please try to make it faster somehow with the code

1) That's so easy to fix. You just don't know how to do it.
2) Get a better lavalink
3) Get a better host.

**Comment by JotaroKujo0525** [comment]
Why did you label this as a bug

**Comment by DarrenOfficial** [comment]
This is an example of user error, yet blaming it on the code.
