### ISSUE TITLE
client.build is not a function

### ISSUE THREAD

**Issue by KasaiKonoru** [SudhanPlayz/Discord-MusicBot#605]
after starting index.js

**Comment by QuintenQVD0** [comment]
client.build
If you get an error in your console that says TypeError: client.build is not a Function, this isn't the best error to get. (not saying any error is good)

Well at first, congratulations on picking the lucky card.

This issue does not happen often.

MAKE SURE YOUR BOT'S CONFIG IS COMPLETELY FILLED OUT. NOTHING CAN BE BLANK.

If your botconfig is completely filled out and it still causes the same error, make a new project.

If you need further help, don't hesitate to let us know!

**Comment by DarrenOfficial** [comment]
🙏🏼
