### ISSUE TITLE
Stage Channel

### ISSUE THREAD

**Issue by enemyalert** [SudhanPlayz/Discord-MusicBot#608]
Isn't cool if the bot is compatible with Stage Channels 👍. I suggest if there's a text above it just like here. I highly appreciated your effort good job!
![image_2021-12-16_121721](https://user-images.githubusercontent.com/74367697/146307211-84764bba-fb9b-48b8-b05d-7df357962631.png)

**Comment by dragonfirefox** [comment]
I think they'll add StageChannel support on v5 rewrite.

**Comment by DarrenOfficial** [comment]
Use v5 branch.
