### ISSUE TITLE
Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by bossWither** [SudhanPlayz/Discord-MusicBot#62]
Hello! I have been using this discord bot script! It was working, but now it has one issue. 
![изображение](https://user-images.githubusercontent.com/75183579/100772921-e4ec3480-3408-11eb-9e57-84f60ccbd43f.png)

Please help me fix it!

**Comment by RyzenK8** [comment]
Go to the root you project and simply delete /module_nodejs. And after run « npm i » otherwise it does not work update the « package.json ».

**Comment by Colonel-Ltd** [comment]
ytdl core version?

**Comment by Colonel-Ltd** [comment]
still have problem?
