### ISSUE TITLE
Threads Support

### ISSUE THREAD

**Issue by testbot-github** [SudhanPlayz/Discord-MusicBot#624]
**Is your feature request related to a problem? Please describe.**
> Yes, People use treads to separate things like bot commands etc.

**Describe the ideal solution**
> Add threads support in v5

**Additional context**
Idea by https://github.com/SudhanPlayz/Discord-MusicBot/discussions/601

**Comment by JotaroKujo0525** [comment]
Actually this'll be added in v5, as of now the bot uses djs 12 and hence can't use newer discord features

**Comment by testbot-github** [comment]
> Actually this'll be added in v5, as of now the bot uses djs 12 and hence can't use newer discord features

That's what I told in `Describe the ideal solution` 🤣
