### ISSUE TITLE
Lyrics command

### ISSUE THREAD

**Issue by etepes** [SudhanPlayz/Discord-MusicBot#628]
**Please describe the problem you are having in as much detail as possible:**

Error in the Lyrics command, if the lyrics of the song are too long, an error will appear: DiscordAPIError: Invalid Form Body
embeds: Embed size exceeds maximum size of 6000, you need to add buttons / pages to avoid this. 

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version: 13.2.0
- Node.js version:14.x
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by DarrenOfficial** [comment]
Yes, I know about this issue. I'm just waiting for @SudhanPlayz to make the buttons' thing, because it's pretty damn complicated.

Expect it to be fixed when @SudhanPlayz finishes exam. Or when I figure out how to make buttons :pray:

**Comment by testbot-github** [comment]
> Yes, I know about this issue. I'm just waiting for @SudhanPlayz to make the buttons' thing, because it's pretty damn complicated.
> 
> Expect it to be fixed when @SudhanPlayz finishes exam. Or when I figure out how to make buttons 🙏

@SudhanPlayz and @Kakarot-0690 be like: 😞 
![image](https://user-images.githubusercontent.com/82745607/148620301-a0172c10-1e62-43e9-84ee-2be73faa2872.png)

**Comment by DarrenOfficial** [comment]
stop talking and go coding @testbot-github
