### ISSUE TITLE
24/7 uninterrupted live music what time the bot there is more ability to communicate

### ISSUE THREAD

**Issue by RyzenK8** [SudhanPlayz/Discord-MusicBot#63]
**Describe the bug**
I put music on my server with bot. NCS Music 24/7 without interruption. A few hours later there is more ability to communicate to discord and YouTube API.

**To Reproduce**
1. Start the script
2. Play the music in vocal, live without interruption
3. Wait a few hours
4. The bot unable to communicate API

**Expected behavior**
It happens after a few hours.

**Screenshots**
Unfortunately there is no screenshot there was no error message.

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Redmi Note 9]
 - OS: [Android]
 - Browser [Firefox]
 - Version [10]

**Additional context**
To fix the issue for requiring bot restart.
Exactly the music - https://youtu.be/IP0ZRj-_xG4

**Comment by Colonel-Ltd** [comment]
The connection quality will be raised in the next update, keep tuned
