### ISSUE TITLE
Slash command is not working.

### ISSUE THREAD

**Issue by iamrahul24** [SudhanPlayz/Discord-MusicBot#630]
**Please describe the problem you are having in as much detail as possible:
I followed the whole tutorial and I am able to use the bot I created but I cant see a single /commands.**

**DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/928567641621282876/guilds/543679808249528333/commands',
  code: 50001,
  httpStatus: 403
}
7:0:2022 - 13:28 | Info: [Slash Command]: [POST-FAILED] Guild 543679808249528333, Command: bump
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/928567641621282876/guilds/543679808249528333/commands',
  code: 50001,
  httpStatus: 403
}
7:0:2022 - 13:28 | Info: [Slash Command]: [POST-FAILED] Guild 543679808249528333, Command: clear
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/928567641621282876/guilds/543679808249528333/commands',
  code: 50001,
  httpStatus: 403
}
7:0:2022 - 13:28 | Info: [Slash Command]: [POST-FAILED] Guild 543679808249528333, Command: config
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/928567641621282876/guilds/543679808249528333/commands',
  code: 50001,
  httpStatus: 403
}
7:0:2022 - 13:28 | Info: [Slash Command]: [POST-FAILED] Guild 543679808249528333, Command: disconnect
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/928567641621282876/guilds/543679808249528333/commands',
  code: 50001,
  httpStatus: 403
}
7:0:2022 - 13:28 | Info: [Slash Command]: [POST-FAILED] Guild 543679808249528333, Command: grab
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/928567641621282876/guilds/543679808249528333/commands',
  code: 50001,
  httpStatus: 403
}
7:0:2022 - 13:28 | Info: [Slash Command]: [POST-FAILED] Guild 543679808249528333, Command: help
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/928567641621282876/guilds/543679808249528333/commands',
  code: 50001,
  httpStatus: 403
}
7:0:2022 - 13:28 | Info: [Slash Command]: [POST-FAILED] Guild 543679808249528333, Command: invite
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/928567641621282876/guilds/543679808249528333/commands',
  code: 50001,
  httpStatus: 403
}
7:0:2022 - 13:28 | Info: [Slash Command]: [POST-FAILED] Guild 543679808249528333, Command: loop
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/928567641621282876/guilds/543679808249528333/commands',
  code: 50001,
  httpStatus: 403
}
7:0:2022 - 13:28 | Info: [Slash Command]: [POST-FAILED] Guild 543679808249528333, Command: loopqueue
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Discord-MusicBot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async /home/runner/Discord-MusicBot/util/RegisterSlashCommands.js:36:9 {
  method: 'post',
  path: '/applications/928567641621282876/guilds/543679808249528333/commands',
  code: 50001,
  httpStatus: 403
}
7:0:2022 - 13:28 | Info**

```js
// Place your code here
nothing different from source code. only 
```

**Further details:**

- discord.js version: 13.5.0
- Node.js version: 17.3.0
- Operating system: linux
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by DarrenOfficial** [comment]
If you got an error in your console that says \`DiscordAPIError: Missing Access\`, this means the bot does not have the proper permissions.  
  Use this link below to re-invite it with the proper perms -
**https://discord.com/oauth2/authorize?client_id=CLIENT_ID&permissions=2205281600&scope=bot%20applications.commands**
• CLIENT_ID needs to be replaced with your bot Id
• Permission calculator: [learn more](https://finitereality.github.io/permissions-calculator)
• You can use #generateInvite instead: [learn more](https://discord.js.org/#/docs/main/main/class/Client?scrollTo=generateInvite)
**If you re-invited the bot and your console still shows \`DiscordAPIError: Missing Access\`, then your bot is in a server you don't have access to so you can't fix it.**
Make sure you **restart** your bot so it knows it has the correct permissions.

**Comment by iamrahul24** [comment]
> If you got an error in your console that says `DiscordAPIError: Missing Access`, this means the bot does not have the proper permissions. Use this link below to re-invite it with the proper perms - **https://discord.com/oauth2/authorize?client_id=CLIENT_ID&permissions=2205281600&scope=bot%20applications.commands** • CLIENT_ID needs to be replaced with your bot Id • Permission calculator: [learn more](https://finitereality.github.io/permissions-calculator) • You can use #generateInvite instead: [learn more](https://discord.js.org/#/docs/main/main/class/Client?scrollTo=generateInvite) **If you re-invited the bot and your console still shows `DiscordAPIError: Missing Access`, then your bot is in a server you don't have access to so you can't fix it.** Make sure you **restart** your bot so it knows it has the correct permissions.

thank you for help and sorry I wasted your time because later on I solved this issue on my own but now I am facing another problem where earlier commands were working fine but now it is not.

![image](https://user-images.githubusercontent.com/62786811/148578204-83a2ee09-8a33-4e90-a078-1a50b00a418b.png)

**Comment by iamrahul24** [comment]
(node:1741) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'SlashCommand' of undefined
    at WebSocketManager.<anonymous> (/home/runner/Discord-MusicBot/structures/DiscordMusicBot.js:108:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1741) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1741) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'SlashCommand' of undefined
    at WebSocketManager.<anonymous> (/home/runner/Discord-MusicBot/structures/DiscordMusicBot.js:108:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1741) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'SlashCommand' of undefined
    at WebSocketManager.<anonymous> (/home/runner/Discord-MusicBot/structures/DiscordMusicBot.js:108:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1741) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'SlashCommand' of undefined
    at WebSocketManager.<anonymous> (/home/runner/Discord-MusicBot/structures/DiscordMusicBot.js:108:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by iamrahul24** [comment]
7:0:2022 - 17:24 | Info: Web Server has been started
7:0:2022 - 17:24 | Info: Command Loaded: bassboost
7:0:2022 - 17:24 | Info: Command Loaded: bump
7:0:2022 - 17:24 | Info: Command Loaded: clear
7:0:2022 - 17:24 | Info: Command Loaded: config
7:0:2022 - 17:24 | Info: Command Loaded: disconnect
7:0:2022 - 17:24 | Info: Command Loaded: grab
7:0:2022 - 17:24 | Info: Command Loaded: help
7:0:2022 - 17:24 | Info: Command Loaded: invite
7:0:2022 - 17:24 | Info: Command Loaded: loop
7:0:2022 - 17:24 | Info: Command Loaded: loopqueue
7:0:2022 - 17:24 | Info: Command Loaded: lyrics
7:0:2022 - 17:24 | Info: Command Loaded: move
7:0:2022 - 17:24 | Info: Command Loaded: nowplaying
7:0:2022 - 17:24 | Info: Command Loaded: pause
7:0:2022 - 17:24 | Info: Command Loaded: play
7:0:2022 - 17:24 | Info: Command Loaded: queue
7:0:2022 - 17:24 | Info: Command Loaded: remove
7:0:2022 - 17:24 | Info: Command Loaded: resume
7:0:2022 - 17:24 | Info: Command Loaded: search
7:0:2022 - 17:24 | Info: Command Loaded: seek
7:0:2022 - 17:24 | Info: Command Loaded: shuffle
7:0:2022 - 17:24 | Info: Command Loaded: skip
7:0:2022 - 17:24 | Info: Command Loaded: skipto
7:0:2022 - 17:24 | Info: Command Loaded: stats
7:0:2022 - 17:24 | Info: Command Loaded: volume
7:0:2022 - 17:24 | Info: Command Loaded: youtube
7:0:2022 - 17:24 | Info: Event Loaded: guildCreate
7:0:2022 - 17:24 | Info: Event Loaded: message
7:0:2022 - 17:24 | Info: Event Loaded: raw
7:0:2022 - 17:24 | Info: Event Loaded: ready
7:0:2022 - 17:24 | Info: Event Loaded: voiceStateUpdate
7:0:2022 - 17:24 | Info: Successfully Logged in as Musician-San#4066
7:0:2022 - 17:24 | Info: Registering slash commands for 543679808249528333
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: bassboost
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: bump
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: clear
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: config
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: disconnect
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: grab
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: help
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: invite
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: loop
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: loopqueue
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: lyrics
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: move
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: nowplaying
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: pause
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: play
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: queue
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: remove
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: resume
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: search
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: shuffle
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: skip
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: skipto
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: stats
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: volume
7:0:2022 - 17:24 | Info: [Slash Command]: [POST] Guild 543679808249528333, Command: youtube
7:0:2022 - 17:24 | Info: Lavalink: Node Main had an error: getaddrinfo ENOTFOUND https
7:0:2022 - 17:25 | Info: Lavalink: Node Main had an error: getaddrinfo ENOTFOUND https
7:0:2022 - 17:25 | Info: Lavalink: Node Main had an error: getaddrinfo ENOTFOUND https
7:0:2022 - 17:26 | Info: Lavalink: Node Main had an error: getaddrinfo ENOTFOUND https
7:0:2022 - 17:26 | Info: Lavalink: Node Main had an error: getaddrinfo ENOTFOUND https
7:0:2022 - 17:27 | Info: Lavalink: Node Main had an error: Unable to connect after 5 attempts.

**Comment by iamrahul24** [comment]
![image](https://user-images.githubusercontent.com/62786811/148585696-1b7d59f9-f403-4166-ab91-4d371ec1a086.png)

**Comment by iamrahul24** [comment]
> ![image](https://user-images.githubusercontent.com/62786811/148585696-1b7d59f9-f403-4166-ab91-4d371ec1a086.png)

i have solved this issue but I cant use /info

**Comment by wolf498** [comment]
> (node:2990) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'SlashCommand' of undefined at WebSocketManager. (/home/runner/Discord-MusicBot/structures/DiscordMusicBot.js:108:15) at processTicksAndRejections (internal/process/task_queues.js:97:5)  node index.js

where do i fix the issue with / command

**Comment by iamrahul24** [comment]
> > (node:2990) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'SlashCommand' of undefined at WebSocketManager. (/home/runner/Discord-MusicBot/structures/DiscordMusicBot.js:108:15) at processTicksAndRejections (internal/process/task_queues.js:97:5)  node index.js
> 
> where do i fix the issue with / command

You need to host lavalink fir that. But it is not working properly.
