### ISSUE TITLE
No normal commands notice feature

### ISSUE THREAD

**Issue by testbot-github** [SudhanPlayz/Discord-MusicBot#633]
**Is your feature request related to a problem? Please describe.**
Yes, Some people will think that the bot will only work with normal commands.

**Describe the ideal solution**
Add Trigger -
If someone uses a normal command then it will tell `normal commands are not supported and you can use slash commands` and if a specific guild didn't give slash perms to the bot, it will tell to reinvite with slash command perms.

**Comment by DarrenOfficial** [comment]
No
