### ISSUE TITLE
Crashes when playing certain playlists from spotify

### ISSUE THREAD

**Issue by Fluff663** [SudhanPlayz/Discord-MusicBot#640]
**Please describe the problem you are having in as much detail as possible:**
The bot crashes when playing this playlist - https://open.spotify.com/playlist/5Zg5m6T2vysZyemIPHkflZ?si=68bd86b6c9d645a7

**Further details:**

- discord.js version:13.5.1
- Node.js version:17.2.0
- Operating system:Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
Medium
**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

![image](https://user-images.githubusercontent.com/31542675/148841817-a0fe5e03-4527-495d-8b05-e2273d2f19ff.png)

**Comment by DarrenOfficial** [comment]
don't use discord.js 13 for v4.

**Comment by JotaroKujo0525** [comment]
Also recommend you to use lts version

**Comment by Fluff663** [comment]
how do i downgrade discord.js
![image](https://user-images.githubusercontent.com/31542675/148954662-ce57e241-5cf0-48a0-a93c-3d11915936ef.png)

**Comment by Fluff663** [comment]
nevermind i just forgot to uninstall first
