### ISSUE TITLE
Bot doesn't recognize it has been disconnected if someone forcefully disconnects. -v4

### ISSUE THREAD

**Issue by sumeetsingh180** [SudhanPlayz/Discord-MusicBot#643]
If someone forcefully disconnects the bot from VC(without using the command ) when it's playing a song or on 24/7 it disconnects but it still thinks it's in VC. IF you try to play a song after that it says "you should be connected to the same VC" and it does not work until the bot is restarted.

**Comment by DarrenOfficial** [comment]
This issue has been solved in v5,
due to v4 using a deprecated (d.js12) v4 will not be updated anymore.
