### ISSUE TITLE
How can you change the status to streaming?

### ISSUE THREAD

**Issue by Keshii1** [SudhanPlayz/Discord-MusicBot#661]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Describe the ideal solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by kotru21** [comment]
check config file

**Comment by kotru21** [comment]
![IMG_20220119_132127.jpg](https://user-images.githubusercontent.com/88907641/150111493-d02eb6fd-25e5-4b01-9230-3d1bd438580a.jpg)

**Comment by kotru21** [comment]
Change 
type:"LISTENING"
to 
type:"STREAMING"

**Comment by JotaroKujo0525** [comment]
Also why does this have enhancement tag xddddd
