### ISSUE TITLE
/volume command wont work

### ISSUE THREAD

**Issue by NidhishRAR** [SudhanPlayz/Discord-MusicBot#662]
The /volume command wont work if nothing is entered in the amount , whereas it is supposed to tell the current volume.

![Screenshot 2022-01-20 102103](https://user-images.githubusercontent.com/76802532/150276915-9ef0dad8-4c77-4716-93e2-9d4be16a63fb.png)

**Console log error**-

(node:165) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.run (/home/runner/Pissed-Music-Bot/commands/volume.js:104:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:165) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

**Further details:**

- discord.js version: v13.6.0
- Node.js version: v12.16.1
- Operating system: Running on replit

**Comment by DarrenOfficial** [comment]
Read the error, and also running the bot on replit has some issue like this. I do not recommend using replit for hosting.

**Comment by NidhishRAR** [comment]
Which is better to host then replit? heruko? Or what?

**Comment by dottodottoo** [comment]
> Which is better to host then replit? heruko? Or what?

both of them is sucks, get a vps

**Comment by DarrenOfficial** [comment]
or a dedicated server brrr

**Comment by NidhishRAR** [comment]
Ok, lol thanks 😜
