### ISSUE TITLE
Bot isn't reply text when host it on glitch.me  

### ISSUE THREAD

**Issue by anny414** [SudhanPlayz/Discord-MusicBot#67]
**Bot not replying so please add a some steps for how to activate bot on glitch**

**Comment by SudhanPlayz** [comment]
Can you show logs

**Comment by AnkitBattula** [comment]
> Can you show logs

![Screenshot (48)](https://user-images.githubusercontent.com/28685132/101568834-cbd91a00-39ec-11eb-89b5-d05a81e1fb35.png)
![Screenshot (49)](https://user-images.githubusercontent.com/28685132/101568842-cf6ca100-39ec-11eb-80ec-ac4f53a9560c.png)

**Comment by AnkitBattula** [comment]
> Can you show logs
@SudhanPlayz  check plzz

**Comment by Colonel-Ltd** [comment]
Glitch didnt support node 14 so, you need to update node version to 12.

**Closed**
