### ISSUE TITLE
Mute resume bug

### ISSUE THREAD

**Issue by SDS1234** [SudhanPlayz/Discord-MusicBot#671]
I paused the bot. Earlier I server muted server someone in my voice channel server and then the music resumed. And when I unmuted him again, the music paused again.

**Comment by SDS1234** [comment]
![grafik](https://user-images.githubusercontent.com/54279682/150776693-c9440cd5-bc75-4d24-8f0d-dc69b1e4d5d7.png)

**Comment by kotru21** [comment]
omg ping 234 ms
Maybe bot is overloaded?
I dont really sure that this bug happends because of overload but ping & latency is too big.
And try to update bot to v 4.1.4(latest commits)

**Comment by SDS1234** [comment]
How can i update?

And its not overloaded:
![grafik](https://user-images.githubusercontent.com/54279682/150851243-bc04ba84-9325-432d-ae93-3dc13f891886.png)

**Comment by SDS1234** [comment]
> And try to update bot to v 4.1.4(latest commits), at least it will fix some other issues.

The latest released version is v.4.1.2

**Comment by kotru21** [comment]
![image](https://user-images.githubusercontent.com/88907641/150853039-6534420e-bea5-4974-8da2-fed17ee66d93.png)

**Comment by kotru21** [comment]
I mean that you have ping & API latency around 300.
It is not good.

**Comment by SDS1234** [comment]
True, but what can i do against it

**Comment by SDS1234** [comment]
> ![image](https://user-images.githubusercontent.com/88907641/150853039-6534420e-bea5-4974-8da2-fed17ee66d93.png) v 4.1.4 is latest

![grafik](https://user-images.githubusercontent.com/54279682/150853374-1dc151cf-60b6-4f7f-9cad-1595347c3ebf.png)

**Comment by kotru21** [comment]
It is not related to this bug, but what hosting are you using?

**Comment by SDS1234** [comment]
> It is not related to this bug, but what hosting are you using?

I host it by myself (using pterodactyl)

**Comment by DarrenOfficial** [comment]
234 ping is not overloaded. that's like 0.2xxx seconds which is fast

**Comment by SDS1234** [comment]
yeah but why is it that high?

**Comment by DarrenOfficial** [comment]
v4 is known to have this issue. the only way to fix it is to use the v5-beta version. which you can get at https://github.com/sudhanplayz/discord-musicbot/tree/v5

**Comment by kotru21** [comment]
> 234 ping is not overloaded. that's like 0.2xxx seconds which is fast

oh,ok I thought that if application ping >100 it is bad.
i have 60ms on my host

**Comment by DarrenOfficial** [comment]
> yeah but why is it that high?

because of location?

**Comment by SDS1234** [comment]
my server are in the Netherlands
and I'm in Germany

**Comment by DarrenOfficial** [comment]
> > 234 ping is not overloaded. that's like 0.2xxx seconds which is fast
> 
> oh,ok I thought that if application ping >100 it is bad. i have 60ms on my host

I would say anything under 600 - 700ms should be fine, but anything above that you may notice the lag.

**Comment by kotru21** [comment]
> > > 234 ping is not overloaded. that's like 0.2xxx seconds which is fast
> > 
> > 
> > oh,ok I thought that if application ping >100 it is bad. i have 60ms on my host
> 
> I would say anything under 600 - 700ms should be fine, but anything above that you may notice the lag.

Ok, ths for info

**Comment by DarrenOfficial** [comment]
> my server are in the Netherlands
> and I'm in Germany

doesn't matter where you are, what matter is the discord api endpoint. which is located in the usa

**Comment by SDS1234** [comment]
So i cant do anything against it?

**Comment by DarrenOfficial** [comment]
> So i cant do anything against it?

do what exactly...

**Comment by SDS1234** [comment]
Make the ping better

**Comment by DarrenOfficial** [comment]
Other than to move the server host to us *or near it*, No.

**Comment by SDS1234** [comment]
k

**Comment by SDS1234** [comment]
> I paused the bot. Earlier I server muted server someone in my voice channel server and then the music resumed. And when I unmuted him again, the music paused again.

And what's about the bug?

**Comment by DarrenOfficial** [comment]
> v4 is known to have this issue. the only way to fix it is to use the v5-beta version. which you can get at https://github.com/sudhanplayz/discord-musicbot/tree/v5

this

**Comment by DarrenOfficial** [comment]
tho v5 doesn't have a dashboard yet... it's still wip

**Comment by SDS1234** [comment]
Would you recommend to me to update to the beta?

**Comment by SDS1234** [comment]
Or should i wait?

**Comment by kotru21** [comment]
If this bug is not too critical for you i would reccommend to wait for v5 release.

**Comment by SDS1234** [comment]
Do you know if the bug is fixed in the new version

**Comment by DarrenOfficial** [comment]
It's fixed

**Comment by kotru21** [comment]
> v4 is known to have this issue. the only way to fix it is to use the v5-beta version. which you can get at https://github.com/sudhanplayz/discord-musicbot/tree/v5

Darren says that it is fixed
As I said, try v5 not on "production" server.

**Comment by DarrenOfficial** [comment]
Most of the v4 bug report has been implemented in v5

**Comment by SDS1234** [comment]
> Otherwise try v5 You can try it not in "production" server.

What do you mean by this?

**Comment by kotru21** [comment]
> > Otherwise try v5 You can try it not in "production" server.
> 
> What do you mean by this?

Make other bot(with v5 branch) and check how it works

**Comment by SDS1234** [comment]
okay, thank you guys for your help

**Comment by DarrenOfficial** [comment]
You can try the v5-beta version to see if you liked it or no, if not use v4. :p
v5 bot https://buses.rocks

**Comment by DarrenOfficial** [comment]
also v5-beta isn't compatible with v4. So you'll need to reinvite it from all server.

**Comment by DarrenOfficial** [comment]
tho we will make the migration commands as soon as the dashboard is completed.
