### ISSUE TITLE
Suddenly stops

### ISSUE THREAD

**Issue by DilanDimel** [SudhanPlayz/Discord-MusicBot#674]
The bot works perfectly but suddenly stops working even while online. The weird part is the bot is in vc too but when I try commands, there is no response, so I stopped the bot and started it again. It starts normally and says its only but the bot is not online. I checked the repl.it to see what's wrong and I saw while it was starting all the code doesn't load.
![Opera Snapshot_2022-01-23_213543_replit com](https://user-images.githubusercontent.com/88804934/150718136-faf9d1e7-d81a-4554-a964-2f6f9d933f86.png)
![Opera Snapshot_2022-01-23_213812_discord com](https://user-images.githubusercontent.com/88804934/150718235-d64b7622-6bc5-457f-b03c-c2aff4381b00.png)

**Comment by DarrenOfficial** [comment]
You're being ratelimited by discord. this is not a bug.

**Comment by DarrenOfficial** [comment]
This happens most likely because you're using shared hosting. *repl.it*
