### ISSUE TITLE
[v5] Bot doesn't stop playback when moved to a channel with no users.

### ISSUE THREAD

**Issue by alou-S** [SudhanPlayz/Discord-MusicBot#679]
#### Pre-Requisites
- `alwaysplay: false` in `config.js`

#### Description
- If you move the bot to a Voice Channel with no people it won't pause playback.

#### Expected Behaviour
- Pauses playback since new channel has no users.

#### Other Notes
- Funnily the bot deals with dragging it from an empty channel to a channel with people just fine
- Also if you throw it in a channel without people and then move it back to a channel with people it will say "Resumed Playback" despite never pausing said playback.

**Comment by alou-S** [comment]
@DarrenOfficial Bump

**Comment by DarrenOfficial** [comment]
i'll look into it.

**Comment by BioCla** [comment]
looked around:
`\lib\DiscordMusicBot.js` (Line 187)
and
`\node_modules\erela.js\dist\structures\Manager.js` (Line 264) might be useful
