### ISSUE TITLE
[v5] Bot doesn't have embed player controls on Now Playing embed.

### ISSUE THREAD

**Issue by alou-S** [SudhanPlayz/Discord-MusicBot#680]
#### Pre-Requisites
- `alwaysplay: false` in `config.js`

#### Description
- The new "Now Playing" embed  after pausing and resuming playback from user leaving and joining channel doesn't contain player controls (pause/play, volup, voldown)

#### Example of embed with the controls
![image](https://user-images.githubusercontent.com/73123610/151169846-af1841ce-0e02-4252-8b01-8631f3934000.png)

#### Expected Behavior
- New "Now Playing" embed has player controls.

#### Steps to Reproduce
1. Leave Channel
2. Bot send paused playback embed.
3. Join Channel.
4. Bot sends resumed playback embed.
5. Bot sends now playing embed without player controls.
6. User has to scroll to previous "Now Playing" embed to use controls.

#### Image of said behavior
![image](https://user-images.githubusercontent.com/73123610/151170248-b04b1ffd-5b03-4e12-80ce-a425766d2d19.png)

**Comment by DarrenOfficial** [comment]
Fixed :p
![NewEmbed](https://grabify.photos/i/7728a2f3.png)
