### ISSUE TITLE
Port to TypeScript

### ISSUE THREAD

**Issue by valandexx** [SudhanPlayz/Discord-MusicBot#683]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Describe the ideal solution**
Bot ported to TypeScript.

**Describe alternatives you've considered**

**Additional context**

**Comment by DarrenOfficial** [comment]
Why, Give us a good reason to convert the bot to ts then maybe we'll consider it.
