### ISSUE TITLE
Lavalink node not connected

### ISSUE THREAD

**Issue by prayaslk** [SudhanPlayz/Discord-MusicBot#684]
**Please describe the problem you are having in as much detail as possible:** I put the lavalink details but still bot says lavalink node not connected how to fix this?

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by kotru21** [comment]
Check this issue:
https://github.com/SudhanPlayz/Discord-MusicBot/issues/665

**Comment by prayaslk** [comment]
Not working bro 
![IMG_20220127_120853](https://user-images.githubusercontent.com/70499403/151306729-5d8cc746-f368-4696-91cb-bbeec56da592.jpg)
![IMG_20220127_121826](https://user-images.githubusercontent.com/70499403/151306749-7f12a12a-c34f-4300-8b04-9f037989178a.jpg)

**Comment by kotru21** [comment]
If you have DiscordAPI missing acess err check you token client secret & client id
Maybe you filled something wrong

**Comment by kotru21** [comment]
And check lavalink config again, please
You need to put correct host password and port
You can find public lava servers here: https://lavalink.darrennathanael.com/

**Comment by JotaroKujo0525** [comment]
Don't put this as a bug brah

**Comment by kotru21** [comment]
Yea,chang the label to help-wanted

**Comment by SoaringGecko** [comment]
I am also having this problem, weird thing is though I've been hosting my bot for a very long time and it only just recently stopped working

**Comment by LewdHuTao** [comment]
> I am also having this problem, weird thing is though I've been hosting my bot for a very long time and it only just recently stopped working

just change your lavalink then
