### ISSUE TITLE
[v5] Bot loses Discord Presence attributes after a while. (Also happens on v4)

### ISSUE THREAD

**Issue by alou-S** [SudhanPlayz/Discord-MusicBot#685]
#### Description
- Bot loses Discord Presence status and activity after a while.
- Don't really know a way to reproduce bug but it just happens after leaving the bot running for a while.

#### Steps to Reproduce
?. Probably caused due to network issues with the bot host?

#### Possible Fix
- Make sure the bot updates its Discord Presence every once every minute or something. (Yeah pretty inefficient probably something better out there I have no idea of javascript or discord.js)

#### What I mean by Discord Presence
![image](https://user-images.githubusercontent.com/73123610/151373432-0ec05467-bf69-4665-bb5d-a1557592be7d.png)
The status changes to online and the activity to nothing.

**Comment by DarrenOfficial** [comment]
It's host issue, and also discord api issue. sometimes the api just dies. https://dis.gd/status
