### ISSUE TITLE
[v5] /play from Spotify & YouTube Crashing

### ISSUE THREAD

**Issue by t0g3pii** [SudhanPlayz/Discord-MusicBot#687]
**Please describe the problem you are having in as much detail as possible:**
Downloaded a Fresh Install of this, configured everything including the Spotify Stuff.
Started the bot, used the >play command for a Spotify Playlist
Bot Answered with the Following:
`:mag_right: Searching...
No matches found for - https://open.spotify.com/playlist/0FgYR2laRfBLO2fAWNmg81?si=30418e30f3064298`

Crash Code in Console is further down.

**Include a reproducible code sample here, if possible:**

```js
/play https://open.spotify.com/playlist/0FgYR2laRfBLO2fAWNmg81?si=30418e30f3064298
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: v16.10.0
- Operating system: Windows 11
- Priority this issue should have – Normal

`RangeError: Argument "data" is not a valid track: Cannot read properties of undefined (reading 'includes')
    at Function.build (C:\Users\Nico\Desktop\Discord-MusicBot-4.1.2\node_modules\erela.js\dist\structures\Utils.js:120:19)
    at Object.run (C:\Users\Nico\Desktop\Discord-MusicBot-4.1.2\commands\play.js:78:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
C:\Users\Nico\Desktop\Discord-MusicBot-4.1.2\node_modules\erela.js\dist\structures\Utils.js:120
            throw new RangeError(`Argument "data" is not a valid track: ${error.message}`);
                  ^`

**Comment by SudhanPlayz** [comment]
It works in current commit of v5, Maybe it's because of lavalink server. Fix your lavalink server

**Comment by t0g3pii** [comment]
> It works in current commit of v5, Maybe it's because of lavalink server. Fix your lavalink server

Im using the latest Version of Lavalink Server with the Following Example Settings:

`server: # REST and WS server
  port: 8080
  address: 0.0.0.0
lavalink:
  server:
    password: "passwordRemovedForGithub"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO`

**Comment by t0g3pii** [comment]
Okay, i switched to v5, tried /play https://www.youtube.com/playlist?list=PLNjBRrjKmKELI1E3PJr2DkcMzqxmYxtXo and tried /play https://open.spotify.com/playlist/0FgYR2laRfBLO2fAWNmg81?si=e5de68290ac54523

But got the Following Error now:

> TypeError [COMMAND_INTERACTION_OPTION_NOT_FOUND]: Required option "query" not found.
    at CommandInteractionOptionResolver.get (C:\Users\Nico\Desktop\Discord-MusicBot-5\node_modules\discord.js\src\structures\CommandInteractionOptionResolver.js:77:15)
    at CommandInteractionOptionResolver._getTypedOption (C:\Users\Nico\Desktop\Discord-MusicBot-5\node_modules\discord.js\src\structures\CommandInteractionOptionResolver.js:94:25)
    at CommandInteractionOptionResolver.getString (C:\Users\Nico\Desktop\Discord-MusicBot-5\node_modules\discord.js\src\structures\CommandInteractionOptionResolver.js:159:25)
    at SlashCommand.run (C:\Users\Nico\Desktop\Discord-MusicBot-5\commands\slash\play.js:23:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'COMMAND_INTERACTION_OPTION_NOT_FOUND'

**Comment by t0g3pii** [comment]
Reinvite the bot solved the issue, after reinvite i used npm run deploy again^^

Problem was the the arg from play was in v4 "url" or something similiar and changed in v5 to "query"
