### ISSUE TITLE
[v5] The queue ends after the volume down button is pressed

### ISSUE THREAD

**Issue by NONPLAYT** [SudhanPlayz/Discord-MusicBot#694]
**Please describe the problem you are having in as much detail as possible: im installed v5 to test how it work, but when I pressing volume down button in player, queue is ending**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version: 13.5.1
- Node.js version: 16.13.1
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Relevant client options:**

- partials: none
- gateway intents: presence, server members, and message content
- other: none

**Comment by DarrenOfficial** [comment]
Please provide more details on this issue.
