### ISSUE TITLE
Implement auto join Stage

### ISSUE THREAD

**Issue by itsfranciscooli** [SudhanPlayz/Discord-MusicBot#695]
Implement bot auto joins stage as speaker when requested.

**Comment by DarrenOfficial** [comment]
;-;

**Comment by DarrenOfficial** [comment]
https://git.darrennathanael.com/DarrenOfficial/DiscordMusic/commit/18d28fccc8bb9cec7e5db66c54493c3722281f0c take your cake and eat it two.
