### ISSUE TITLE
Support for playlist list

### ISSUE THREAD

**Issue by scifisatan** [SudhanPlayz/Discord-MusicBot#704]
It becomes frustrating to put each and every song link to play. So a feature to play from playlist link would be nice.

**Comment by DarrenOfficial** [comment]
No.

**Comment by DarrenOfficial** [comment]
We've tried to do playlist, but it requires an external db, maybe in the future release of v5.

**Comment by t0g3pii** [comment]
a simple json where a playlist url is saved until a external db solution is found? 
```
[
{
"name1": "spotify.com/url1",
"name2": "youtube.com/playlisturl"
}
]
```
