### ISSUE TITLE
Add a DJ Role feature.

### ISSUE THREAD

**Issue by Dragonizedpizza** [SudhanPlayz/Discord-MusicBot#71]
Add a DJ Role feature.

A DJ role means when the only a specific role can stop and skip music.

**Comment by asavage7** [comment]
I would also like to see this change, it can be frustrating sometimes when everyone can skip or stop music.

**Comment by SudhanPlayz** [comment]
What happen if the DJ is offline and the users needed to skip the song

**Comment by asavage7** [comment]
I don't know how easy this would be to implement but what if there was some sort of voting system?

**Comment by Dragonizedpizza** [comment]
> What happen if the DJ is offline and the users needed to skip the song

A DJ role. Meaning multiple users can have the role.
