### ISSUE TITLE
Bot crashes when person which isn't in a voice channel uses `!skipto`

### ISSUE THREAD

**Issue by Keyitdev** [SudhanPlayz/Discord-MusicBot#727]
**Please describe the problem you are having in as much detail as possible:**
When the first person is in a voice channel with the bot and the bot is playing a music playlist (of course the playlist has more than 1 song), and other person ( which isn't in the voice channel) uses `!skipto` the bot crashes.

**Include a reproducible code sample here, if possible:**

```js
~/commands/skipto.js:23
      voiceChannel: message.member.voice.channel.id,
                                                 ^

TypeError: Cannot read properties of null (reading 'id')
    at Object.run (~/commands/skipto.js:23:50)
    at module.exports (~/events/message.js:67:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.3.0
```

**Further details:**

- bot version: v4.1.4
- discord.js version: v12.5.3
- Node.js version: v16.14.0 (also tested on v17.3.0)
- Operating system: GNU/Linux (arch)
- Priority this issue should have – please be realistic and elaborate if possible: Normal

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by DarrenOfficial** [comment]
already fixed in v5
