### ISSUE TITLE
Bug for status streaming

### ISSUE THREAD

**Issue by Maxey1950** [SudhanPlayz/Discord-MusicBot#733]
So i have this 
Presence: {
  status: "online", // You can show online, idle, and dnd
    name: "Prefix -", // The message shown
type: "STREAMING",
url: "https://www.twitch.tv/nocopyrightsounds",
},
  
But when i look in discord in the server it says playing  not streaming anyone help?

Pls help or fix bug

**Comment by Maxey1950** [comment]
@here Help pls

**Comment by JotaroKujo0525** [comment]
???

**Comment by JotaroKujo0525** [comment]
Brah, this isn't even a bug, idk your host maybe slow, try regenerating your token and see

**Comment by JotaroKujo0525** [comment]
Also remove the bug label

**Comment by Maxey1950** [comment]
> Brah, this isn't even a bug, idk your host maybe slow, try regenerating your token and see

it is not i was running it on repl.it

**Comment by JotaroKujo0525** [comment]
Yes, replit is slow

**Comment by Maxey1950** [comment]
i did it on my pc to but it said 
TypeError: client.build is not a function
    at Object.<anonymous> (H:\Discord-MusicBot-master\Discord-MusicBot-master\index.js:4:8)      
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

**Comment by JotaroKujo0525** [comment]
It means you didn't fill all of your botconfig.js

**Comment by kotru21** [comment]
> i did it on my pc to but it said TypeError: client.build is not a function at Object. (H:\Discord-MusicBot-master\Discord-MusicBot-master\index.js:4:8) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) at Module.load (internal/modules/cjs/loader.js:950:32) at Function.Module._load (internal/modules/cjs/loader.js:790:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) at internal/main/run_main_module.js:17:47

whaoh, this err means that you forgot to fill something in botconfig.js file

**Comment by kotru21** [comment]
Maybe close this issue?
