### ISSUE TITLE
PLAY COMMAND ERROR

### ISSUE THREAD

**Issue by brahmendra79** [SudhanPlayz/Discord-MusicBot#734]
TypeError [COMMAND_INTERACTION_OPTION_NOT_FOUND]: Required option "query" not found.

In V5

**Comment by txj-xyz** [comment]
Please provide your code and the error, this is not a lib error.

**Comment by dottodottoo** [comment]
> TypeError [COMMAND_INTERACTION_OPTION_NOT_FOUND]: Required option "query" not found.
> 
> In V5

you probably use v4 on same bot before and try to run v5 without deploy the slash commands and not reinvite the bot to remove v4 commands

**Comment by dottodottoo** [comment]
and why you added bug label ;-;

**Comment by JotaroKujo0525** [comment]
Please remove the bug label and add help wanted instead

**Comment by txj-xyz** [comment]
@SudhanPlayz Can you please close this?
