### ISSUE TITLE
Express Server for Replit Always On

### ISSUE THREAD

**Issue by kaaax0815** [SudhanPlayz/Discord-MusicBot#74]

**Comment by Colonel-Ltd** [comment]
No description provided.

**Comment by kaaax0815** [comment]
https://repl.it/talk/learn/Hosting-discordjs-bots-on-replit-Works-for-both-discordjs-and-Eris/11027
You need a server that gets pinged with e.g. uptimerobot, so the bot stays on and the repl doesnt become idle

**Comment by SudhanPlayz** [comment]
We dont need an express server

**Comment by kaaax0815** [comment]
Do you pay for Replit? Because I cloned your repo on repl and if i dont use the express server with uptimerobot, the repl gets down

**Comment by SudhanPlayz** [comment]
Its your problem not of Discord Music Bot and anyway a express server is coming up for v4 as a dashboard though
