### ISSUE TITLE
Can't use /queue after adding spotify playlist but [prefix]queue works and songs work. (v5)

### ISSUE THREAD

**Issue by DudeShift** [SudhanPlayz/Discord-MusicBot#742]
I am hosting a bot on replit following the v5 guide, after adding a spotify playlist, the slash command for queue does not work. I get a "The application did not respond" message in discord and replit console output of:

_(node:1550) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
    at DiscordMusicBot.module.exports [as Pagination] (/home/runner/Discord-MusicBot/util/pagination.js:12:37)
    at Object.run (/home/runner/Discord-MusicBot/commands/queue.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)_

**However,** using the [prefix] version of the queue command (ie, !queue) works. Nothing else seems to be effected as songs will still play, you can add, move, remove, etc, Adding more non-spotify source songs will not fix the slash queue command.

**Comment by JotaroKujo0525** [comment]
well, the bot can't send a message

**Comment by DarrenOfficial** [comment]
that's not v5? v5 doesn't have prefix

**Comment by txj-xyz** [comment]
v5 is working fine as of my tests, can you please add reproduction steps?

**Comment by DarrenOfficial** [comment]
closing this as @DudeShift haven't replied.

**Comment by Seth-Revz** [comment]
Not on v5 but,
slash command `/queue` crashes mine as well if there is more than a page of items and pagination is called.
prefix command works fine.

```
C:\Users\Development\Desktop\Discord-MusicBot-master\util\pagination.js:12
  const curPage = await msg.channel.send(
                                    ^

TypeError: Cannot read properties of undefined (reading 'send')
    at DiscordMusicBot.module.exports [as Pagination] (C:\Users\Development\Desktop\Discord-MusicBot-master\util\pagination.js:12:37)
    at Object.run (C:\Users\Development\Desktop\Discord-MusicBot-master\commands\queue.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

to reproduce I just add a long spotify playlist and /queue.

**Comment by DarrenOfficial** [comment]
Do not reply to this issue. This is a completely different issue than you have @Seth-Revz consider asking in the discord server or opening another github issue.

Putting your issue in here is useless.
--



Glowing regards,

Darren Nathanael.
