### ISSUE TITLE
Vc bug

### ISSUE THREAD

**Issue by Alone-ankush** [SudhanPlayz/Discord-MusicBot#746]
When I move bot to new vc..it doesn't play any song...

**Comment by JotaroKujo0525** [comment]
Please provide more information. Not just `When I move bot to new vc..it doesn't play any song... ` ;-;

**Comment by Alone-ankush** [comment]
Suppose 
I played a song in - music 1
Then I moved bot to - music 2
I also moved to music 2
But,when I play a song
Bot tell 
 | You must be in the same voice channel as me to use this command!
Please fix this bug

**Comment by DarrenOfficial** [comment]
already fixed in v5
