### ISSUE TITLE
/commands being duplicated on upgrade 

### ISSUE THREAD

**Issue by AidanTheBandit1** [SudhanPlayz/Discord-MusicBot#747]
**Please describe the problem you are having in as much detail as possible:**
When upgrading the bot from V4 to V5 it doesn’t remove old commands resulting in duplicates of many old commands and some old commands still show up but simply don’t work
**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version: latest
- Node.js version: 17.6
- Operating system: Ubuntu Server
- Priority this issue should have – please be realistic and elaborate if possible: 4/10

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by LewdHuTao** [comment]
its not a bug lol, you have to reinvite your bot to remove v4 commands

**Comment by AidanTheBandit1** [comment]
Ok
