### ISSUE TITLE
bot still playing after disconnecting

### ISSUE THREAD

**Issue by AliDayyani** [SudhanPlayz/Discord-MusicBot#749]
bot still playing after disconnecting without dc command 
can you fix it please

**Comment by JotaroKujo0525** [comment]
you mean the bot still plays even you disconnect?

**Comment by AliDayyani** [comment]
yes after disconnecting with the discord disconnect button it still play and didn't clear the queue

**Comment by AliDayyani** [comment]
I think this code help you 
client.on('voiceStateUpdate', (oldState, newState) => {
    // check if someone connects or disconnects
    if (oldState.channelID === null || typeof oldState.channelID == 'undefined') return;
    // check if the bot is disconnecting
    if (newState.id !== client.user.id) return;
    // clear the queue
    return queue.delete(oldState.guild.id);
    
});

**Comment by AliDayyani** [comment]
why are you close this it still having problem

**Comment by DarrenOfficial** [comment]
because it's already fixed?

**Comment by DarrenOfficial** [comment]
https://git.unix.lgbt/Darren/DiscordMusic/commit/8161eb139bc84811dbad2ec7a7df033d0a08ca56
