### ISSUE TITLE
discord.js@12.5.3 No longer Supported 

### ISSUE THREAD

**Issue by Supreme69X** [SudhanPlayz/Discord-MusicBot#754]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
The bot not getting online as the version of [discord.js@12.5.3] has been not supported as i am deleting the lasted version and install the old one it show it is not supported
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by LewdHuTao** [comment]
wait djs 12 already stopped working? i thought it will stop working on april 30
