### ISSUE TITLE
Backup lavalink.

### ISSUE THREAD

**Issue by shanuflash** [SudhanPlayz/Discord-MusicBot#755]
I'd be great if there was an option for backup lavalink, when your main lavalink fails (or) is down, it could connect to it until the main comes back online. I am using your source for my discord bot, but sometimes lavalink timesout (or) limit exceeds and I have to change servers and restart the bot.

**Comment by DarrenOfficial** [comment]
This was a limitation of lavasfy. It is solved in the v5 branch https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5

**Comment by shanuflash** [comment]
@DarrenOfficial is v5 branch stable enough to run my bot on it? Or should I wait for the final release. Thanks.

**Comment by JotaroKujo0525** [comment]
Ye it's stable enough
