### ISSUE TITLE
[v5] Using server mute on anybody causes the bot to pause itself (wtf)

### ISSUE THREAD

**Issue by alou-S** [SudhanPlayz/Discord-MusicBot#766]
#### Description
- Server muting anybody in a voice chat pauses the bot

#### Expected Behavior
- The bot keeps playing the song?

### How to Reproduce
1. Make bot play a song
2. Server mute yourself or anybody (not the normal mute)
3. The bot pauses itself.

#### Other Notes
- How does this even happen?
- You can use `/resume` to resume the bot.

**Comment by DarrenOfficial** [comment]
it's not an issue with erela

**Comment by BioCla** [comment]
> hay sorry to bug you guys but i found the problem return; // you never know, right if (newState.serverMute == true && oldState.serverMute == false) (line 26) this I removed it and you can server mute in voice state

In what file though?

**Comment by wolf498** [comment]
thats the one

**Comment by BioCla** [comment]
> thats the one

I think however that your fix isn't quite optimal... while it may work it's supposed to prevent the bot to keep the song going when it's muted, the slight oversight is that the clause checks for all new states in the VC instead of just the bot's'

**Comment by wolf498** [comment]
it fixes the server mute problem

**Comment by BioCla** [comment]
> it fixes the server mute problem

But If you mute the bot the player will still roll and while you can't hear it the song will keep going, which is unintended
