### ISSUE TITLE
No matches found

### ISSUE THREAD

**Issue by GoodDay360** [SudhanPlayz/Discord-MusicBot#772]
I use default config, but the bot returns `No matches found for - music...`
Host at: https://replit.com/

**Comment by Vincenzo160** [comment]
I am encountering the same problem

**Comment by Vincenzo160** [comment]
I had the same problem, just change the default lava link server with your own or use a public one, you can find a list [here](https://lavalink-list.darrennathanael.com/NoSSL/lavalink-without-ssl/)

**Comment by JotaroKujo0525** [comment]
Also this isn't a bug or smth + can somebody close this
