### ISSUE TITLE
[v5] Reload command

### ISSUE THREAD

**Issue by XstreamSpeed** [SudhanPlayz/Discord-MusicBot#775]
**Is your feature request related to a problem? Please describe.**
Yes, it is, currently the Admins config in config.js has no use, a reload command would be helpful for the bot owners when the bot bugs out in the server.

**Describe the ideal solution**
Basically, the command restarts the bot when required, the only people who can use this command are the bot owners(client.config.Admins) it will help for a quick fix for issues that are yet to be reported to the developers.

**Describe alternatives you've considered**
None that could be more efficient as of when I’m writing this.

**Additional context**
The embed could look this this:
.setTitle(‘All commands were successfully reloaded’)
.addField(‘Reloaded commands’, ${commands.reloaded_or_smth})
.addField(‘Commands failed to reload’, ${command.reload.failed_or_smth})
.setFooter(‘Bot reloaded by: ${message.author }’)
.setTimestamp();

**Comment by DarrenOfficial** [comment]
added
