### ISSUE TITLE
Playback error! [v5]

### ISSUE THREAD

**Issue by Vretu-Dev** [SudhanPlayz/Discord-MusicBot#779]
While change Volume on Button, music was crashed and skip next until the end of the queue.

![Screenshot_2022-04-04-22-53-47-06](https://user-images.githubusercontent.com/82831707/161630408-0b2c5c38-e461-474b-bceb-b8e0689f65af.jpg)

**Comment by DarrenOfficial** [comment]
not bot issue, it's your lavalink issue.
