### ISSUE TITLE
Afk is a moderatos command but anyone can use this command

### ISSUE THREAD

**Issue by anny414** [SudhanPlayz/Discord-MusicBot#78]
Afk is a moderatos command but anyone can use this command Please make only for mods!!

**Comment by SudhanPlayz** [comment]
So hm what server permission needed to use that command

**Comment by anny414** [comment]
Manage Server Permission Need Fir That Command I Think

**Comment by anny414** [comment]
> So hm what server permission needed to use that command

please add quickly We are waiting ??

**Comment by tyger796** [comment]
coding takes time, leave the author alone. he can go at his own pace

**Comment by anny414** [comment]
I have tried To add permission  with This 
`if(!message.author.hasPermission("MANAGE_CHANNEL")){
message.channel.send(`YOU DON'T  HAVE PERMISSION `)

}`
But I am getting a error like these
https://cdn.discordapp.com/attachments/773047507009404948/800001759153618944/unknown.png 
Any one can help me ?

**Comment by OblivionGhoul** [comment]
Try using 
`message.member.hasPermission('MANAGE_CHANNEL')`
