### ISSUE TITLE
[v5] double /play slash commands

### ISSUE THREAD

**Issue by kubo6472** [SudhanPlayz/Discord-MusicBot#785]
/play shows for both search and play directly as two different commands

**Comment by Jotarokujo10525** [comment]
What? I don't understand the explanation, please provide a screenshot of the issue

**Comment by XstreamSpeed** [comment]
I think he means that doing /play is searching the song and sending the SearchEmbed while also sending the SongAddedEmbed.

**Comment by kubo6472** [comment]
> I think he means that doing /play is searching the song and sending the SearchEmbed while also sending the SongAddedEmbed.

/play song: - bot fails to respond
/play query: - a song is played

**Comment by kubo6472** [comment]
> > > I think he means that doing /play is searching the song and sending the SearchEmbed while also sending the SongAddedEmbed.
> > 
> > 
> > /play song: - bot fails to respond /play query: - a song is played
> 
> It's the Slash command deployed if you did use V4 before, I don't remember exactly but reinviting it should remove /play song:

Oh, okay.
