### ISSUE TITLE
i want to make bot wait in voice channel some time after queue of music ends 

### ISSUE THREAD

**Issue by mohamedgentle** [SudhanPlayz/Discord-MusicBot#786]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by XstreamSpeed** [comment]
It's a coming feature in v5. It's in the config file with the name of disconnectTime.

**Comment by mohamedgentle** [comment]
> when v5 will realese ?

**Comment by Vretu-Dev** [comment]
> > when v5 will realese ?

Ask Sudhan
