### ISSUE TITLE
error when npm run deploy

### ISSUE THREAD

**Issue by pengengantibaju** [SudhanPlayz/Discord-MusicBot#787]
![image](https://user-images.githubusercontent.com/92777707/162636010-9a20ab9f-ef63-47da-ada6-82133b95e639.png)

pls help

**Comment by Jotarokujo10525** [comment]
Is that even v5 dude

**Comment by Vretu-Dev** [comment]
> ![image](https://user-images.githubusercontent.com/92777707/162636010-9a20ab9f-ef63-47da-ada6-82133b95e639.png)
> 
> pls help

Deploy only for V5 Branch. If you use V5 use `node deploy/globa`l
