### ISSUE TITLE
Please add Vote Skip Command

### ISSUE THREAD

**Issue by anny414** [SudhanPlayz/Discord-MusicBot#79]
Hello Developers 
Their is only Skip Command But Wnen Their are too many users Listening some people Can Skip Quickly And Frequently. So Please make Skip Commands for Mods Only and add vote skip Command

**Comment by LegendaryEmoji** [comment]
Hmm, I Can Make That And Pull Request :D

**Comment by skyventuree** [comment]
While Sudhan is busy with their life, you can check out [this](https://discordjs.guide/popular-topics/permissions.html#roles-as-bot-permissions) and some JS, nodeJS tutorial to add the permission yourself.
