### ISSUE TITLE
[v5] Speed command

### ISSUE THREAD

**Issue by XstreamSpeed** [SudhanPlayz/Discord-MusicBot#791]
**Is your feature request related to a problem? Please describe.**
It currently, isn't.

**Describe the ideal solution**
A speed command, it changes the speed of the video, much similar to the concept of the bassboost command in v4, The default speeds could be inherited from YouTube ( 1x, 1.5x, 2x) and there could also be a new addition to the config.js file as (client.config.maxSpeed) this shows the max speed users can use, this can go upto 4x or above (developer choice).

**Describe alternatives you've considered**
None at the moment.

**Additional context**
None.

**Comment by DarrenOfficial** [comment]
ask erela.js to implement it
