### ISSUE TITLE
Play command error

### ISSUE THREAD

**Issue by numarkpro** [SudhanPlayz/Discord-MusicBot#792]
Hello, I'm using the latest v5 beta hosted on hosting. When I use the /play command, in console give these error

![image](https://user-images.githubusercontent.com/73024472/163580242-0ea788c1-e126-4a90-9c7a-80e70b519b78.png)

**Comment by DarrenOfficial** [comment]
reinvite your bot

**Comment by numarkpro** [comment]
I reinvited the bot, but now there are no commands at all

**Comment by Jotarokujo10525** [comment]
i-

**Comment by Jotarokujo10525** [comment]
Dude. There's really no commands there because you need to deploy
