### ISSUE TITLE
Change embed's tItle in the play command 

### ISSUE THREAD

**Issue by XstreamSpeed** [SudhanPlayz/Discord-MusicBot#802]
**Is your feature request related to a problem? Please describe.**
No problems, a feature request

**Describe the ideal solution**
As you know there are currently 4 ways the bot plays music, youtube, spotify, deezer and apple music(there might be more), and there are embeds for each one of them, It would be good if it said the title as something like "Spotify/YouTube/Deezer/Apple Music Playlist Loaded".

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by DarrenOfficial** [comment]
I tried do that, but erela.js plugins kinda sucks and unfortunately theres no way to tell if the music url is from spotify or youtube.
