### ISSUE TITLE
Bot Disconnects after i used volume command

### ISSUE THREAD

**Issue by ProKocak28** [SudhanPlayz/Discord-MusicBot#826]
The bot just keeps disconnecting after i run the volume command. I tried to update erela.js but it still didnt work.

![Disconnected after running volume command](https://i.imgur.com/qq48gri.jpg)

idk how to fix this =\

**Comment by JotaroKujo0525** [comment]
change [lavalink](https://lavalink-list.darrennathanael.com/)

**Comment by ProKocak28** [comment]
> change [lavalink](https://lavalink-list.darrennathanael.com/)

it worked thx
