### ISSUE TITLE
Nuker

### ISSUE THREAD

**Issue by TopClips** [SudhanPlayz/Discord-MusicBot#829]
The bot just nukes 2 of my servers
![469254F1-D8E6-44FE-ABD3-CE7A1A6A9F91](https://user-images.githubusercontent.com/103296052/166220404-4f7948d2-ca76-4dfe-8590-867f19a3c60a.jpeg)

if I am being honust, I know it’s not you guys but I just need someone to take my anger out on. Sorry

**Comment by LewdHuTao** [comment]
w-what?

**Comment by LewdHuTao** [comment]
uh ig your bot token just leaked…

**Comment by ItzCuteAkemi** [comment]
Do you change your bot config and upload it to forked repo?

**Comment by JotaroKujo0525** [comment]
@TopClips
Hello and good morning (evening here)! We are terribly sorry for your experience but we just own the code you're using. Someone might have leaked your token, or in fact, it's a github user name Sawadalla or smth.
So now, let's make things clear and straightforward, we just own the code, you leaked your token, someone committed your token in our repo and boom, here we are now. You need to be vigilant in your token, or else kaboom, you will get nuked by some people.
This is not a bug, rather just you being carefree on your token.

**Comment by JotaroKujo0525** [comment]
Aight I checked it, your token was leaked by a pull request opened by @sawadalla

**Comment by TopClips** [comment]
> Aight I checked it, your token was leaked by a pull request opened by @sawadalla

Ok. Tbh I already knew it wasn’t you guys and I was just doing it to take my anger out on you. Could you also privately dm me this “token leak” @ TopClips#3240

**Comment by TopClips** [comment]
Ohh you probs can’t I forgot they have other tokens
