### ISSUE TITLE
PLAS ADD AUTO PLAY FEATURE

### ISSUE THREAD

**Issue by TREASUREQUESTSERVER** [SudhanPlayz/Discord-MusicBot#833]
WE WANT AUTOPLAY FEATURE LIKE ONE SONG END THEN PLAY NEW SONG

**Comment by JotaroKujo0525** [comment]
WOW THATS CRAZY

**Comment by JotaroKujo0525** [comment]
anw jokes aside, autoplay feature are yet to be added, i'm not sure if it will be added

**Comment by JotaroKujo0525** [comment]
because honestly , it doesn't really seem like a necessary feature to add in the first place

**Comment by BioCla** [comment]
Isn't autoplay already implemented in erela.js by default?
referring to the Manager class options argument `autoPlay: boolean`
![image](https://user-images.githubusercontent.com/81859084/167076333-69d6b381-c54b-48ec-a409-2eb15862be58.png)
