### ISSUE TITLE
All Commands require Dj Role

### ISSUE THREAD

**Issue by Your-Trash-kid** [SudhanPlayz/Discord-MusicBot#834]
**Please describe the problem you are having in as much detail as possible:**
When the dj role is set in a server you need the dj role to use any commands

**Include a reproducible code sample here, if possible:**
```js
/**
 *
 * @param {require("../structures/DiscordMusicBot")} client
 * @param {require("discord.js").Message} message
 * @returns {void} aka: nothing ;-;
 */

module.exports = async (client, message) => {
  if (message.author.bot || message.channel.type === "dm") return;
  let prefix = client.botconfig.DefaultPrefix;

  let GuildDB = await client.GetGuild(message.guild.id);
  if (GuildDB && GuildDB.prefix) prefix = GuildDB.prefix;

  //Initialize GuildDB
  if (!GuildDB) {
    await client.database.guild.set(message.guild.id, {
      prefix: prefix,
      DJ: null,
    });
    GuildDB = await client.GetGuild(message.guild.id);
  }

  //Prefixes also have mention match
  const prefixMention = new RegExp(`^<@!?${client.user.id}> `);
  prefix = message.content.match(prefixMention)
    ? message.content.match(prefixMention)[0]
    : prefix;

  if (message.content.indexOf(prefix) !== 0) return;

  const args = message.content.slice(prefix.length).trim().split(/ +/g);
  //Making the command lowerCase because our file name will be in lowerCase
  const command = args.shift().toLowerCase();

  //Searching a command
  const cmd =
    client.commands.get(command) ||
    client.commands.find((x) => x.aliases && x.aliases.includes(command));

  //Executing the codes when we get the command or aliases
  if (cmd) {
    if (
      (cmd.permissions &&
        cmd.permissions.channel &&
        !message.channel
          .permissionsFor(client.user)
          .has(cmd.permissions.channel)) ||
      (cmd.permissions &&
        cmd.permissions.member &&
        !message.channel
          .permissionsFor(message.member)
          .has(cmd.permissions.member)) ||
      (cmd.permissions &&
        GuildDB.DJ &&
        !message.channel
          .permissionsFor(message.member)
          .has(["ADMINISTRATOR"]) &&
        !message.member.roles.cache.has(GuildDB.DJ))
    )
      return client.sendError(
        message.channel,
        "Missing Permissions!" + GuildDB.DJ
          ? " You need the `DJ` role to access this command."
          : ""
      );
    cmd.run(client, message, args, { GuildDB });
    client.CommandsRan++;
  } else return;
};
```
The code above is what is sending the error, and it dose not check what command is run and just sends a error if they have dj role, we need to check what command is run to make commands like help accessible 

**Further details:**

- discord.js version: v12.5.3
- Node.js version: v12.22.10
- Operating system: Replit
- Priority this issue should have – please be realistic and elaborate if possible: High

**Relevant client options:**

- partials: none
- gateway intents: Server members, Message content
- other: none

**Comment by BioCla** [comment]
please fill out the issue template accordingly, provide all required information and then some. 
this really doesn't explain much

**Comment by Your-Trash-kid** [comment]
Yes sorry @BioCla i have done what i know now

**Comment by Your-Trash-kid** [comment]
> please fill out the issue template accordingly, provide all required information and then some. this really doesn't explain much

done it

**Comment by BioCla** [comment]
Right, so the problem originates here
```js
//Executing the codes when we get the command or aliases
	if (cmd) {
	// if command has permissions && command has channel permissions && user doesnt have the perms in the channel for the command in that channel
		if ((cmd.permissions && cmd.permissions.channel && !message.channel
			.permissionsFor(client.user).has(cmd.permissions.channel)) 
	// Or the command has permissions && command has member permissions && user inst in the commands member permissions case
		|| (cmd.permissions && cmd.permissions.member && !message.channel
			.permissionsFor(message.member).has(cmd.permissions.member)) 
	// Or the command has permissions && GuildDB has a DJ Role && command caller is not an ADMIN && is not a DJ
		|| (cmd.permissions && GuildDB.DJ && !message.channel
			.permissionsFor(message.member).has(["ADMINISTRATOR"]) && !message.member.roles.cache.has(GuildDB.DJ)))
			return client.sendError(message.channel, "Missing Permissions!" + GuildDB.DJ ? " You need the `DJ` role to access this command." : "");
		cmd.run(client, message, args, { GuildDB });
		client.CommandsRan++;
	} else return;
```

I've commented out what the guards do and it seems pretty evident where the problem is

**Comment by JotaroKujo0525** [comment]
Uh, is this a suggestion or a bug, what specifically, is there a problem to the code that you need to fix or do you want to suggest something?

**Comment by Your-Trash-kid** [comment]
Ok so now what we need to do is we need to see what command they have run before we check if they have DJ role @BioCla, but I don't knownhwo to do that so I'll need you to help me

**Comment by Your-Trash-kid** [comment]
@JotaroKujo0525 it is a bug beacuse the DJ role is ment to allow you to use commands like loop and stuff not making the but full non accesss

**Comment by BioCla** [comment]
> Ok so now what we need to do is we need to see what command they have run before we check if they have DJ role @BioCla, but I don't knownhwo to do that so I'll need you to help me

Well, You would need to modify each command so that it has a property which can be looked at by the handler and determine if it should be a DJ Role only command or not, if so then verify if the user has the required role/permissions and execute if everything seems in check:

example:

```js
module.exports = {
    name: "test",
    ...properties,
    DJOnly: true,
    run: ...
}
````
and in the handler:
```js
if (GuildDB.DJ && cmd.DJOnly && !message.member.roles.cache.has(GuildDB.DJ)) {
    return ...
}
```
Taken, this should be an || in the big `if` clause

**Comment by Your-Trash-kid** [comment]
> 

i have no idea how to add this so youre have to help me in discord, name **pᴉʞ ɥsɐɹʇ ɹnoʎ#1399** msg me when your free and ill msg you back :)
