### ISSUE TITLE
idk random thing

### ISSUE THREAD

**Issue by txj-xyz** [SudhanPlayz/Discord-MusicBot#837]
https://github.com/SudhanPlayz/Discord-MusicBot/blob/1a096c5caa10b72fb07b9c03cf14cc9830d4e7a9/events/voiceStateUpdate.js#L12-L13

not sure if you care about this, but this is extremely memory inefficient

**Comment by BioCla** [comment]
Those variables are automatically freed once the event closes, JS has an integrated [Garbage Collector](https://en.wikipedia.org/wiki/Garbage_collection_(computer_science)) and is very efficient in allocating memory, the life span of those variables isn't very high as they are only used once and then discarded.
more info [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management)

**Comment by txj-xyz** [comment]
oh gotcha, been staring at C too much, thanks LOL
