### ISSUE TITLE
help command issue

### ISSUE THREAD

**Issue by Ronak83s** [SudhanPlayz/Discord-MusicBot#84]
The help command doesn't looks properly in phone.
I am uploading both screenschots of phone and pc.
The formatting of help command looks ugly in phone.
In phone there are single inverted commas in both side of all commands.
![Screenshot_2021-01-10-20-26-41-586_com discord](https://user-images.githubusercontent.com/72686370/104126440-91172880-5382-11eb-9296-b13a460dcd01.jpg)
![unknown](https://user-images.githubusercontent.com/72686370/104126443-95dbdc80-5382-11eb-9840-825b654e4e3d.png)

**Comment by skyventuree** [comment]
I posted a PR for this issue. Hope he will merge it soon.

**Comment by SudhanPlayz** [comment]
Fixed
