### ISSUE TITLE
Replit stuck. Shows "Failed to connect, retrying"

### ISSUE THREAD

**Issue by TheCoderSimp** [SudhanPlayz/Discord-MusicBot#842]
![image](https://user-images.githubusercontent.com/102155498/168716242-99ff7cd9-3f3d-4c39-92db-59936a95121a.png)

**Comment by JotaroKujo0525** [comment]
Not a bug, replits issue or your Internet issue, thx

**Comment by JotaroKujo0525** [comment]
We can't solve this problem unfortunately

**Comment by JotaroKujo0525** [comment]
Oh I forgot. You can create another project for this, see if that solves it, basically repeat all the steps again
