### ISSUE TITLE
[v5] Make bot retry playing a song on error.

### ISSUE THREAD

**Issue by alou-S** [SudhanPlayz/Discord-MusicBot#844]
Basically the bot has a chance to show up a playback error once in a while. 
![image](https://user-images.githubusercontent.com/73123610/169365752-59f982d0-b3f7-4b9b-b04a-68a0e41af7b0.png)

**YES,** I know its a LavaLink issue and all but I guess it would be nice if the bot just kindly retried playing the song on error rather than going to next song in the list. Like 3 tries and then moves to next song. 

LavaLink Logfile containing the error
[lavalink.log](https://gist.github.com/alou-S/8c7f3f2f9d84dda6fb4480e5181d9efc)

**Comment by DarrenOfficial** [comment]
increase the retryLimit on lavalink.
