### ISSUE TITLE
Add Leave command

### ISSUE THREAD

**Issue by Pixel-Gamer** [SudhanPlayz/Discord-MusicBot#85]

**Comment by anny414** [comment]
@Pixel-Gamer Hello sir The Bot left vc After server queue is over If You Use afk command Bot will stay in that vc So when Your servers Queue Will Get over Bot will left vc No need This leave Command @SudhanPlayz If I am wrong  Please tell me

**Comment by OblivionGhoul** [comment]
Or you can easily just code it. Just use this code. 
```javascript
 const voiceChannel = message.member.voice.channel;
 if(!voiceChannel) return message.channel.send("You need to be in a voice channel to stop the music!");
 await voiceChannel.leave();
 await message.react('✅')
 await message.channel.send('Goodbye!')
```

**Comment by Colonel-Ltd** [comment]
Added.
