### ISSUE TITLE
New discord VC channels crash the bot when ANY message is sent

### ISSUE THREAD

**Issue by BuyMyMojo** [SudhanPlayz/Discord-MusicBot#855]
Running the master branch just fine until now but when a single message is sent into the built in text channels that are appart of voice channels now crashes the bot.

**Further details:**

- discord.js version: 12.5.3
- Node.js version: v14.17.3
- Operating system: Windows server 2019
- Priority this issue should have – please be realistic and elaborate if possible: Probably very high since if anyone uses these channels it breaks the bot for everyone.

**Comment by JotaroKujo0525** [comment]
well, you're using a deprecated version (12.5.3) and that feature is new so ye, like threads, you can't interact with it

**Comment by XstreamSpeed** [comment]
Use the v5 branch and go on from there

**Comment by BioCla** [comment]
update your discord.js package to the latest version 13.8.0

**Comment by JotaroKujo0525** [comment]
I tried using 13.8.0 on my bot and its running just fine

**Comment by BioCla** [comment]
can this be closed?

**Comment by JotaroKujo0525** [comment]
h
