### ISSUE TITLE
The error says: (Error: Cannot find module 'discord.js')

### ISSUE THREAD

**Issue by DaveNotAve** [SudhanPlayz/Discord-MusicBot#865]
I'm on replit, i add a Token, and i run it, When i run it, There's have an error says that Error: Cannot find module 'discord.js'

Can anyone help me?

**Comment by LewdHuTao** [comment]
lmao its not even a bug, just install discord.js package and you’re good to go

**Comment by JotaroKujo0525** [comment]
To be exact do `npm i` and also please Google first the problems before making an issue thx, you can now close this
