### ISSUE TITLE
[V5] Autoqueue command repeating same song

### ISSUE THREAD

**Issue by DevAmiyo** [SudhanPlayz/Discord-MusicBot#882]
The new autoqueue command (#871) is adding the same song to the queue.

**Comment by LewdHuTao** [comment]
isn’t it already fixed in #868

**Comment by DevAmiyo** [comment]
> isn’t it already fixed in #868

It was.. but then in #871 it was changed to autoqueue and that doesn't seem to work it just keeps on repeating the same track.

**Comment by DevAmiyo** [comment]
👍
