### ISSUE TITLE
Ping & Uptime command 

### ISSUE THREAD

**Issue by Ronak83s** [SudhanPlayz/Discord-MusicBot#92]
Add Ping & Uptime command.

**Comment by DarkTheif** [comment]
well I already did this so here add a new file in commands called ping.js and put this code in

`const discord = require("discord.js");

module.exports = {
  info: {
    name: "ping",
    description: "To see the ping of the bot",
    usage: "[ping]",
    aliases: ["pg"],
  },
  
  run: async (client, message, args) => {
    
    let embed = new discord.MessageEmbed()
    .setDescription(`Pong - ${client.ws.ping}ms`)
    .setColor("RANDOM")
    .setFooter(`Requested by ${message.author.username}`)
    
    message.channel.send(embed)
  }
}`

**Comment by SudhanPlayz** [comment]
Nope
