### ISSUE TITLE
Slash Commands rename request /Leave -> /Stop and /playing -> /nowplaying

### ISSUE THREAD

**Issue by Saud-97** [SudhanPlayz/Discord-MusicBot#920]
Renaming ` /Leave -> /Stop `to correctly name it since now it doesn't cause 247 enabled players to actually leave rather it would only stop. #910 

I would actually suggest to not immediately kick the bot from channel rather leave it and it will leave on its own anyways after it timeouts.

Renaming `/playing -> /nowplaying` since /playing is sharing same letters as /play which will mess on how discord is sorting the commands based on usage. also nowplaying is a more expressive name to represent the functionality.

**Comment by BioCla** [comment]
> `/Nowplaying` since its already widely used in bots and people are used to it.

It has been done 👍
