### ISSUE TITLE
Code is stuck on repl.it

### ISSUE THREAD

**Issue by ArpitJacob805** [SudhanPlayz/Discord-MusicBot#925]
The Bot was working properly fine but I don't know how it became offline in my server so I came to repl.it to stop and run it again. But the code is stuck and not exceeding forward. Please Help.  

code:

 node index.js
Replit system detected, initiating special `unhandledRejection` event listener
20:5:2022 - 5:53 | Info: Web Server has been started
20:5:2022 - 5:53 | Info: Command Loaded: bassboost
20:5:2022 - 5:53 | Info: Command Loaded: bump
20:5:2022 - 5:53 | Info: Command Loaded: clear
20:5:2022 - 5:53 | Info: Command Loaded: config
20:5:2022 - 5:53 | Info: Command Loaded: disconnect
20:5:2022 - 5:53 | Info: Command Loaded: grab
20:5:2022 - 5:53 | Info: Command Loaded: help
20:5:2022 - 5:53 | Info: Command Loaded: invite
20:5:2022 - 5:53 | Info: Command Loaded: loop
20:5:2022 - 5:53 | Info: Command Loaded: loopqueue
20:5:2022 - 5:53 | Info: Command Loaded: lyrics
20:5:2022 - 5:53 | Info: Command Loaded: move
20:5:2022 - 5:53 | Info: Command Loaded: nowplaying
20:5:2022 - 5:53 | Info: Command Loaded: pause
20:5:2022 - 5:53 | Info: Command Loaded: play
20:5:2022 - 5:53 | Info: Command Loaded: queue
20:5:2022 - 5:53 | Info: Command Loaded: remove
20:5:2022 - 5:53 | Info: Command Loaded: resume
20:5:2022 - 5:53 | Info: Command Loaded: search
20:5:2022 - 5:53 | Info: Command Loaded: seek
20:5:2022 - 5:53 | Info: Command Loaded: shuffle
20:5:2022 - 5:53 | Info: Command Loaded: skip
20:5:2022 - 5:53 | Info: Command Loaded: skipto
20:5:2022 - 5:53 | Info: Command Loaded: stats
20:5:2022 - 5:53 | Info: Command Loaded: volume
20:5:2022 - 5:53 | Info: Command Loaded: youtube
20:5:2022 - 5:53 | Info: Event Loaded: guildCreate
20:5:2022 - 5:53 | Info: Event Loaded: message
20:5:2022 - 5:53 | Info: Event Loaded: raw
20:5:2022 - 5:53 | Info: Event Loaded: ready
20:5:2022 - 5:53 | Info: Event Loaded: voiceStateUpdate
  

![Screenshot 2022-06-20 112509](https://user-images.githubusercontent.com/107832724/174535706-445c25cf-902f-4fdd-85c5-b7f5d3471ae0.png)

**Comment by JotaroKujo0525** [comment]
`kill 1` on shell, the try again. This was due to rate limit on replit systems

**Comment by ArpitJacob805** [comment]
Yeah! It worked, thank you so much @JotaroKujo0525
