### ISSUE TITLE
v5 Lyrics - missing last line in every lyrics

### ISSUE THREAD

**Issue by urbels** [SudhanPlayz/Discord-MusicBot#928]
Every song lyrics requested are missing last line. Maybe API does it, cant check.

**Comment by DarrenOfficial** [comment]
> Every song lyrics requested are missing last line. Maybe API does it, cant check.

can you provide the song that you're trying to search

**Comment by DarrenOfficial** [comment]
> man, blame genius

my api just get's it from genius directly

**Comment by DarrenOfficial** [comment]
> > > Every song lyrics requested are missing last line. Maybe API does it, cant check.
> > 
> > 
> > can you provide the song that you're trying to search
> 
> Just tried Nine Million Bicycles - Katie Melua. Last line bot reports is "And there are nine-million bicycles in Beijing". Actual last line is "And you know that I will love you till I die!".

I just checked, it seems like it's not just my api that are cutting the last line. check out: https://api.popcat.xyz/lyrics?song=Nine%20Million%20Bicycles%20-%20Katie%20Melua, https://some-random-api.ml/lyrics?title=Nine%20Million%20Bicycles%20-%20Katie%20Melua

I'm quite sure genius changes something at their end. I'll try to debug & fix it if possible.

**Comment by JotaroKujo0525** [comment]
Uh @DarrenOfficial I did a thing where it uses `lyrics-finder` just like in v4, in my case, it's working pretty well, imma send the code to you in your dms

**Comment by DevAmiyo** [comment]
Idk how to implement musixmatch api but musixmatch seems to have many lyrics genius doesn't. I've encountered it so many times Darren's api / genius just not having the lyrics I want but musixmatch does.

**Comment by DarrenOfficial** [comment]
> musixmatch seems to have many lyrics genius doesn't.

You are correct, also you need to contact someone at musixmatch to get access to their API :kekw:. 
Also, from what I know musixmatch is expensive af https://about.musixmatch.com/business/pricing-plans

![image](https://user-images.githubusercontent.com/55406094/175651709-b1da3b79-cee3-4040-92be-d2ba27c2708b.png)

**Comment by DarrenOfficial** [comment]
Expensive, because licensing coverage cost a lot of money.

**Comment by DevAmiyo** [comment]
;-;

**Comment by urbels** [comment]
genius web seems to return all the lyrics. Could be just their api that cuts it off.

**Comment by JotaroKujo0525** [comment]
so uh @urbels, is the bug fixed yet?

**Comment by urbels** [comment]
> so uh @urbels, is the bug fixed yet?

no, nothing changed

**Comment by Neko-Life** [comment]
> genius web seems to return all the lyrics. Could be just their api that cuts it off.

Ikr. @DarrenOfficial y u dum

**Comment by DarrenOfficial** [comment]
> > genius web seems to return all the lyrics. Could be just their api that cuts it off.
> 
> Ikr. @DarrenOfficial y u dum

no. there's nothing I can do, that's the way that I got the lyrics. I checked it.
