### ISSUE TITLE
Resume Command

### ISSUE THREAD

**Issue by OblivionGhoul** [SudhanPlayz/Discord-MusicBot#93]
The resume command is not working after you pause it. There is a message that sends to say that the music is resumed, but nothing is playing.

**Comment by Colonel-Ltd** [comment]
Tested and pause, resume commands works perfectly, Try update your project latest version

**Comment by OblivionGhoul** [comment]
I downloaded the GitHub code today and put my token in the ENV file and ran the bot. All the other commands were working.

**Comment by OblivionGhoul** [comment]
For me, I had to pause it and resume it again for it to work

**Comment by OblivionGhoul** [comment]
Since I figured that out for me, I just changed the code in the resume.js file to this. 
```javascript
serverQueue.connection.dispatcher.resume();
serverQueue.connection.dispatcher.pause();
serverQueue.connection.dispatcher.resume();
```

**Comment by Colonel-Ltd** [comment]
Resolved.
