### ISSUE TITLE
rename config.js ?

### ISSUE THREAD

**Issue by Hiura-Souji** [SudhanPlayz/Discord-MusicBot#931]
Hello

Is it convenient to rename config.js to config-example.js or something?
This makes it easy to update with git pull :)

thank you~

**Comment by SudhanPlayz** [comment]
> Hello
> 
> Is it convenient to rename config.js to config-example.js or something? This makes it easy to update with git pull :)
> 
> thank you~

you can use `dev-config.js`*(create the file and copy `config.js`)* file if you wanted to code something in development mode or something else
