### ISSUE TITLE
Enhancement request for repo git history

### ISSUE THREAD

**Issue by Saud-97** [SudhanPlayz/Discord-MusicBot#933]
**Is your feature request related to a problem? Please describe.**
There was a draft branch that I have created to view differences but it got merged by mistake and then reverted.

Can you please squash these two commits? I can't sync my fork because the history reverted all my changes as part of the commits. 

Just squish this revert https://github.com/SudhanPlayz/Discord-MusicBot/issues/909 with the one before it or delete them from history then force-push. The history is broken atm and I can't sync cuz of this.

Maybe its better to completely delete these two commits from history and force-push. Squashing might still not work good.

_Originally posted by @Saud-97 in https://github.com/SudhanPlayz/Discord-MusicBot/issues/909#issuecomment-1159569524_

**Describe alternatives you've considered**
Creating another branch and moving my changes there but that result in me losing all my history and having to patch all my changes inside 1 big commit.

This is preventing me from easily creating PRs from my old commits that I can view from my old history.

**Comment by DarrenOfficial** [comment]
> Can you please squash these two commits?

No, your commit changes unnecessary stuff.

**Comment by DarrenOfficial** [comment]
We can't delete the commit.
