### ISSUE TITLE
Replit node16 

### ISSUE THREAD

**Issue by JotaroKujo0525** [SudhanPlayz/Discord-MusicBot#940]
In #923 , it added discord.js v13 support on `master` branch, however, peeps on replit can't install it just by cloning the repo.They need to install node 16, soooo ye on `master` there's no script like `kickstartReplit.sh` on it. So ig we need to make a script like that in `master`

I'm sending this to spread awareness, i'll close this when this feature is added

**Comment by JotaroKujo0525** [comment]
If you're on replit, you may encounter this issue 
```
Error: Cannot find module 'node:events'
```

**Comment by DevAmiyo** [comment]
I've tried all aways to update replit to node16 but it just resets to node14.

**Temporary workaround:**
- Open `.replit` file.
- Change `run = "node index.js"` to `run = "npx node index.js"`.
- Restart your repl. If it doesn't work, run `kill 1` in console.

**Comment by DevAmiyo** [comment]
Gonna create a PR making these changes...
