### ISSUE TITLE
Ping command (I already made it just use this code)

### ISSUE THREAD

**Issue by DarkTheif** [SudhanPlayz/Discord-MusicBot#95]
const discord = require("discord.js");

module.exports = {
  info: {
    name: "ping",
    description: "To see the ping of the bot",
    usage: "[ping]",
    aliases: ["pg"],
  },
  
  run: async (client, message, args) => {
    
    let embed = new discord.MessageEmbed()
    .setDescription(`Pong - ${client.ws.ping}ms`)
    .setColor("RANDOM")
    .setFooter(`Requested by ${message.author.username}`)
    
    message.channel.send(embed)
  }
}

**Comment by Colonel-Ltd** [comment]
This just shows websocket ping not the latency between message and bot's response.

**Comment by DarkTheif** [comment]
ah Good Point this should do it xd If not then Im a dumbass 

const discord = require("discord.js");

module.exports = {
  info: {
    name: "ping",
    description: "To see the ping of the bot",
    usage: "[ping]",
    aliases: ["pg"],
  },
  
  run: async (client, message, args) => {
    
    let embed = new discord.MessageEmbed()
    .setDescription(`Pong ${Math.floor(client.ws.ping)}`)
    .setColor("RANDOM")
    .setFooter(`Requested by ${message.author.username}`)
    
    message.channel.send(embed)
  }
}

**Comment by DarkTheif** [comment]
oh yea I am a dumbass here give me a few mins

**Comment by DarkTheif** [comment]
ok here this should be it sorry Im a dumbass 

const discord = require("discord.js");

module.exports = {
  info: {
    name: "ping",
    description: "To see the ping of the bot",
    usage: "[ping]",
    aliases: ["pg"],
  },
  
  run: async (client, message, args) => {
    
    let embed = new discord.MessageEmbed()
    .setDescription(` 🏓Latency is ${Date.now() - message.createdTimestamp}ms. \n🏓API Latency is ${Math.round(client.ws.ping)}ms`)
    .setColor("RANDOM")
    .setFooter(`Requested by ${message.author.username}`)
    
    message.channel.send(embed)
  }
}

**Comment by SudhanPlayz** [comment]
No need of this command for now I will do everything combined at v4
