### ISSUE TITLE
Current master branch bugs

### ISSUE THREAD

**Issue by JotaroKujo0525** [SudhanPlayz/Discord-MusicBot#954]
![Screenshot_20220628_104203](https://user-images.githubusercontent.com/77835007/176080465-b9ac77c8-40cf-42ff-9900-cd135565ed6f.jpg)
Won't give any details from this, currently testing the `master` branch, and there's a hefty lot of bugs here. I'll debug all of the stuffs that are wrong in the code and put it here

**Comment by JotaroKujo0525** [comment]
![Screenshot_20220628_104203](https://user-images.githubusercontent.com/77835007/176080857-d51b0c06-8691-45f2-8b7b-f8332301bfce.jpg)

Commands that are affected with this error: (image on top) (to be updated) 
-help
-config

**Comment by JotaroKujo0525** [comment]
This is really bad, there are so many commands with error, even the functions are getting altered

**Comment by JotaroKujo0525** [comment]
I recommend reverting back to `ed1812f37b7450ade78b160691b1333a0bbfe544`

**Comment by Saud-97** [comment]
ed1812f37b7450ade78b160691b1333a0bbfe544

**Comment by JotaroKujo0525** [comment]
Fixed in #953
