### ISSUE TITLE
Enable Squash PR commits by default

### ISSUE THREAD

**Issue by Saud-97** [SudhanPlayz/Discord-MusicBot#959]
Please setup these configs in Github Repo settings to make the repo PR commits cleaner and concise.

![image](https://user-images.githubusercontent.com/39028181/176746884-968f65d6-a08f-4aa2-8f64-5e0bbf9a5ce5.png)

**Comment by JotaroKujo0525** [comment]
@SudhanPlayz wake up

**Comment by SudhanPlayz** [comment]
done

**Comment by Saud-97** [comment]
@SudhanPlayz Is the configuration changed again or what happened cuz there are still pull requests not squashed and create many commits.

![image](https://user-images.githubusercontent.com/39028181/178104259-fbf74adc-ef05-4181-a166-0969131806dc.png)

**Comment by Saud-97** [comment]
Should probably copy exact configs like I shared in the issue. To make it forced squash instead of optional.

**Comment by Saud-97** [comment]
Kindly someone reopen this.
