### ISSUE TITLE
Update nowplaying message instead of resending when possible 

### ISSUE THREAD

**Issue by Saud-97** [SudhanPlayz/Discord-MusicBot#982]
**Is your feature request related to a problem? Please describe.**
Do not re-send new nowplaying msg if it was the last message in channel, update it instead.
It would be better to not send a new message. 
This way we can reduce the delete requests to Discord API for the old message. 

**Describe the ideal solution**
I already did the update logic in the controller.js. However I'm not sure how to update the nowplaying message. 

**Additional context**

How now playing message is sent.
https://github.com/SudhanPlayz/Discord-MusicBot/blob/209e730e88afd04a0a28c2c19a730cdb589e5607/lib/EpicPlayer.js#L90-L135

Update logic I've done before.

https://github.com/SudhanPlayz/Discord-MusicBot/blob/c8aa819226d8932c3beb91adb53a6babfad91870/util/Controller.js#L105-L107

**Comment by BioCla** [comment]
I don't see this a a particularly good idea, unless the bot is only used in a single channel in which only slash commands would be allowed, which i see as very unlikely.
The point of resending the message each time a new song comes on is to allow the user to be certain of the track that's playing, without having to scroll all the way back up, in case the channel is actively used.
Also the API doesn't really care for the message send and delete requests as long as they're within a certain threshold of messages per second.

**Comment by Saud-97** [comment]
I just realized that I was showing the send now playing message logic from my fork does not come from upstream. I have succeeded in implementing this but since my fork is quite different already I won't PR this.
If anyone interested, here is the commit 25c9d733586712e18ee8351be8263b3d6932d72b.
