### ISSUE TITLE
Previous cannot reach to the beginning of queue

### ISSUE THREAD

**Issue by Saud-97** [SudhanPlayz/Discord-MusicBot#983]
**Please describe the problem you are having in as much detail as possible:**
Play any playlist. When you finish it try to go back to the first song played in queue. 
There is no way currently to go back it will get stuck instead to the second to last song in queue iirc.

### Essentials:

- Bot Version: v5
- Commit Hash: 1439b3ad52184e4471c654850c888a4e93760afa
- Node.js version: 18
- Operating system: Linux

#### Additional system info
- Is it virtualized? (Docker or ...) : Heroku
- What CPU is it running on (X86 or ARM or...): Heroku
- Additional details that might help us figure out the problem: 
**This is the second time I open the issue, first one got closed for no reason #937 (also wrongly closed as completed).** 

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by JotaroKujo0525** [comment]
Why didn't you reopen the othe issue you created?

**Comment by Saud-97** [comment]
Issues cannot be reopened by user if it was closed by maintainers.

**Comment by JotaroKujo0525** [comment]
Ah alrighty then, you can continue on this issue

**Comment by SudhanPlayz** [comment]
isnt that what it supposed to do...?

**Comment by Saud-97** [comment]
> isnt that what it supposed to do...?

Previous only works once and can't go back to any earlier songs played before in queue.

Try to play 4 songs A, B, C, D. When you reach D song, you cannot go back and listen to A, B because player will only last and before last songs.

I don't think this is the expected behavior considering the player already has a queue so why not utilize it.

**Comment by SudhanPlayz** [comment]
Well for me this is the expected behavior. If you want like that you can do it on your own bot.
