### ISSUE TITLE
Efficient leave and join.

### ISSUE THREAD

**Issue by anushshetty8** [SudhanPlayz/Discord-MusicBot#99]
Description:
The bot must know when to leave a VC and join another requested one, if there is a song playing in the former VC but no one's listening.

Steps to reproduce:
1) Join a VC.
2) Play a song
3) Leave the VC
4) Join another VC
5)Ask for song.
The bot will continue to play the song on the previous VC itself, but won't join the new one untill the song is over.

What should happen:
Let's consider Groovy, if someone plays a song in a VC and leaves the VC, joins another VC and asks for a song Groovy will quit the previous VC and join this one. But if someone is listening a song in a VC and someone else tries to connect it to another VC Groovy says 'Someone is already listening' as soon as the listener leaves the VC and lets Groovy alone, the 2nd person will be able to make Groovy join his VC.

This is exactly what should happen.

**Comment by anushshetty8** [comment]
If you didn't get what I mean ping me, I'll elaborate.

**Comment by Colonel-Ltd** [comment]
The bot will continue to play the song on the previous VC itself, ؟

**Comment by anushshetty8** [comment]
> The bot will continue to play the song on the previous VC itself, ؟

That shouldn't happen, think about it. If someone leaves the bot alone playing a song, someone else who wants to listen to a song in another VC will have to wait till all the queued songs are over.

**Comment by anushshetty8** [comment]
@Colonel-Ltd

**Comment by kaaax0815** [comment]
+1

**Comment by booleans-oss** [comment]
Is anyone working on this suggestion ?

**Comment by skyventuree** [comment]
For this scenario, I'd prevent user from choosing new song unless the bot is in the corresponding voice chat. (Bot should be in the same channel as user did, as it would do before.)

**Comment by SudhanPlayz** [comment]
Thanks for your suggestion, it has been added in TO-DO list of Discord Music Bot v4, which will be launched in a short period of time!
