### ISSUE TITLE
error question

### ISSUE THREAD

**Issue by LucasB25** [SudhanPlayz/Discord-MusicBot#990]
there would be something to prevent this kind of error while playing music?

The uploader has not made this video available in your country,
This video contains content from [Merlin] IDOL Distribution, who has blocked it in your country on copyright grounds,
This video is not available,
The uploader has not made this video available..

**Comment by JotaroKujo0525** [comment]
Nah, this is the limitations of lavalink, you can add a gmail account to access age restricted videos. But, for the videos not available in the country the code is hosted, then you cant do anything about it.

Also remove bug label this isn't a bug

**Comment by LucasB25** [comment]
Yeah, but how’d they get out of the code?

**Comment by JotaroKujo0525** [comment]
As i said, it's the limitations of lavalink

**Comment by JotaroKujo0525** [comment]
If the video is;
-not available in your country
-age restricted (you can prevent this)
-copyright stuffs
-the author limited the access of the video,
Then I'm afraid there's nothing you can do

**Comment by LucasB25** [comment]
But in this directory, there is not a message telling users these errors?

**Comment by JotaroKujo0525** [comment]
What do you mean at `in this directory`

**Comment by LucasB25** [comment]
In the github `discord-musicbot` directory have you added code that signals users who listen to music, this error feedback when it emits a song with the bot?
