### ISSUE TITLE
V5 | Language files

### ISSUE THREAD

**Issue by PandaKeny** [SudhanPlayz/Discord-MusicBot#991]
Like the title, I want a separate language file and people can translate bots in many different languages.

**Comment by JotaroKujo0525** [comment]
Hm, ig not really necessary for the whole v5 code as english is.... you know, the language that almost all people know nowadays.
Also, who will translate? Well, we can't also use Google translator as its not accurate

**Comment by JotaroKujo0525** [comment]
It is indeed doable, but not the type that we really need

**Comment by PandaKeny** [comment]
Translators can be all those who want bot translation can support, I know English is a popular language but there will definitely be people who are not good at English, language files to be more friendly to people and the language of their country.

**Comment by JotaroKujo0525** [comment]
@DarrenOfficial @SudhanPlayz your thoughts?

**Comment by JotaroKujo0525** [comment]
Also I'll convert this to an idea discussion to not mix up with other issues
