### ISSUE TITLE
Play Command

### ISSUE THREAD

**Issue by Nooby69** [SudhanPlayz/Discord-MusicBot#994]
Whenever u play and the nowplaying comes it don't get deleted 
autoqueue feature if enabled the nowplaying message will spam 
I request u to make it to get it deleted when other song plays.

**Comment by JotaroKujo0525** [comment]
How bad is this *spam*

**Comment by Nooby69** [comment]
> How bad is this _spam_

The more u play the more the messages are if they get deleted its better.

**Comment by JotaroKujo0525** [comment]
well,if that's the case, ig it's much better to put slowmode in every command and can be toggled by the config

**Comment by JotaroKujo0525** [comment]
deleting the now playing message in unnecessary as its purpose is to show the current playing message

**Comment by Neko-Life** [comment]
Good issue. 
Basically:
```js
// discord channel garbage collector
if (new_song_playing) old_nowplaying_embed.delete();
if (play_command_embed.age > 10) play_command_embed.delete();
```

**Comment by JotaroKujo0525** [comment]
sooo, we doing this?

**Comment by Nooby69** [comment]
> Good issue. Basically:
> 
> ```js
> // discord channel garbage collector
> if (new_song_playing) old_nowplaying_embed.delete();
> if (play_command_embed.age > 10) play_command_embed.delete();
> ```

Yes something like this please

**Comment by Nooby69** [comment]
> deleting the now playing message is kinda unnecessary as its purpose is to show the current playing message

Every time new nowplaying message comes old stays there which looks like a spam

**Comment by Nooby69** [comment]
**Btw its for v5 just telling because I don't want confusion and I didn't mentioned it**

**Comment by Nooby69** [comment]
**Can someone approve this and make it official**

**Comment by JotaroKujo0525** [comment]
well,if somebody were willing to work on this, alternatively, you can also find a way to do this and make a pull request

**Comment by Neko-Life** [comment]
Sure I can see and implement it later tonight

**Comment by Nooby69** [comment]
**Thanks**
